### ISSUE TITLE
How to use registerFactory ?

### ISSUE THREAD

**Issue by hieuseesaa** [fluttercommunity/get_it#101]
Hello

I have 2 class

```
abstract class UserRepository {
  Future<User> getUser;
}
```

```
class UserRepositoryImpl implements UserRepository {
  @override
  Future<User> getUser() {
   // ..... logic
  }
}

```

I use like below

   ```

 sl.registerFactory<UserRepository>(
        () => UserSummaryRepositoryImpl());
```

on main.dart

```
UserRepository _userRepository = sl.get(); 
_userRepository.getUser();
```

And get error below

```
No type UserRepositoryImpl is registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;did you forget to register it?)
'package:get_it/get_it_impl.dart':
Failed assertion: line 251 pos 14: 'instanceFactory != null'
```

NOTE: If I use the following then it works. But it is not clear.

```
    sl.registerSingleton(UserRepositoryImpl());
    sl.registerFactory<UserRepository>(
            () => sl.get<UserRepositoryImpl>());
```

Please help me solve the above case. thank you very much

**Comment by escamoteur** [comment]
From the code above this seems a bit strange to me. I always recomment passing the Generic type when you use `get`.
you can then write `sl<MyType>()` and omit the get.

What I don't understand is this here:

```Dart
sl.registerFactory<UserRepository>(
     () => UserSummaryRepositoryImpl());
```
where you use a complete different Implementation than the one in your error Message.
Please create a small repro project on GitHub, so that I can have a closer look

**Comment by hieuseesaa** [comment]
@escamoteur hello sir
I created a sample project
Please check here.
https://github.com/hieuseesaa/test_floor

- Please help me fix with https://github.com/fluttercommunity/get_it/issues/99 
Thank you very much

**Comment by escamoteur** [comment]
you mixed up async registration and sync call of `get`

your function must look like
```Dart
  static _registerDatabase() async {
    AppDatabase database =
        await $FloorAppDatabase.databaseBuilder('test.db').build();
    sl.registerLazySingleton(() => database.userDao);
  }
```

**Comment by hieuseesaa** [comment]
@escamoteur  thank you. It worked. 

Can you help me with this question?

I'm android developer. I used  https://github.com/InsertKoinIO/koin to inject function.
for classes UserRepository and UserRepositoryImpl. I just used the following

    factory<UserRepository> {
        UserRepositoryImpl()
    }

But for get_it. I need to do the following

  sl.registerSingleton(UserRepositoryImpl());
  sl.registerFactory<UserRepository>(() => sl.get<UserRepositoryImpl>());

=====> So for get_it. Is there a way to do the same as koin ?. Please help me. Thank you very much.

**Comment by escamoteur** [comment]
What are you trying to do there?
´´´
sl.registerSingleton(UserRepositoryImpl());
sl.registerFactory(() => sl.get());
´´´
I would just do:

```Dart
sl.registerSingleton<UserRepository>(UserRepositoryImpl());
```

**Comment by hieuseesaa** [comment]
@escamoteur Thank you very much. It worked.

**Comment by hieuseesaa** [comment]
@escamoteur 
Hello sir. I have a problem.

When I add UserDao inside UserRepositoryImpl. It show error. 

I use like below

```
class UserRepositoryImpl implements UserRepository {
  UserManager manager;
  UserDAO userDAO;

  UserRepositoryImpl(this.manager, this.userDAO);

  @override
  User getUser() {
    manager.test();
    final id = Random.secure().nextInt(1000);
    print("ID ====> $id");
    return User("$id", "Google");
  }

  @override
  void insert(User user) async {
    userDAO.insertUser(user.toUserEntity());
  }
}
```


```
abstract class UserRepository {
  User getUser();
  void insert();
}

```

```
GetIt sl = GetIt.instance;

class ServiceLocator {
  static Future<void> initCommon() async {
    sl.registerSingleton(UserManager());
    await _registerDatabase();
  }


  static _registerDatabase() async {
    AppDatabase database =
        await $FloorAppDatabase.databaseBuilder('test.db').build();
    sl.registerLazySingleton(() => database.userDao);
    sl.registerSingleton<UserRepository>(UserRepositoryImpl(sl.get(), sl.get()));
  }
}
```

This is error

```
The following assertion was thrown building Builder:
No type UserRepository is registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
did you forget to register it?)
'package:get_it/get_it_impl.dart':
Failed assertion: line 257 pos 14: 'instanceFactory != null'
```


Please help me. thank you very much.

**Comment by escamoteur** [comment]
You never registered a type `UserRepository´ in your code. You only registered a derived class. If you would always use the generic types that would not happen to you.

Instead of
```Dart
sl.registerSingleton(UserManager());
```
you have to do

```Dart
sl.registerSingleton<UserRepository>(UserManager());
```
