### ISSUE TITLE
Instantiating lazysingleton with different class factories. 

### ISSUE THREAD

**Issue by casvanluijtelaar** [fluttercommunity/get_it#102]
I have a Service that can be instantiated 2 different ways, by using two factories. however this class gets instantiated I need it to be a lazysingleton.

if I register a singleton like this:
```
locator.registerLazySingleton<Service>(() => Service());
```
then how to I instantiate it with a factory constructor later?
```
Service service = Service.fromJson(data);
```
needs to be instantiated somewhere in here, to get the singleton reference later on.
```
GetIt locator = GetIt.instance;
Service service = locator<Service>();
```

**Comment by escamoteur** [comment]
If you register it as LazySingleton, you can't access it as factory. You can pass a parameter to your factories, so you could register it as factory and pass `data` as parameter. Check the readme on factories with paramters.

**Comment by casvanluijtelaar** [comment]
right but I need the state of that class to persist until I call the reset function?

**Comment by escamoteur** [comment]
I think then factory isn't the right thing. why not using the laszy singleton an do the fromJson in its factory function?

```Dart
locator.registerLazySingleton<Service>(() => Service.fromJson(data));
```

**Comment by casvanluijtelaar** [comment]
because I did not think of that :sweat_smile: . I got into the habit of declaring all lazysingletons and factories in main. But you're absolutely right this sense. Keep up the good work!
