### ISSUE TITLE
How to registerFactory but with dependencies?

### ISSUE THREAD

**Issue by ydhnwb** [fluttercommunity/get_it#104]
How to registerFactory but with dependencies?
For example in Kotlin Koin will be like

```
val networkModule = modules {
     single { RetrofitInstance() }
}

val repoModule = modules {
   //userRepo depends on RetrofitInstance
   factory { UserRepository(get()) }
}
```

How to achieve this in get_it?
I created the setup like this
```
GetIt locator = GetIt.instance;

void setupGetIt() {
  locator.registerSingleton(AppDatabase());

  //then how to register UserRepository with dependencies?


}
```
There is only registerSingletonWithDependencies available, registerFactoryWithDependencies is not exists.
Or maybe there is another approach to achieve this?

**Comment by escamoteur** [comment]
IMHO dependencies don't really make sense for a factory. If you need to be sure that another registered object is available use `allReady` or `isReady` to wait for it.

**Comment by ydhnwb** [comment]
Okay, I will try it
