### ISSUE TITLE
Provide a type or a name

### ISSUE THREAD

**Issue by BrianMwas** [fluttercommunity/get_it#105]
I don't understand why am getting this error

> Failed assertion. GetIt: You have to provide either a name or a type. 
It asks the question whether I registered GetIt right, and I did. It says I should use
`var GetIt getIt = GetIt.instance;`
Am I missing something because I can't seem to find the problem. Everything is as it should be..

**Comment by escamoteur** [comment]
Can you show me the code where you register your Objects and where you access them where you get that exception.

**Comment by BrianMwas** [comment]
Hi, thanks but I found out it was an analyzer issue. I was able to fix it
