### ISSUE TITLE
isRegistered is not working

### ISSUE THREAD

**Issue by rdonoso** [fluttercommunity/get_it#107]
Hello,

I am trying to use the method to check if a singleton is registered, but it seems that i am doing something wrong.

This is an extract of the code and if i use this way always return false and always throw the exception with the next line that is already registered the singleton
`if (!locator.isRegistered(instance: ControlCenterViewModel))`

But this way if the instance is not loaded throw an exception, to make sure that ControlCenterViewModel is in get_it.
`if (!locator.isRegistered(instance: locator<ControlCenterViewModel>()))`

Please help, how i can make this right.

Thanks!

**Comment by escamoteur** [comment]
```
if (!locator.isRegistered(instance: ControlCenterViewModel))
```
you can't pass a type as instance you should do it like:

```
if (!locator.isRegistered<ControlCenterViewModel>( ))
```

**Comment by rdonoso** [comment]
@escamoteur Thank you! it works!
