### ISSUE TITLE
Error with hot reload

### ISSUE THREAD

**Issue by gersonfa** [fluttercommunity/get_it#11]
I am getting this error every time my application is hot reloaded

` Type HttpService is already registered
flutter: 'package:get_it/get_it.dart': Failed assertion: line 53 pos 12: 'allowReassignment ||
flutter: !_factories.containsKey(T)'`

This is my get_it setup
`GetIt sl = new GetIt();

void setupServiceLocator() {
  sl.registerSingleton<HttpService>(new HttpService());
  sl.registerLazySingleton<TransactionService>(() => new TransactionService());
  sl.registerLazySingleton<TransactionManager>(() => new TransactionManagerImplementation());
} `

For solve this I have to make a hot restart, but I don't want to do this every I change my code, can you help me to understand this problem?

**Comment by escamoteur** [comment]
Where do you call your register function? If you do it directly in main before runApp it should not happen.

**Comment by escamoteur** [comment]
Did this solve your problem?

**Comment by gersonfa** [comment]
Sorry, I haven't had noticed you have answered, but yes, that solved my problem. Thanks!

**Comment by MuthuHere** [comment]
sorry guys, i am trying to register with context in this case. If i do hot reload getting this error. I need context to register, so i did inside the 
build(BuildCotext context){
 setsetupLocator(context)
}

so how to do in this case. Thanks

**Comment by josh-ksr** [comment]
@MuthuHere this is possible, but you'll need some logic to handle it inside your GetIt setup code. Here's an example:

```
void setUpServiceLocator(BuildContext context) {
  if (getIt.isRegistered<AppLocalizations>()) {//setup was called before, we only re-register what depends on context
    getIt.unregister<AppLocalizations>();
    getIt.registerSingleton<AppLocalizations>(AppLocalizations.of(context));
    return;
  }
getIt.registerSingleton<AppLocalizations>(AppLocalizations.of(context));
//do all your other setup that's independent of context here
}
```

**Comment by escamoteur** [comment]
@MuthuHere don't do this inside a build function. It can be called anytime. Use a StatefulWidget and access the context in `didChangeDependency`.

What do you want to register that needs a context? Maybe there is a better way to do this.

@josh-ksr  don't use the `.of` to reach something to register in get_it. Instead register `Applocalization` before you call `runApp` directly in get_it as it doesn't depend on the context.

**Comment by josh-ksr** [comment]
@escamoteur I don't think it is possible to use the new flutter localization system without context, at least i haven't found a way to use it without context yet. 
That's why i added a builder to the MaterialApp and setup GetIt inside it, seems to work without problems so far even with hot reload. Or is there any problem with this approach that i just haven't seen yet? Here's some example code:

```
  Widget build(BuildContext context) {
    return MaterialApp(
          builder: (context, widget) {
            setUpServiceLocator(context);
            return FutureBuilder(
                future: getIt.allReady(),
                builder: (BuildContext context, AsyncSnapshot snapshot) {
                  if (snapshot.hasData) {
                    return widget;
                  } else {
                    return Container(color: Colors.white);
                  }
                });
          },
        );
}
```

**Comment by escamoteur** [comment]
yes, that should work fine. I was just looking at the examples here and didn't see why you need the context when creating the AppLocalisation instance.
