### ISSUE TITLE
get_it readme not looking good on pub.dev

### ISSUE THREAD

**Issue by praveeno** [fluttercommunity/get_it#110]
![image](https://user-images.githubusercontent.com/19618730/93954874-24910300-fd6c-11ea-94a1-7dc3f0b82f33.png)
https://pub.dev/packages/get_it

It feel like somehow readme messed up there. it's looking right in github readme.

**Comment by praveeno** [comment]
same on https://pub.dev/documentation/get_it/latest/

**Comment by escamoteur** [comment]
Thanks for reporting. I fixed it.
