### ISSUE TITLE
In 5.x, how to locate named instance without type or using super type?

### ISSUE THREAD

**Issue by Windol** [fluttercommunity/get_it#111]
In a project of mine, I use GetIt to select the parser to be used for each type of JSON using one of the properties of JSON itself. In version 4.x I registered the parsers by name, but I didn't pass a type, because when I parse, I won't necessarily know the exact type. I will probably only know that it is a Widget.

In version 5.x I can't find the parsers because I don't know the exact type.

Is there any way to register for example a `Container` with named instance and find it without passing the type, or passing the super type` Widget` and the name of the instance?

**Comment by escamoteur** [comment]
Yeah, the change was made because users asked to be able to use the same name with different types.
I'm actually not sure if I would use GetIt in such a case at all but implmemt my on `map<String,Parser> and just go from there.

**Comment by Windol** [comment]
Is there any possibility of adding support for both modes of operation? If so, what would be the best way to do it? And how can I contribute?

**Comment by knaeckeKami** [comment]
Couldn't you do

```dart
 GetIt.I.registerSingleton<Widget>(Container(), instanceName : "container");
 GetIt.I.registerSingleton<Widget>(SizedBox.shrink(), instanceName: "sizedbox");

...

final widget = GetIt.I<Widget>(instanceName: myName);

```

?

**Comment by Windol** [comment]
No. I need to be able to do:
```dart
GetIt.I.registerSingleton<Container>(Container(), instanceName: "containerName");

final widget = GetIt.I<Widget>(instanceName: "containerName");
final container = GetIt.I<Container>(instanceName: "containerName");
```

**Comment by escamoteur** [comment]
Why do you have to register it with container as type? using Widget + Name could be a solution

**Comment by Windol** [comment]
Some objects that I need to parse, use the super type, but others use specific implementations. In those cases I would have to register the same parser twice with different types. It is a possibility, but it would no longer be singleton.

**Comment by escamoteur** [comment]
Why can't all your parsers share a common super type?

**Comment by Abion47** [comment]
@Windol 
Why would you need to know that a parser returns a `Widget` some of the time and specifically a `Container` in other times? The vast majority of Flutter build methods only care that they are getting `Widget` objects, which leads me to suspect that this restriction is one you arbitrarily imposed on yourself.

**Comment by Windol** [comment]
@escamoteur, initially my code used the specific type to do some validations, I'm still refactoring the code and checking alternatives to ensure that the validations continue to work properly.

@Abion47 you may be right to be a self-imposed constraint. I am refactoring all the code to test the use of GetIt referencing only the super type.

In relation to the example I set, it is merely illustrative. In reality the objects registered in GetIt are the parsers for each type of class. These parsers are for parsing JSON for `BorderRadius`,` ThemeData`, `Scaffold`,` Container`, etc.

If you are interested in seeing how I implemented the use of GetIt in my project, follow the link for the main class of the project to use GetIt. Comments and suggestions are welcome.

https://github.com/Legytma/schema_widget

https://github.com/Legytma/schema_widget/blob/92d5ef54fbda406b30fb12f1a6609e4bc7aaf4bd/lib/schema_widget.dart#L133-L473

**Comment by Abion47** [comment]
@Windol 
Before even looking at your code, I want to say that it would probably be a bad idea to use GetIt in a package. The global nature of GetIt means that if the people using your package are also using GetIt, they will potentially be competing with you for storage buckets. However unlikely a collision might be, the possibility of you overriding the app's saved values or the app overriding your saved values is reason enough to look for an alternate solution that is limited in scope to your own package code.

If nothing else, at least follow the directions to create a new instance of GetIt that can be specific to your package through `GetIt.asNewInstance()`.
