### ISSUE TITLE
How to unregister an re-registerSingleton properly?

### ISSUE THREAD

**Issue by freewebwithme** [fluttercommunity/get_it#112]
Hi! 
I am using get_it with injectable package.
I need to update some of instance like session and client that is already registered.
In Session case,
I registered session instance manually(not using injectable for session instance) after successfully logged in.
```
final session = Session.fromJson(result.data["logIn"]);

// here  I am updating a session instance
if (getIt.isRegistered<Session>()) {
    getIt.unregister<Session>();
   // Register new session instance
    getIt.registerSingleton<Session>(session);
  } else {
    getIt.registerSingleton<Session>(session);
  }
  
```
But it seems that there is still a old session instance.
Am I doing wrong?

I googled for this and also tried in issues, but I can't find proper answer for me.
And for now I can't upgrade to v5 because getIt V5 is not supported in injectable.

**Comment by escamoteur** [comment]
On first glance, this looks totally fine for me. What do you mean with 'is seems there is an old instance'?
Do you get an exception?

**Comment by freewebwithme** [comment]
Thanks for your reply. Yes the problem was from other thing.
I have more question relating this title.

If instance A(Singleton) is depending on instance B(Singleton), then  some reason I got new instance B.
So I unregister instance B and re-register instance B.
 Do I have to re-register instance A to get a new instance B?

For example
```
@singletone
class AuthenticationApi {
  AuthenticationApi(this.client);
  final GraphQLClient client;
}
```
AuthenticationApi is created at app starts up and client instance also created without auth token.
After login or sign up, I created new instance of client with auth token.
So I did
```
  // creating new client instance
  final client = Client().client();
  if (getIt.isRegistered<GraphQLClient>()) {
    getIt.unregister<GraphQLClient>();
    getIt.registerSingleton<GraphQLClient>(client);
  } else {
    getIt.registerSingleton<GraphQLClient>(client);
  }
```
So I registered new singleton of client.
Do I have to do this for AuthenticationApi instance also?
AuthenticationApi instance still has old client instance?

**Comment by escamoteur** [comment]
You are using injectable right? I have no idea what it does under the hood.
If you are using GetIt manually you don't have such effects.

**Comment by EngGemy95** [comment]
I have the same problem and i did not find any solution .

**Comment by razasubtain** [comment]
final GetIt locator = GetIt.instance;

///[register]
///
void register(BaseOptions dioBaseOptions) {
  p('Base Options===========================> ${dioBaseOptions.baseUrl}');
  locator.registerLazySingleton<DioConfig>(
    () => DioConfig(initialOptions: dioBaseOptions),
  );
  locator.registerLazySingleton<ApiService>(
    () => ApiService(
      dioConfig: locator<DioConfig>(),
    ),
  );}


unRegisterAllLocator() async {

  await locator.unregister<ApiService>();

  await locator.unregister<DioConfig>();
  
}
i have two different configurations for the api's in my application. During login i have different base options and after login i use different baseOptions.After login When i unRegister locators through (**unRegisterAllLocator()** ) and register locator with new baseoptions it works fine and uses the new base options. but when i try to logout the user and unregister the locators and pass the locator with new baseOptions it prints the new baseoptions as i use the p('Base Options===========================> ${dioBaseOptions.baseUrl}'); but when i call the api it somehow uses the old instance with old baseoptions. I am stuck for a while and don't understand why this is happening.

**Comment by escamoteur** [comment]
How should get_it know which object it should unregister if you don't pass the type?

I'm general for your use case of login/logout I recommend using get_it scopes for that. Check the Readme.
Am 1. Feb. 2025, 00:44 +0100 schrieb razasubtain ***@***.***>:

**Comment by razasubtain** [comment]
i have passed the type somehow it is not displayed in the question i share my code again 
void register(BaseOptions dioBaseOptions) {
  p('Base Options===========================> ${dioBaseOptions.baseUrl}');
  locator.registerLazySingleton<DioConfig>(
    () => DioConfig(initialOptions: dioBaseOptions),
  );
  locator.registerLazySingleton<ApiService>(
    () => ApiService(
      dioConfig: locator<DioConfig>(),
    ),
  );
}

unRegisterAllLocator() async {


  await locator.unregister<ApiService>();
 
  await locator.unregister<DioConfig>();

}

please have a look if need some info let me know. 

the log printing the correct baseoption but when i call the api it somehow uses the old baseoption and old instance.

**Comment by razasubtain** [comment]
> How should get_it know which object it should unregister if you don't pass the type?
> 
> I'm general for your use case of login/logout I recommend using get_it scopes for that. Check the Readme.
> Am 1. Feb. 2025, 00:44 +0100 schrieb razasubtain ***@***.***>:
> […](#)

i have passed the type somehow it is not displayed in the question i share my code again 
void register(BaseOptions dioBaseOptions) {
  p('Base Options===========================> ${dioBaseOptions.baseUrl}');
  locator.registerLazySingleton<DioConfig>(
    () => DioConfig(initialOptions: dioBaseOptions),
  );
  locator.registerLazySingleton<ApiService>(
    () => ApiService(
      dioConfig: locator<DioConfig>(),
    ),
  );
}

unRegisterAllLocator() async {


  await locator.unregister<  **ApiService**     >();
 
  await locator.unregister<  **DioConfig**     >();

}
just adding the quotes for question purpose show how the type is getting removed when i post the question but i am not using quotes in real. 

please have a look if need some info let me know. 
the log printing the correct baseoption but when i call the api it somehow uses the old baseoption and old instance.

**Comment by escamoteur** [comment]
Honestly, no idea why this shouldn't work. If you can create a small repro project that shows this behavior I am happy to look into it.
As this is absolutely base functionality of get_it it's highly unlikely that this is a bug of the package
Am 1. Feb. 2025, 01:18 +0100 schrieb razasubtain ***@***.***>:

**Comment by razasubtain** [comment]
This is actually my company project so can't share unfortunately but i used the pushNewScope and it did not worked.
locator(BaseOptions dioBaseOptions){
if (!locator.hasScope('sessionScope')) {
    locator.pushNewScope(
      scopeName: 'sessionScope',
      dispose: () {
        p('Session Scope Disposed');
      },
    );
  }

  locator.registerLazySingleton<DioConfig>(
    () => DioConfig(options: dioBaseOptions),
  );

  locator.registerLazySingleton<ApiService>(
    () => ApiService(
      dioConfig: locator<DioConfig>( ),
    ),
  );}
////
unRegisterAllLocator() async {
  if (locator.hasScope('sessionScope')) {
    await locator.popScope(); // Clears all scoped dependencies
  }


// Below theses are my dio configurations which i pass inside the DioConfig class based on if user is logged in or not.
after logout it uses the old instance even after calling the unregisterAllLocator Method. I don't understand why this is happening. 
///
class AllDioOptions {
  static final FirstDioOptions = BaseOptions(
      validateStatus: (status) {
        return status != null &&
            status >= 200 &&
            status < 400; // Allow redirects
      },
      followRedirects: true,
      baseUrl: AllBaseUrl.cAuthEndPoint,
      connectTimeout: const Duration(seconds: 100),
      receiveTimeout: const Duration(seconds: 100),
      headers: DifferentHeaders.getCHeader());

  static final SecondDioOptions = BaseOptions(
      validateStatus: (status) {
        return status != null &&
            status >= 200 &&
            status < 400; // Allow redirects
      },
      followRedirects: true,
      baseUrl: AllBaseUrl.tBaseUrl,
      connectTimeout: const Duration(seconds: 100),
      receiveTimeout: const Duration(seconds: 100),
      headers: DifferentHeaders.getTHeader());
}

**Comment by razasubtain** [comment]
Can you please tell me one thing, if there are multiple threads running can it lead to this issue where even
 after unregistering the instances i am still getting the old instance ?

**Comment by escamoteur** [comment]
As Dart is single threaded the only possible situation that I could imagine is during some async call.

You could check directly after unregistering with 'isRegistered' if the object is still inside get_it.
Am 4. Feb. 2025, 13:14 +0100 schrieb razasubtain ***@***.***>:

**Comment by razasubtain** [comment]
First of all thanks for you response. I resolved the issue finally. Actually i was calling the multiple api's at a time and after using that approached which you mentioned to check directly if the object is registered or not after unregistering it
if (locator.isRegistered<ApiService>()) {
    p('Api Service Still registered==========');
  }

i realized the print statement was being called even after unregistering the locator i am not sure why this was happening any idea???  so i did this 
  await unregisterService<ApiService>();
Future<void> unregisterService<T extends Object>() async {
  if (locator.isRegistered<T>()) {
    p('Unregistering ${T.toString()}...');
    await locator.unregister<T>();
  } else {
    p('${T.toString()} is not registered.');
  }
}

and explicitly removed the locator from getit . After that i never got the log of "Api service is still registered".

The second change which i had to make was specifically not related to getit but it might be helpful for someone in future.

 dio = Dio(
      BaseOptions(
        validateStatus: (status) => status != null && status >= 200 && status < 400,
        followRedirects: true,
        baseUrl: AllBaseUrl.cXAuthEndPoint,
        connectTimeout: const Duration(seconds: 100),
        receiveTimeout: const Duration(seconds: 100),
        headers: {
          'accept': 'application/json',
          'authorization': 'Bearer $_token',
          'content-type': 'application/json',
        },
      ),
    );
i was passing the token as a string variable so in all cases after logging out it was keeping the old token until i restart the app so i changed the variable with getToken() method to return the latest token every time . Small mistake but it was over looked and took so much time to notice but thankfully the issue got resolved. Thanks Again!!!!

**Comment by escamoteur** [comment]
No idea why you again lost the generic types in your code examples. So your code doesn't make any sense. I think already in your previous post too.
I really would like to know what is going on there.
Am 5. Feb. 2025, 04:35 +0100 schrieb razasubtain ***@***.***>:

**Comment by razasubtain** [comment]
i am also confused why my type is getting removed when i save the comment. I just added the qoutes around the type for avoiding this behaviour only not a part of my actual flutter code .

**Comment by escamoteur** [comment]
Ok, so you were storing the token not in an object inside get_it but somewhere else?

The only thing that I can imagine is, did you await the unregisterAll function that you used in the beginning? If not then that is the problem
Am 5. Feb. 2025, 05:12 +0100 schrieb razasubtain ***@***.***>:

**Comment by razasubtain** [comment]
No actually i was awaiting the unregisterAll method. The problem which i couldn't completely understand the reason was i called the unregistered method only once on logout but i was getting the multiple print statements of the below print statement maybe because i was calling the multiple api's at same time so there was some kind of race problem. 
if (locator.isRegistered<"ApiService">())
 {
 p('Api Service Still registered==========');

 }

so instead of unregistering them directly i put a condition to first check if it is register then unregister it so if unregisterAll method is called multiple times in a response of multiple api executions it verifies every time if the instance is register then unregister it. Also i was using some static values which were might be causing the Race problem so i converted them into singleton. For now my code is working fine.
