### ISSUE TITLE
Not able to change values in registered singleton or user error?

### ISSUE THREAD

**Issue by enzotar** [fluttercommunity/get_it#116]
```
// get it registration in one file
//
sl.registerSingleton<MemoryDatabase>(MemoryDatabase());
sl.registerSingleton<Commands>(Commands());


// in a second file
//
class MemoryDatabase{
   List cache = [];
}

// in a third file, factory singleton with RxCommands
//
class Commands{
   final RxCommand<void, List> doSomething;

   Commands._({this.doSomething});

   factory Commands(){
      List cache = sl<MemoryDatabase>().cache;

      final _doSomething = RxCommand.createSyncNoParam<List>(){
         // some work is done with an output of newCache       

         // this does not work, but I don't get why <<<<<<--------------------------- QUESTION IS HERE
         cache = newCache;
         // and this works
         sl<MemoryDatabase>().cache = newCache;
        
         return [newCache]
      };

      return Commands._(
         doSomething: _doSomething,
      );
   }

}


```

**Comment by escamoteur** [comment]
That's kinda weird. you mean that if you do `cache=newCache` and you access it later over `sl<MemoryDatabase>().cache` the data isn't changed?
could you send me a minimal repro project? What you describe should not be possible.

**Comment by enzotar** [comment]
Precisely - the data isn't changed.

Here you go
https://github.com/enzotar/GetItExample.git

Press the floating button multiple times once loaded. Let me know if the example is not clear. Thanks

**Comment by escamoteur** [comment]
I was a bit perplexed too here for a moment but it behaves as it should. 
The moment you assign ´newCache` to `cache you replace the content of the variable `cache` that pointed to the the list inside the MemoryDatabase to a completely different variable.

you can try this here:

```dart
class Container{
  List list = [1,2,3];
}


void main() {
  final container = Container();
  
  var cache = container.list;
  
  cache = [5,6,7];
  
 
  print(container.list);
  
}
```

the surprising thing is , if you don't assign but do an addall on cache it works as you thought.

**Comment by enzotar** [comment]
Shouldn't be the reverse? as in  `var container.list = cache`
Then the container.list is actually changed.

```
class Container{
  List list = [1,2,3];
}


void main() {
  final container = Container();
  
  
  List cache = [5,6,7];
  container.list = cache;

 
  print(container.list);
  
  
}
```

**Comment by enzotar** [comment]
Sorry, I didn't understand your last comment regarding code rebuilds.

Maybe I am confusing stuff, but why would:
`container.list = cache` work and container.list changes but
`sl<Container>.list = cache` does't work and container.list is not changed.

**Comment by escamoteur** [comment]
sorry I didn't mean real rebuilds but that my example simulates what you asked.

```Dart

   factory Commands(){
      List cache = sl<MemoryDatabase>().cache;

      final _doSomething = RxCommand.createSyncNoParam<List>(){
         // some work is done with an output of newCache       

         // this does not work, but I don't get why <<<<<<--------------------------- QUESTION IS HERE
         cache = newCache; // this can't work see my example
         // and this works
         sl<MemoryDatabase>().cache = newCache; /// this here works it's like doing `container.list=cache`
        
         return [newCache]
      };
```

**Comment by enzotar** [comment]
Looking at it again, I actually think it is not the same as the example. It is the reverse as below.  Am I getting it wrong?
```
class Container{
  List list = [1,2,3];
}


void main() {
  final container = Container();
  
  List cache = [5,6,7];
  container.list = cache;

  print(container.list);
  
  
}
```

**Comment by escamoteur** [comment]
Nope :-)

` List cache = sl<MemoryDatabase>().cache;` is different to `container=container`
and you asked why `  cache = newCache;` doesn't work.

**Comment by enzotar** [comment]
Ah I think I'm getting it. This is some Dart trickery! and user error  :-)  Make me wish for pointers.

**Comment by escamoteur** [comment]
yep! I too think pointers would be clearer here. If you use addAll instead of the assignment it works because then `cache` still holds the instance inside container. But the assignment completely assigns a new instance to `cache`.
But I too had to think twice and try it :-)
