### ISSUE TITLE
isRegistered always returns false

### ISSUE THREAD

**Issue by eelishiram** [fluttercommunity/get_it#117]
Hi. I am using **get_it** version **5.0.1**  and I have a snippet like this
```
final locator = GetIt.instance;

check() {
  Test a = Test();
  locator.registerFactory<Test>(() => a);
  Test b  = locator.get<Test>();
  print(identical(a, b)); // true
  print(locator.isRegistered<Test>(instance: b)); // false
}
```
As you can see, the identical returns true for instances a and b. However, when I try to check whether the instance b is registered, it returns false.  If I modify the last print statement as below

`  print(locator.isRegistered<Test>()); // true`

then it does return true. But since I want to check if exact instance is registered or not, this does not suit my needs at all. Is there something that I am missing regarding to the usecase of instance field?

**Comment by escamoteur** [comment]
don't pass the instance that does only work for singletons, not for factories

**Comment by escamoteur** [comment]
did this solve your problem? I will close this for now. if you still have a problem please open a new issue
