### ISSUE TITLE
No register type error

### ISSUE THREAD

**Issue by oscarshaitan** [fluttercommunity/get_it#118]
I get this error 
```
No type XUseCase is registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
did you forget to register it?)
```
get it dont find the `XUsCase` but is already registered 

`sl.registerLazySingleton<XUseCase >(() => XUseCase (sl()));`

**Comment by escamoteur** [comment]
looks good to me, what is the constructor of XUseCase doing? can you show me the code where you get the exception?

**Comment by oscarshaitan** [comment]
```
class XUseCase {
  final XRepository repository;

  XUseCase (this.repository);

  Future<Either<Failure, dynamic>> call(String param1, String param2) async {
    return repository.run(param1, param2);
  }
}
```
is to simple usecase
that use case is needed on a bloc an I call the use case with 
`XUseCase  xUsecase = sl.get<XUseCase >();`

**Comment by oscarshaitan** [comment]
and was working fine I have at least 15 types registered the only thing new is I update to `get_it: ^5.0.1`

**Comment by escamoteur** [comment]
What should this here do `sl()`?

**Comment by oscarshaitan** [comment]
sorry thats my get_it instance :D 
`final sl = GetIt.instance..allowReassignment = true;`

**Comment by escamoteur** [comment]
yeah but you call it while passing to the constructor: 
`sl.registerLazySingleton<XUseCase >(() => XUseCase (sl()));`

**Comment by oscarshaitan** [comment]
this
`sl.registerLazySingleton<XUseCase >(() => XUseCase (sl()));`
in on the setup just like the guide.
in this case that bloc is not provide by the get_it I'm getting the usecase just when I needed not on the constructor

**Comment by escamoteur** [comment]
yeah, so you are expecting that the `sl()` returns you a registered instance of `XRepository` ? could it be that the constructor of `XRepository` tries to access `XUsecase'

**Comment by oscarshaitan** [comment]
no, the repo dont have any instance of sl or the usecase

**Comment by oscarshaitan** [comment]
an yesh Im specting sl return a Xrpository tha tis also registered 
`sl.registerLazySingleton<XRepository >(() => XRepository (sl()));`

**Comment by oscarshaitan** [comment]
also tht repository dependecy is registered too. was working just fine until yesterday that I update to ` get_it: ^5.0.1` also I made a full clean and restaert everything. 
btw is happening only on ios

**Comment by escamoteur** [comment]
I recommeds always use sl<Type>() which is better to read.

Now, that seems pretty weird that it only happens on iOS because get_it doesn't use any system functions.

could it be that it's a timing issue? that somehow on iOS a part of code gets executed that tries to access XUsecase before it it registered?
Did you check in the stack trace when the exception happens where the sl<XUsecase>() is called?

**Comment by oscarshaitan** [comment]
I dont think is the timing cuz all those register are happening before the runApp() call  so is weird indeed and more wierd that os happening only on ios

```
import 'injection_container.dart' as di;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  di.init();

  runApp(MyApp());
}
```

**Comment by escamoteur** [comment]
would you mind joining me in a zoom call that I can look at your project?
That is honestly too weird.

**Comment by oscarshaitan** [comment]
sure!

**Comment by escamoteur** [comment]
https://us04web.zoom.us/j/77933595721?pwd=d2liOGphejErY0xyMWk1cFVkMUNvZz09

**Comment by oscarshaitan** [comment]
@escamoteur I clean flutter reset/invalidate cache and now is working Thanks!
