### ISSUE TITLE
You tried to access an instance of UserStore that was not ready yet

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [fluttercommunity/get_it#119]
My app started giving this error, I would like to know the possible causes because it was working just perfect and out of nothing, this started, sorry if its documented, I tried searching and reading but could find something about

**Comment by escamoteur** [comment]
In case you upgraded to V5 there has been a change. Are you using named registrations? 
Also please do a flutter clean and try again

**Comment by diego-lipinski-de-castro** [comment]
Im using get_it: ^4.0.4 still, tried flutter clean and problem persists
![image](https://user-images.githubusercontent.com/29608698/96463666-56777700-11fd-11eb-9d6a-4c1c9116ccc5.png)

This is the the file where I bootstrap the store, when I push to the /Pages route, is when I access the store, and then, BOOM

**Comment by diego-lipinski-de-castro** [comment]
I tried putting await getIt.allReady(); before calling the next route, it never goes, its like it never gets ready

**Comment by diego-lipinski-de-castro** [comment]
Oh, i think i just found the problem, the store if throwing an error on the initialization, thats why it does not proceed

**Comment by diego-lipinski-de-castro** [comment]
That was the problem, sorry for the useless issues.
