### ISSUE TITLE
.get() does not return instance when registered with .registerSingletonAsync 

### ISSUE THREAD

**Issue by DirtyNative** [fluttercommunity/get_it#121]
I made a new project with a model class:

```
class Model {
  int i;

  Future<Model> init() async {
    await Future.delayed(Duration(seconds: 1));
    i = 10;
    return this;
  }
}
```

and a service locator file

```
import 'package:get_it/get_it.dart';

import 'model.dart';

void setup() {
  var getIt = GetIt.instance;

  getIt.registerSingletonAsync<Model>(() async {
    var model = Model();
    model.init();

    return model;
  }, signalsReady: true);
}
```

The setup method is called right before `runApp(MyApp());`

When setting `singnalsReady` to `true` I get an erorr:

`
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#02fe8):
You tried to access an instance of Model that was not ready yet
'package:get_it/get_it_impl.dart':
Failed assertion: line 322 pos 14: 'instanceFactory.isReady'
`

And when I set `singnalsReady` to `false`, GetIt returns an instance though the `init()` function did not finish, so the `int` inside is still `null`. As I have read in the docmentation, GetIt should run the async function first, and then return the instance from the `get()` method. Is this a bug?

**Comment by escamoteur** [comment]
you have to either await the `model.init` call or do it like this:

```Dart
  getIt.registerSingletonAsync<Model>(() async {
    var model = Model();
    return model.init();
  }, signalsReady: false);
```

so that you return the future that you get from init. Only set `signalsReady` to true if you want to signal it manually

**Comment by DirtyNative** [comment]
Sorry my fault, had forgot to write down await again after a lot of testing.. But even when I await the init() method, I still get the same error

**Comment by escamoteur** [comment]
on which version of GetIt are you?

**Comment by escamoteur** [comment]
and did you set `signalReady` to false?

**Comment by DirtyNative** [comment]
I am working on the latest version of get_it (5.0.1) and also on the latest stable version of flutter itself (1.22.2). Yes, I tried it with true and false, both throw this exception.. I attached the project itself, maybe this could help solving this issue
[test_proj.zip](https://github.com/fluttercommunity/get_it/files/5423688/test_proj.zip)

**Comment by escamoteur** [comment]
Thats great will have a look

**Comment by escamoteur** [comment]
Hi,

it can't work the way you do it :-)

if you register any Singleton async, you have to check if the instance is ready before you access it the first time.
you can ensure that all instances are ready by using calling ´allReady()´ on your GetIt instance which returns a future that completes when all instances are ready.
Best way to use this is in combination with a FutureBuilder, that can then display a waiting Spinner until the Future has completed.

**Comment by DirtyNative** [comment]
I see, this was my mistake :'D So I implemented a splash screen which runs `allReady()` and after all is loaded, it shows my MainView. Works perfect, thanks!
