### ISSUE TITLE
Get.to() on FlutterFire onResume handler not working on iOS.

### ISSUE THREAD

**Issue by FactorMouk** [fluttercommunity/get_it#123]
I have this on FlutterFire onResume handler:

```
onResume: (Map<String, dynamic> message) async {
     if (!global.onChatScreen) {
         Get.to(ChatView(
                chatID: int.parse(message['data']['conversation_id'])));
     }
},
```

This works on Android (when I click on the notification, I'm redirected to the Chat Preview page), but not on iOS!
I checked and the code goes into "if".

**Comment by evandrmb** [comment]
Are you sure this issue belongs to Get_it? To me it seems you're using Get navigation (this package: https://pub.dev/packages/get)

**Comment by escamoteur** [comment]
Thats what I just wanted to say :-)
