### ISSUE TITLE
Object/factory with with name __environments__ and  type Set<String> is already registered inside GetIt. 

### ISSUE THREAD

**Issue by Pawelo93** [fluttercommunity/get_it#124]
Hello

Im using two configuration of getIt, one in main project and one in other module. When both configurations meet, there is error:
`Object/factory with with name __environments__ and  type Set<String> is already registered inside GetIt. `

It was working before on older version.

**Comment by escamoteur** [comment]
What do you mean with two configurations?
can you show me a bit more of your code?

**Comment by Pawelo93** [comment]
configureMainInjection(mainGetIt, Environment.dev);
  configureModuleInjection(moduleGetIt, Environment.dev);

im trying to join two separate DI, in mainGetIt i need one class from module with all it dependencies

**Comment by Pawelo93** [comment]
Sorry I was missing
GetIt.asNewInstance()

**Comment by ReniDelonzek** [comment]
I have same problem. My code 

```
    if (!GetIt.I.isRegistered(instance: HiveService())) {
      GetIt.I.registerSingleton<HiveService>(HiveService());
    }
```

isRegistered always returns false, and the second time I run this code, registerSingleton fails saying that this class is already registered

My get_it version: 5.0.1

**Comment by escamoteur** [comment]
@ReniDelonzek No, you have another problem :-)

What you are doing here

```Dart
isRegistered(instance: HiveService()))
``` 
is that you create a completely new `HiverService` object and you ask GetIt if this is already registered, which never can be the case to this if always evaluate to true.
Using the `instance` parameter is when you want to know if an object you have is registered. 
What you want todo is:

```Dart
GetIt.I.isRegistered<HiveService>();
```
But I also would question why do you check this at all? Maybe there is a better approach.

Cheers

**Comment by ReniDelonzek** [comment]
> `GetIt.I.isRegistered<HiveService>();`

Oh, it is work! 

Sorry, my first use this lib, Alias, congratulations on the excellent work done on it!

My use case is as follows:
I have a function that is triggered by Firebase's onBackgroundMessage, so it runs in a new isolate.

The code that I run next depends on this service being registered correctly in GetIT. And as it is a new isolate, I have to register inside it

In this situation I have no way of knowing when this code is running for the first time (which would be the only time I need to register), so this conditional to know if it is already registered or not.

If you have any suggestions for a better approach that I can take, please, I would greatly appreciate receiving. Thank you!

**Comment by escamoteur** [comment]
Ah, understood cool Am 28.10.2020 15:42 schrieb Reni Delonzek <notifications@github.com>:

GetIt.I.isRegistered<HiveService>();

Oh, it is work!
Sorry, my first use this lib, Alias, congratulations on the excellent work done on it!
My use case is as follows:
I have a function that is triggered by Firebase's onBackgroundMessage, so it runs in a new isolate.
The code that I run next depends on this service being registered correctly in GetIT. And as it is a new isolate, I have to register inside it
In this situation I have no way of knowing when this code is running for the first time (which would be the only time I need to register), so this conditional to know if it is already registered or not.
If you have any suggestions for a better approach that I can take, please, I would greatly appreciate receiving. Thank you!
