### ISSUE TITLE
Can we register different objects of the same type as LazySingleton ? 

### ISSUE THREAD

**Issue by chinkysight** [fluttercommunity/get_it#125]
I want to do something like this :
 
```dart
final GetIt locator = GetIt.instance;

void setupLocator() {
  locator.registerLazySingleton<Section>(() => Section(title: "HomeView"));
  locator.registerLazySingleton<Section>(() => Section(title: "ProfileView"));
}
```

**Comment by escamoteur** [comment]
Yep, add an instanceName when registering. you also have to use it then when you access it again.

also check the scope feature. Maybe this also could help you

**Comment by chinkysight** [comment]
> Yep, add an instanceName when registering. you also have to use it then when you access it again.
> 
> also check the scope feature. Maybe this also could help you

Can please show me am example ?

**Comment by isaacadariku** [comment]
First of all... What are you trying to achieve with this?

**Comment by chinkysight** [comment]
I have two different ChopperClients, which I want to access using Get_It. The advantage is that I can dispose the client withing the registerLazySingleton method.

**Comment by escamoteur** [comment]
@chinkysight what is your problem after reading on named registration in the readme?

**Comment by chinkysight** [comment]
> @chinkysight what is your problem after reading on named registration in the readme?

You means registerFactoryParam ? I can't find a dispose method 😭😭

**Comment by chinkysight** [comment]
> Yep, add an instanceName when registering. you also have to use it then when you access it again.
> 
> also check the scope feature. Maybe this also could help you

I don't get add instanceName when registering, can you show me an example ???

**Comment by escamoteur** [comment]
no, named registration. every register call has an optional 'instanceName' parameter. also ´get´ has the same optional parameter.
if you assign a name when registering you have to use it again when you access the object

```Dart
void setupLocator() {
  locator.registerLazySingleton<Section>(() => Section(title: "HomeView"),instanceName:'home');
  locator.registerLazySingleton<Section>(() => Section(title: "ProfileView"), instanceName;'profile');
}
```

and when you want to access it:


```Dart
final view = locator<Section>(instanceName:'home');
````

**Comment by chinkysight** [comment]
> no, named registration. every register call has an optional 'instanceName' parameter. also ´get´ has the same optional parameter.
> if you assign a name when registering you have to use it again when you access the object
> 
> ```Dart
> void setupLocator() {
>   locator.registerLazySingleton<Section>(() => Section(title: "HomeView"),instanceName:'home');
>   locator.registerLazySingleton<Section>(() => Section(title: "ProfileView"), instanceName;'profile');
> }
> ```
> 
> and when you want to access it:
> 
> 
> ```Dart
> final view = locator<Section>(instanceName:'home');
> ````
> 
> 

Ohh so in this way I can register different objects of same type right ?

**Comment by escamoteur** [comment]
Yep just give them different names but take that you use the same names when you access the singleton

**Comment by chinkysight** [comment]
> Yep just give them different names but take that you use the same names when you access the singleton 

Thank you so much for your response ☺️
