### ISSUE TITLE
Register lazy singleton that depends on async lazy singleton

### ISSUE THREAD

**Issue by haashem** [fluttercommunity/get_it#126]
OK, the title maybe is confusing but here it is the dependency:

UserPreferences -->  IPreferences __> Preferences --> SharedPreferences

I have setup this in main function:

``` dart
get.registerLazySingletonAsync<SharedPreferences>(
      () async => SharedPreferences.getInstance());
  get.registerLazySingleton<IPreferences>(
      () => Preferences(get<SharedPreferences>()));
  get.registerLazySingleton<UserPreferences>(
      () => UserPreferences(get<IPreferences>()));
```

But when when I try to access `getIt<UserPreferences>()` `get_it` complains I tried to access an instance of`SharedPreferences` that was not easy yet.

how can I solve this async dependency?

**Comment by escamoteur** [comment]
use registerSingletonWithDependencies for the two latter ones

**Comment by haashem** [comment]
Thanks for hint, but I didn't work.
There are two ways:
1. Register async dependency `SharedPreferences` synchronously so the whole dependency chain is synchronous. 
``` dart
final sharedPreferences = await SharedPreferences.getInstance();
 get.registerSingleton<SharedPreferences>(sharedPreferences);
.
.
.
```
2. use `getAsync` method instead. because `SharedPreferences` is loaded asynchronously and I was trying to access it synchronously. cons is I have to know inside details, UserPreferences has a async dependency. which is not right. 

should `get_it` auto wait for its async dependency when its requested synchronously? do I have misunderstanding?

I read the read me page, but I couldn't understand the use case of `dependsOn` well! 
my goal is to resolve dependencies lazily. what's the right approach?

**Comment by escamoteur** [comment]
Great that this worked for you. 

1. returning the instance would be an idea but would be a breaking change. Also most of the time I just use allReady() at some place at startup, and I don't check after that with `isReady`. 
2. you can save some key strokes by omitting the `get` as GetIt is a callable class, like
```Dart
 final userPreferences = getIt<UserPreferences>();
```

**Comment by haashem** [comment]
👍
I took me a hours to understand and debug the issue; I got fooled that I'm accessing synchronous instance. I appreciate if you can update the read me especially in `dependsOn` section. provide a hint: if you are trying to get a instance depends on async instance you MUST use `allReady`with a `FutureBuilder` or `await isReady<T>()`to guarantee dependency is ready before accessing it.

Thanks for supporting this great library 😉

**Comment by escamoteur** [comment]
Ok will make this more clear!
