### ISSUE TITLE
Singleton not being instantiated

### ISSUE THREAD

**Issue by andreddie81** [fluttercommunity/get_it#127]
I've got a very simple flutter app, where, at the very beginning I have:

**---- main.dart ----**
```
void main() {
  initializeDependenciesInjection();
  runApp(MyApp());
}
```

**--- dependencies.dart**

```
import 'package:get_it/get_it.dart';
import 'package:sample_app/network/main_api.dart';

GetIt getIt = GetIt.instance;

void initializeDependenciesInjection() {
  getIt.registerSingleton<MainApi>(MainApi(), signalsReady: true); 
}
```

**----- MyApp.dart ------**

```
MainApi api;

@override
  void initState() {

    print("INIT IS CALLED");

    getIt.isReady<MainApi>().then((_) {
      print("API HAS BEEN INITIALIZED");
      api = getIt<MainApi>();
    });
    super.initState();
  }
```

And when I try to use `api` on any other part of the class **I get a Null exception**, even inside a FutureBuildwe where I am using as `future: getIt.allReady(),`

The message **API HAS BEEN INITIALIZED** is never printed.

what am I doing wrong here?? tried to follow the example as much as I can.

**Comment by escamoteur** [comment]
Hi,

I'm not fully sure. Some clarificaions:

1.: using isReady, allReady only makes sense if you have some async initialization in the objects that you register in get_it.
2. if you set `signalReady=true` getIt expects you to call `signalReady` when your object is ready.

if you could show me a bit more code of your MainMapi constructor it might help me to help you further.

**Comment by andreddie81** [comment]
Hi thanks for you fast response,

I do not really have any async initializations in my object, maybe there I am doing something wrong.

Well the MainApi is very very basic at the moment, not sure if that will help but, here it is:

```
import 'package:http/http.dart' as http;

class MainApi {

  final _hostAddress = "xxxxxxxxxxxxxxx";

  Future<http.Response> getAllUsers() async {
    return await http.get(
      '$_hostAddress/getAllUsers', headers: <String, String>{
        'Content-Type': 'application/json; charset=UTF-8'
      },
    );
  }
```
}

**Comment by escamoteur** [comment]
In that case you don't have to use isReady or allReady at all because Dart is singel threaded.
Just don't pass `signalReady` you can directly access MainApi after the registration.
If your object needs some async work before you can use it like reading from shared_preferences you can come back to this here.

**Comment by andreddie81** [comment]
Thank you so much, I will try it!

**Comment by andreddie81** [comment]
It works, you were right, no need for `signalReady` at all. Thanks again!
