### ISSUE TITLE
Issue enabling multiple instances

### ISSUE THREAD

**Issue by chrisoftech** [fluttercommunity/get_it#129]
Am currently facing an issue with enabling multiple instances via `GetIt.allowMultipleInstances=true;`.
Enabling this results to error-logs on console.

Installed package version is `get_it: ^5.0.1`

How can i resolve this?

Thanks for your assistance

**Comment by escamoteur** [comment]
Oh, `GetIt.allowMultipleInstances=true;` was removed in the past. I forgot to delete it in the readme.

**Comment by escamoteur** [comment]
Why do you need multiple instances? Maybe I can show you a better approach

**Comment by chrisoftech** [comment]
Thanks for the quick reply.

A package i developed and a project am working on utilizes `get_it` for DI. With `get_it` instantiated as singleton, my current project, tends to use the already existing instance of `get_it` (from package).

With previous version of `get_it`, instantiating `get_it` asNewInstance()  resolves this issue.

Is there a work around i could apply?

**Comment by escamoteur** [comment]
Why is it a problem if it uses the same?
Otherwise `asNewInstance` is still the way to go

**Comment by chrisoftech** [comment]
Later resolved this. Seems to be an issue resulted from injection as `get_it` is a singleton.
In my case, protected api calls requires a `HeaderInterceptor` to be injected (to provide `Authorization` headers and parameters) while authentication api calls does not require a `HeaderInterceptor` but in this case, `dio` package still retains the injected `HeaderInterceptor` (and still checks for credentials which have been deleted on signout) as it was instantiated as a `lazy-singleton` (could have registered it as a `factory`).

With this, my solution was to pass a header key-value to indicate whether a call requires Authorization credentials or not.

Thanks for your assistance.
