### ISSUE TITLE
Invalid argument(s): Object/factory with  type CellarService is already registered inside GetIt.

### ISSUE THREAD

**Issue by redsuperbat** [fluttercommunity/get_it#130]
Here is the code for registering my singletons, wine-service depends on cellar-service and therefore I'm waiting for WineService to be finished before this functions can terminate.

```dart
  static registerSingletonsWithUserDependencies() async {
    if (!_userDepsInitialized) {
      GetIt.I.registerSingletonAsync<CellarService>(
        () async {
          final cellarService = CellarService();
          await cellarService.init();
          return cellarService;
        },
        dispose: (service) => service.dispose(),
      );
      GetIt.I.registerSingletonWithDependencies<WineService>(
        () => WineService(),
        dependsOn: [CellarService],
      );
      await GetIt.I.isReady<WineService>();
      _userDepsInitialized = true;
    }
  }
```

Here is where I'm calling the function:

```dart
  _loadSingletonsDependantOnUser() async {
    print("Setting up user-deps");
    try {
      await DependencyInjection.registerSingletonsWithUserDependencies();
    } catch (e) {
      print(e);
    }
    print("Finished Setting up user deps");
  }
```

The printed error above is: 
`
 Invalid argument(s): Object/factory with  type CellarService is already registered inside GetIt.
`

I don't understand why Get_it tells me that CellarService is already registered and throws an error, I'm not registering the CellarService anywhere else in my code.

**Comment by escamoteur** [comment]
That sounds pretty weird indeed. On the other side get_it is used by so many people and this would be a real fundamental error that I can't imagine how this could happen. could you share the project with me somehow?
Thanks

**Comment by redsuperbat** [comment]
Here is a link to the repo =) Thanks for having a look at the issue
https://github.com/redsuperbat/firebase_wine_cellar

**Comment by escamoteur** [comment]
Hi, I cloned and run the App without any GetIt exception. I only had several 'null reference' exceptions which I fixed by adding some  '?'.
Maybe because the Firestore Database is empty?

**Comment by redsuperbat** [comment]
Hi thanks for looking at this issue! Did you run the app on IOS or android? The app is currently only configured for android. Sorry about that.

If there is any other way I could help let me know! =)

**Comment by escamoteur** [comment]
I ran it on Android. on which Flutter channel are you? I tied it on beta at the moment.
But its really weird, you should get the same null exceptions like me when starting the app. maybe remove the app from your phone, so that you are not logged in and try to run it.

**Comment by redsuperbat** [comment]
I noticed some mistakes in the code. Let me poke around in my codebase a bit more and I'll comment again when I have more findings! Thanks for sticking with me on this! I really appreciate your help. =)

**Comment by escamoteur** [comment]
Otherwise we could make a zoom call on monday so that you can share your screen.
Btw. I wouldn't make the respository public because you have your Firebase config in the repository which was great so that I could directly run the Aoo but might be dangerous if others get to ti

**Comment by redsuperbat** [comment]
Alright,  I'll make it private again, thanks for letting me know. Firebase is still a bit new to me! If you need the updated code again I will add you as a collab! 👍

**Comment by escamoteur** [comment]
could you fix your problem?

**Comment by redsuperbat** [comment]
Yes thanks for your help. Faults in my code made get_it throw this error. Closing because the issue is resolved
