### ISSUE TITLE
Unable to unregister a factory

### ISSUE THREAD

**Issue by naamapps** [fluttercommunity/get_it#131]
Hey,
In the documentation it says: 
> If you need to you can also unregister your registered singletons and factories and pass a optional disposingFunction for clean-up.

However, when calling unregister with a factory instance, I get this error:

> The following StateError was thrown while finalizing the widget tree:
> Bad state: This instance of the type "SomeFactory" is not available in GetIt If you have registered
> it as LazySingleton, are you sure you have used it at least once?

I am trying to unregister the factory to dispose some variables when exiting a page.
I am calling it in the dispose function.

```
  @override
  void dispose() {;
    locator.unregister(
      instance: SomeFactory,
      disposingFunction: SomeFactory.dispose,
    );
    super.dispose();
  }
```
Thanks for your help

**Comment by escamoteur** [comment]
As a Factory creates a new instance on every call you can't use the instance to unregister.
You have to unregister it with the same Type and (name if you used one) as when you registered.
Maybe have also a look at the new Scope functions in V5,perhaps they can make your live easier
