### ISSUE TITLE
Null-safety version of library

### ISSUE THREAD

**Issue by ovestoerholt** [fluttercommunity/get_it#132]
Null-safety is buzzing in articles about Dart and Flutter these days so I tried to use it on a side-project.
After changing to Flutter beta channel and having completed all the recommended changes I find that most libraries in use are (as expected) not null-safe ready.
Are there any plans to provide a null-safety version of get_it?

Thanks, Ove

**Comment by escamoteur** [comment]
I'm actually on it. turned out the get_it is a tough onw for the migration tool. The Dart team was happy to have it as a test case.

**Comment by escamoteur** [comment]
Here is a first version! https://pub.dev/packages/get_it/versions/6.0.0-nullsafety.1

**Comment by ovestoerholt** [comment]
Fantastic! Will give it a go. Thanks!
