### ISSUE TITLE
How to Implement DI get_it with other package in a project

### ISSUE THREAD

**Issue by wisnuwiry** [fluttercommunity/get_it#133]
I have a study case, I want to make an app with a modular project with the package, in the item module. But I don't know about Implementing Dependency Injection in the module.

Thanks..

**Comment by escamoteur** [comment]
if you reference get_it in all your packages they will share the same instance as default.

**Comment by wisnuwiry** [comment]
Are there samples that I can study? @escamoteur

**Comment by escamoteur** [comment]
Can you elaborate what is not clear to you?

**Comment by wisnuwiry** [comment]
My Project App Structures:

```md
├── lib
│   ├── ...
│   └── ...dart
│
├── module1
├── module2
```

In my project in each module, for example, in the example, there are `module1` and `module2`, and in each module is a `package`.

In each package contains all the Data, State Management and UI.

I'm confused about where the DI implementation is put?

Do I put it in `lib / .. di.dart`?

Or is the DI (Service Locator) placed in each item module?

I want to apply this in the best practice.

**Comment by escamoteur** [comment]
if your modules are packages, you have two options:

1. register all objects from all modules at a central place in lib\di.dart for instance. this makes dealing with dependencies often the easiest.

2. give each package an init function that will register all types from that packae and you call these init functions at some place in your main project. For this you don't have to do anything special with get_it. After all init functions are called all objects are in the same global get_it instance.

**Comment by wisnuwiry** [comment]
Thanks @escamoteur
