### ISSUE TITLE
Example not working on 2.0.1

### ISSUE THREAD

**Issue by arlucio** [fluttercommunity/get_it#14]
Tried to run the example with version 2.0.0 or 2.0.1 and it did not. It just appears a white screen. Also, this error appears when running the example: 

"Unhandled Exception: 'package:get_it/get_it.dart': Failed assertion: line 33 pos 12: 'allowMultipleInstances': You should prefer to use the `instance()` method to access an instance of GetIt. If you really need more than one GetIt instance please set allowMultipleInstances to true."

Went back to 1.1.0 and changed GetIt.asNewInstance() to GetIt() and now it works normally.

**Comment by escamoteur** [comment]
Thanks for the feedback, I will check it out.
Do you really need more than one instance?

**Comment by arlucio** [comment]
No, I don't. That's the problem, I'm not trying to create another instance, just running the example to use only one and it gives this error.

As there is no more default constructor GetIt.asNewInstance(), as on the example, is the only way now to initialize it right now, I believe.

I added  `GetIt.allowMultipleInstances = true` to main() and it worked right, but I'm still using only one instance.

**Comment by escamoteur** [comment]
No just use GetIt.instance and store that value in a variable.

**Comment by arlucio** [comment]
I know that, I'm saying that (use GetIt.asNewInstance()) only to declare it, only once on the first time, as global, only once trough all app, no other call to create another instance in all app.

Anyways the example don't work you will get what I'm saying.

**Comment by escamoteur** [comment]
Just fixed it. nI shouldn't have used asNewINstance in the sample. Now it just uses `GetIt.instance`
