### ISSUE TITLE
unregister not working 

### ISSUE THREAD

**Issue by saharvx9** [fluttercommunity/get_it#141]
hi guys i already did fork for this issue
https://github.com/saharvx9/get_it/pull/1

Bug: 
```
  _ServiceFactory _findFactoryByInstance(Object instance) {
   //here is the bug x.instance is null!!
    final registeredFactories =
        _allFactories.where((x) => identical(x.registrationType, instance));

    throwIf(
        registeredFactories.isEmpty,
        StateError(
            'This instance of the type ${instance.runtimeType} is not available in GetIt '
            'If you have registered it as LazySingleton, are you sure you have used '
            'it at least once?'));

    throwIfNot(
        registeredFactories.length == 1,
        StateError(
            'One Instance of ${instance.runtimeType} more than once registered in GetIt'));
    return registeredFactories.first;
  }

```
it should be x.registrationType

**Comment by escamoteur** [comment]
Which version is this code from? this here is how this function looks like in the lates version:

´´´Dart
 _ServiceFactory _findFactoryByInstance(Object instance) {
    final registeredFactories =
        _allFactories.where((x) => identical(x.instance, instance));

    throwIf(
        registeredFactories.isEmpty,
        StateError(
            'This instance of the type ${instance.runtimeType} is not available in GetIt '
            'If you have registered it as LazySingleton, are you sure you have used '
            'it at least once?'));

    throwIfNot(
        registeredFactories.length == 1,
        StateError(
            'One Instance of ${instance.runtimeType} more than once registered in GetIt'));
    return registeredFactories.first;
  }
´´´

**Comment by saharvx9** [comment]
> Which version is this code from? this here is how this function looks like in the lates version:
> 
> ´´´Dart
> _ServiceFactory _findFactoryByInstance(Object instance) {
> final registeredFactories =
> _allFactories.where((x) => identical(x.instance, instance));
> 
> ```
> throwIf(
>     registeredFactories.isEmpty,
>     StateError(
>         'This instance of the type ${instance.runtimeType} is not available in GetIt '
>         'If you have registered it as LazySingleton, are you sure you have used '
>         'it at least once?'));
> 
> throwIfNot(
>     registeredFactories.length == 1,
>     StateError(
>         'One Instance of ${instance.runtimeType} more than once registered in GetIt'));
> return registeredFactories.first;
> ```
> 
> }
> ´´´

sorry i already copied the sulotion
the bug is:

```
_ServiceFactory _findFactoryByInstance(Object instance) {
//Here is the bug x.instance is null
final registeredFactories =_allFactories.where((x) => identical(x.instance, instance));

throwIf(
    registeredFactories.isEmpty,
    StateError(
        'This instance of the type ${instance.runtimeType} is not available in GetIt '
        'If you have registered it as LazySingleton, are you sure you have used '
        'it at least once?'));

throwIfNot(
    registeredFactories.length == 1,
    StateError(
        'One Instance of ${instance.runtimeType} more than once registered in GetIt'));
return registeredFactories.first;
}
```

solution:
` final registeredFactories =_allFactories.where((x) => identical(x.registrationType, instance));`

x.instance is null all the time
x.registrationType correct with value

**Comment by escamoteur** [comment]
No, this is correct, can you please show me how you try to use unregister please?

**Comment by saharvx9** [comment]
getIt.unregister(instance: HomeBloc);
this is singleton and i am getting an error:
and i am using it  in my home page

```
 'This instance of the type ${instance.runtimeType} is not available in GetIt '
        'If you have registered it as LazySingleton, are you sure you have used '
        'it at least once?'
```

**Comment by escamoteur** [comment]
is HomeBlock a type or an instance?

**Comment by saharvx9** [comment]
![Screen Shot 2020-12-16 at 16 16 22](https://user-images.githubusercontent.com/35892162/102359911-0b3dd280-3fba-11eb-943f-d8d56b1b2b19.png)
this is a type ,but when i am debugging this function i am getting all instances are null :(

**Comment by escamoteur** [comment]
where is HomeBloc defined

**Comment by escamoteur** [comment]
you can't pass a type there as instance. you have to do it

´´´dart
getIt.unregister<HomeBloc>()
´´´

**Comment by saharvx9** [comment]
![Screen Shot 2020-12-16 at 16 18 38](https://user-images.githubusercontent.com/35892162/102360185-5c4dc680-3fba-11eb-80e3-8acf19902fc8.png)
at the start

**Comment by escamoteur** [comment]
yep, there you define that the LayzSingleton will create an INSTANCE of the type `HomeBlock` which will be stored inside GetIt.
to access it you have to provide the Type as generic parameter.

**Comment by saharvx9** [comment]
i did not understood you because i provided type,but you said at the start i need to provide an instance
so what i need to do lol

**Comment by escamoteur** [comment]
Look, if you have the HomeBlock instance stored in some variable you can pass that as `instance` to unregister it. If you don't you have to use the type to access it as shoen above

**Comment by saharvx9** [comment]
> Look, if you have the HomeBlock instance stored in some variable you can pass that as `instance` to unregister it. If you don't you have to use the type to access it as shoen above

i dont have it as parameter, i am injecting it to my base widget that i created.
where i can use with type without my fixing?
