### ISSUE TITLE
how can i set state in static method? i get an error which is 'instanceFactory != null': Object/factory 

### ISSUE THREAD

**Issue by yakupbaser** [fluttercommunity/get_it#145]
hi to all. i use foreground_service plugin & stacked(state management lib) & get_it  and foreground_service needs a static periodicfunction that i use a static service class in it. But when i use static class with stacked plugin, the app is working but i cant manage the state which in my static class. So how to manage state in static class, how can i use get_it & static class & states together?

my static service class is:
```
 @lazySingleton
class IlanService with ReactiveServiceMixin {
  static IlanService _ilanService;
  factory IlanService() {
    if (_ilanService == null) {
      _ilanService = IlanService._internal();
      return _ilanService;
    } else {
      return _ilanService;
    }
  }
  Ilan _ilan = Ilan();
  Ilan get ilan => _ilan;
  Future<void> updateIlan() async {
  _ilan = await databaseHelper.getIlan(mazagaService.magazaID);
  notifyListeners();
}
```
locator.dart:
```
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'locator.config.dart';
final getIt = GetIt.instance;
@InjectableInit(
  initializerName: r'$initGetIt', // default
  preferRelativeImports: true, // default
  asExtension: false, // default
)
void configureDependencies() => $initGetIt(getIt);
```
main.dart:
```
void main() async{
  configureDependencies();
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}
```
myview.dart which has the periodic function fore foreground_service:
```
.
..
...
import 'package:buybox/app/services/ilan_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_foreground_service_plugin/flutter_foreground_service_plugin.dart';
import 'package:stacked/stacked.dart';
import 'package:buybox/datamodels/ilan_model.dart';
IlanService ilanService = IlanService();
/* if i try final ilanService = getIt<IlanService>(); then i get an error:
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 298 pos 9: 'instanceFactory != null': Object/factory with  type IlanService is not registered inside GetIt.
E/flutter (26306): (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
E/flutter (26306): Did you forget to register it?)
*/
void periodicTaskFun() {
  FlutterForegroundServicePlugin.executeTask(() async {
  ..
  ..
  ...
  await ilanService.updateIlan();
  await FlutterForegroundServicePlugin.refreshForegroundServiceContent(
    notificationContent: NotificationContent(
      iconName: 'ic_launcher',
      titleText: 'Title Text',
      bodyText: '${DateTime.now()}',
      subText: 'subText',
      color: Colors.red,
    ),
  );
});
```
and lastly i added locator.config.dart:
```
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************
import 'package:stacked_services/stacked_services.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'services/fiyat_service.dart';
import 'services/third_party_services_module.dart';
/// adds generated dependencies
/// to the provided [GetIt] instance
GetIt $initGetIt(
  GetIt get, {
  String environment,
  EnvironmentFilter environmentFilter,
}) {
  final gh = GetItHelper(get, environment, environmentFilter);
  final thirdPartyServicesModule = _$ThirdPartyServicesModule();
  gh.lazySingleton<IlanService>(() => IlanService());
  // Eager singletons must be registered in the right order
  gh.singleton<DialogService>(thirdPartyServicesModule.dialogService);
  return get;
}
class _$ThirdPartyServicesModule extends ThirdPartyServicesModule {
  @override
  DialogService get dialogService => DialogService();
}
```
so how can i use final ilanService = getIt<IlanService>(); instead of IlanService ilanService = IlanService();  Bcoz i have to set state in it :( (edited)

**Comment by escamoteur** [comment]
My guess is that you call

```
final ilanService = getIt<IlanService>();
```
before your registration is finished. 
is `final ilanService` a global variable?

**Comment by yakupbaser** [comment]
yes it is global variable

**Comment by escamoteur** [comment]
Yeah there is the problem. Why do you use a global variable here and not access get_it when you need it?

**Comment by yakupbaser** [comment]
bcoz periodicTaskFun need it?

**Comment by escamoteur** [comment]
you can call Getit inside a static function

**Comment by yakupbaser** [comment]
so should i register service class in static function whith getIt?

**Comment by escamoteur** [comment]
Why registering in the static function? just use it in there with `getIt<IlanService>()`

**Comment by yakupbaser** [comment]
i made your said but i get same error:

`void periodicTaskFun() {
  FlutterForegroundServicePlugin.executeTask(() async {
  final staticIlanService = getIt<IlanService>();
  
    
    dbIlanList = await staticIlanService.getIlanListWithoutRender();

    .
    ..
    ...
    await FlutterForegroundServicePlugin.refreshForegroundServiceContent(
      notificationContent: NotificationContent(
        iconName: 'ic_launcher',
        titleText: 'Title Text',
        bodyText: '${DateTime.now()}',
        subText: 'subText',
        color: Colors.red,
      ),
    );
  });`

error is:

`[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 298 pos 9: 'instanceFactory != null': Object/factory with  type DatabaseHelper is not registered inside GetIt.
E/flutter (15573): (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
E/flutter (15573): Did you forget to register it?)
`

**Comment by escamoteur** [comment]
could I clone your project and have a closer look?

**Comment by yakupbaser** [comment]
i created a clear project for this issue. There is a counter text in the form. When i click the Increase State From HomeViewModal its success. But When i click the Start ForeGround Service; it dowsnt set the Text widget and if i use getit i get same error:

`final newExampleServer = getIt\<ExampleService\>();`

**Comment by escamoteur** [comment]
It didn't crash here. can you push the version that crashes?

**Comment by yakupbaser** [comment]
yes it did not crash becoz i use `ExampleService newExampleService = ExampleService();` in periodicTaskFun of home_view.dart.   if you try `final newExampleService = getIt<ExampleService>();` then you can see the crash

**Comment by escamoteur** [comment]
Ok, it has nothing to do with the ststic method, the problem is that your periodic function is called from a different Isolate which has its own global variables, which means there also is a GetIt but it's a different instance than theone you register your objects in.

Do you need to have this running on a different Isolate? would a normal Timer not be enough?

I also doubt that you need that static stuff in your example service. Important is for this plugin that your periodic function is either gloibal or static.

**Comment by yakupbaser** [comment]
periodicTaskFun of foreground service is working when app is closed but timer is not :(

**Comment by escamoteur** [comment]
ah, I see. Then I fear you have to instanciate your Objects there manually. It doesn't look like you can pass over any data to the functionthat is called.

**Comment by yakupbaser** [comment]
even so thanks for your helps :)

**Comment by escamoteur** [comment]
Thanks, spread the word about get_it, check out get_it_mixin and I'm always happy of a nice tweet @thomasburkhartb
