### ISSUE TITLE
Service error handling

### ISSUE THREAD

**Issue by dkja** [fluttercommunity/get_it#148]
Can I handle service initialization error ? I think that getIt.addReady() should relay error from all services (from Futures) to returned Future

**Comment by escamoteur** [comment]
hmm interesting thought, this would requipre to save errors till someone calls `allReady`

**Comment by dkja** [comment]
Future contains error, so I think that return errorful Futures (or only first may be ok too) is enough.

**Comment by escamoteur** [comment]
Wow, that was a tough one, but only because I tackled it from the wrong side first. I also found some quirks that hadn't really bothered anyone so far.
Is included in the next release

**Comment by escamoteur** [comment]
Implemented in V6.1.0
