### ISSUE TITLE
register with dependencies cause allReady future hangs forever once depend on lazy object

### ISSUE THREAD

**Issue by Goxiaoy** [fluttercommunity/get_it#155]
Try following codes:
```
GetIt.I.registerLazySingletonAsync(() async=> A());
GetIt.I.registerSingletonWithDependencies(() => B(),dependsOn: [ A ]);

await GetIt.I.allReady();
```

current future will hang forever

**Comment by Goxiaoy** [comment]
You can not either call ·`await GetIt.I.get<AppConfig>();` before `await GetIt.I.allReady();` because A is not ready
Deadlock happens

**Comment by escamoteur** [comment]
yep, depending on a LazySingletonAsync doesn't work. I actually didn't want to include an async version of the LazySingleton at first.
