### ISSUE TITLE
README: uses "effect" instead of "affect"

### ISSUE THREAD

**Issue by richardhaven** [fluttercommunity/get_it#156]
> GetIt offers different ways how objects are registered that effect the lifetime of this objects.

Might better be

GetIt offers different ways to register objects, and they each affect the objects' lifespan

**Comment by escamoteur** [comment]
Hi, 
interesting. It seems it's something that isn't really easy https://www.merriam-webster.com/words-at-play/affect-vs-effect-usage-difference

I think lifetime is the generally used term for objects, but I might be wrong here.

I will change it with the next release. thanks
Thomas

**Comment by formvoltron** [comment]
English has so many crazy things like this.  Honestly I wouldn't be able to spell without Google.

**Comment by RahemanAli321** [comment]
Hii, I am interested in open source contribution for flutter so do you any  community ?

**Comment by escamoteur** [comment]
@RahemanAli321 how do you mean if I do any community?

**Comment by RahemanAli321** [comment]
Sorry for bad English I wanted to improve my self and I am trying contribute open source project so that why asked

**Comment by escamoteur** [comment]
most package authors are happy about contributions. So if you want to fix a but, or add a feature, open an issue to discuss first, then you can make a PR

**Comment by RahemanAli321** [comment]
pull request is good but how can I prepare myself for GSOC i really want to some one who guide me that s why I need community or helps.
