### ISSUE TITLE
How scopes are meant to work?

### ISSUE THREAD

**Issue by shinayser** [fluttercommunity/get_it#158]
I just put my hands on the library and it is really nice! But I can't find a example of how to work with scopes. The documentation shows no example and in my testes they simply doesn't work like navigators (as mentioned on the readme).

Can someone provide a simple, clean and straightforward piece of code? I am sure this will help others lost as am I.

EDIT: here is my test code:

```dart

final getit = GetIt.asNewInstance();

void main(List<String> arguments) async {
  getit.pushNewScope(scopeName: 'cli1');
  getit.registerSingleton<ClientDatabase>(ClientDatabaseImpl(1));
  printClient(); //Prints Client 1

  getit.pushNewScope(scopeName: 'cli2');
  getit.registerSingleton<ClientDatabase>(ClientDatabaseImpl(2));
  printClient(); //Prints Client 2

  getit.popScope(); //Popping to cli1
  printClient(); //Still prints Client 2, but should be printing Client 1 since I've popped!
}

void printClient() =>
    print(getit.get<ClientDatabase>().getCliente()?.toString());

class Client {
  int id;

  Client(this.id);

  @override
  String toString() => 'Client $id';
}

abstract class ClientDatabase {
  Client getCliente();
}

class ClientDatabaseImpl extends ClientDatabase {
  final int id;

  ClientDatabaseImpl(this.id);

  @override
  Client getCliente() => Client(id);
}
```

**Comment by shinayser** [comment]
Seems that my problem was that popScope() runs async way, so It needs to  `awaited`. After that, the code above will work!
Definetly a simple  sample on the README file will be helpful for future users.

**Comment by escamoteur** [comment]
I agree, that part is a bit tricky. Little tip, often its helpful to take a look into the tests for a feature.
If you want to add a small example to the readme, I'm happy to get a PR ;-)
