### ISSUE TITLE
reset changed to async?

### ISSUE THREAD

**Issue by sowens-csd** [fluttercommunity/get_it#159]
Thanks for the package, it's been a pleasure to work with. This is just a minor documentation issue for users upgrading from previous versions. The change to make reset async (I think that's a change?) broke a number of unit tests because instances were already registered since I wasn't doing an `await` for the method to complete before trying to register again. A note in the README could perhaps help reduce the confusion. 

Another small point that I ran across is that I was setting up test dependencies in the `setupAll` method of my unit test. The dependencies were not then found by get_it in the `setup` method. This used to work and does not work anymore, I'm not sure why.

**Comment by escamoteur** [comment]
Hi, yes that has, changes, sorry if this caused trouble for you.

For the second part I would need to see your test file.

**Comment by sowens-csd** [comment]
Thanks for the quick response. I see what happened for the `setupAll` issue now. I tried to recreate it and the test passed, then I realized it's the same issue with not waiting for the reset. Here's a reproduce that shows the failure and is doing what my code used to do:

```dart
import 'package:get_it/get_it.dart';
import 'package:test/test.dart';

class ToRegister {}

void main() {
  final sl = GetIt.instance;
  ToRegister registered;

  setUpAll(() {
    sl.reset();
    sl.registerSingleton<ToRegister>(ToRegister());
  });

  setUp(() {
    registered = sl<ToRegister>();
  });

  test('Registered is found', () {
    expect(registered, isNotNull);
  });
}
```

And here's the working version:

```dart
import 'package:get_it/get_it.dart';
import 'package:test/test.dart';

class ToRegister {}

void main() {
  final sl = GetIt.instance;
  ToRegister registered;

  setUpAll(() async {
    await sl.reset();
    sl.registerSingleton<ToRegister>(ToRegister());
  });

  setUp(() {
    registered = sl<ToRegister>();
  });

  test('Registered is found', () {
    expect(registered, isNotNull);
  });
}
```

**Comment by escamoteur** [comment]
Ah, good to hear. then I can close this issue.
Btw. do you know that there is a compagnion package to get_it. the get_it_mixin?

**Comment by sowens-csd** [comment]
I did not, I just had a look at get_it_mixin, it look's interesting, thanks for the pointer, and for your work.

**Comment by escamoteur** [comment]
If you really want to go a bit further also check out flutter_command and functional_listener:-)
