### ISSUE TITLE
[ERROR] isReady and dependsOn not working as expected

### ISSUE THREAD

**Issue by TomasWeg** [fluttercommunity/get_it#163]
Hello. I'm using get_it to manage some dependencies on my project.

I have two models: `Storage` which has an async method called `init` which creates folders and so on. Another model called `Worker` relies on `Storage` to get a path to a folder, so, `Storage` MUST load before.
This is my code:
```dart
// Register Storage
GetIt.instance.registerSingletonAsync(() async {
    var storage = Storage();
    await storage.init();
    return storage;
});

// Register worker
GetIt.instance.registerSingletonAsync(() async {
    var worker = Worker();
    await worker.load();
    return worker;
}, dependsOn: [Storage]);
```

I put some debug messages to see what is happening:
```
[LOG] Trying to load Worker...
[LOG] An exception occurred: HiveError: You need to initialize Hive or provide a path to store the box. // This error happens because Storage hasn't loaded and Hive does not know where to store everything.

[LOG] Storage has been loaded.
```

It is not supposed to load Storage first?

**Comment by escamoteur** [comment]
Are you sure you initialize Hive correctly?
this should work. 
Can you show we where you use isReady? too?

**Comment by TomasWeg** [comment]
@escamoteur As I said, Hive cannot be initialized correctly because Storage is not initialized before so it does not know where to initialize Hive

**Comment by escamoteur** [comment]
And Worker initilizes Hive?

**Comment by TomasWeg** [comment]
Storage initializes Hive. Worker open boxes.

**Comment by escamoteur** [comment]
Would it be possible to clone your project so that I can take a closer look? that should definitely work

**Comment by TomasWeg** [comment]
Im sorry, its closed source. But what i posted is all the code where GetIt
is used

**Comment by escamoteur** [comment]
That may be but if you check the async tests of get_it this should work. Best to create a small repro project with just the Storage/Worker class.

**Comment by escamoteur** [comment]
Any updates on this?
