### ISSUE TITLE
Use get_It in an isolate

### ISSUE THREAD

**Issue by slimyjimmy** [fluttercommunity/get_it#165]
Hey there,
thanks for your work on get_it. I'm really enjoying it!
However, I can't seem to get it working in another isolate where I want to access the services I registered.
I tried passing the `GetIt.instance` inside of a map alongside other parameters as message parameter of the `compute()` function. This, however, results in the following error:
> Illegal argument in isolate message : (function types are not supported yet)

Is there any way to use the services registered inside my GetIt instance in another isolate?

**Comment by escamoteur** [comment]
Hi,
unfortuantely Isolates share no data with each other or with the main thread. So you can't share data via GetIt. You can however register your classes a second time inside the Isolate

**Comment by slimyjimmy** [comment]
Hi,
okay, thanks. I'll try that.
