### ISSUE TITLE
Invalid argument(s): Object/factory with  type *** is already registered inside GetIt.

### ISSUE THREAD

**Issue by dmvvilela** [fluttercommunity/get_it#166]
With Flutter 2.0 when i hot reload i get this error message.

What is up with that?

**Comment by escamoteur** [comment]
that really only started with 2.0?
It means that your hot reload called your registration function again.
Where do you call the registration function?

**Comment by dmvvilela** [comment]
Above return MaterialApp().

**Comment by escamoteur** [comment]
don't do it inside a build function. best directly before runApp
