### ISSUE TITLE
Error: A value of type 'LoginRepositoryImpl' can't be assigned to a variable of type 'LoginRepository' in flutter

### ISSUE THREAD

**Issue by mahmoud-haj-ali** [fluttercommunity/get_it#167]
I use get_it package for dependency injection, and this error is new.

**The error:**
```
lib/injection.dart:164:11: Error: A value of type 'LoginRepositoryImpl' can't be assigned to a variable of type 'LoginRepository'.
 - 'LoginRepositoryImpl' is from 'lib/future/login/data/repository/login_repository_impl.dart'.
 - 'LoginRepository' is from 'lib/future/login/domain/repository/login_repository.dart'.
    () => LoginRepositoryImpl(
          ^
```

**Comment by escamoteur** [comment]
Actually I haven't seen that one before, but I need to see more code to help here. Is your source on github?
Are you using get_t directly or via injectable?

**Comment by mahmoud-haj-ali** [comment]
@escamoteur 
This is my issue on stack
https://stackoverflow.com/q/66587079/13005736

**Comment by mahmoud-haj-ali** [comment]
The problem solved by adding the implementation and the abstract class to the same file.
