### ISSUE TITLE
The class 'GetIt' doesn't have a default constructor.

### ISSUE THREAD

**Issue by corporate-cas** [fluttercommunity/get_it#169]
I get the error:  "The class 'GetIt' doesn't have a default constructor." when I try to instantiate the GetIt class.

```
import 'package:get_it/get_it.dart';

GetIt locator = GetIt();

void setUPLocator() {
  //REGISTER SERVICES HERE...
}
```

The class 'GetIt' doesn't have a default constructor.
Try using one of the named constructors defined in 'GetIt'.dartnew_with_undefined_constructor_default

**Comment by escamoteur** [comment]
use the `instance` property instead
