### ISSUE TITLE
ResetLazySingleton is not resetting.

### ISSUE THREAD

**Issue by petermusembi69** [fluttercommunity/get_it#170]
Hello there,
I am implementing a login feature using getIt and cubit. So once the user clicks on the login button the desired behaviour is to reset the lazySingleton Logincubit. This is necessary when the login credentials are wrong. The app should be able to restart the auth process afresh.

I am using `get_it: ^6.0.0`

Here is where I add the resetLazySingleton in the UI in the BlocConsumer

```    return BlocConsumer<LogInCubit, LogInState>(
            listener: (context, state) => state.when(
                  initial: () {},
                  loading: () {},
                  loaded: () {
                    Navigator.pushNamed(
                      context,
                      AppRouter.otpRoute,
                    );
                  },
                  error: (error) {
                    phoneNumberController.clear();
                    passwordController.clear();
                    locator.resetLazySingleton<LogInCubit>();
                  },
                ),
 ```
 and the Login button.
 ```
 @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    return MaterialButton(
      onPressed: () {
        locator<LogInCubit>().logIn(
          phoneNumber: phoneNumberController,
          password: passwordController,
        );
        locator.resetLazySingleton<LogInCubit>();
      },
 ```
 Here is where I register my LazySingleton
 
 ```
GetIt locator = GetIt.instance;

void setUpServiceLocator() {
  // Services
  locator
    ..registerLazySingleton<LogInCubit>(
      () => LogInCubit(
        authService: locator(),
        hiveService: locator(),
      ),
 ```

**Comment by saharvx9** [comment]
There is bug in get_it_impl class
look for function : _findFirstFactoryByInstanceOrNull
then change this from:
```
    final registeredFactories =
         _allFactories.where((x) => identical(x.instance, instance));
```
to :
```
final registeredFactories =
         _allFactories.where((x) => identical(x.registrationType, instance));
```
 registrationType will do the magic

**Comment by escamoteur** [comment]
@saharvx9 That's not correct. That part of the code is absolutely correct.

@petermusembi69 I just looked at the code. How do you know it didn't reset?

**Comment by escamoteur** [comment]
@saharvx9 a bit more explanation. The function you want to change is only called when you pass an instance of an Object which @petermusembi69 doesn't do here. If you needed to make the change that you proposed to get your code working you are using `resetLazySinglteton` wrong. you can't pass a type as instance. if you don't have an isntance, pass the type as with all other methods as generic parameter

**Comment by escamoteur** [comment]
@petermusembi69 just a tip, for situations like that I recommend to check if get_it scopes wouldn't be the better way to go.

**Comment by saharvx9** [comment]
> @saharvx9 That's not correct. That part of the code is absolutely correct.
> 
> @petermusembi69 I just looked at the code. How do you know it didn't reset?

I check dozen of times instance is always null
So this is why its not possible to to reset it with this line, when i change it it worked perfectly

**Comment by escamoteur** [comment]
if instance is null `_findFactoryByInstance` isn't called as you can see

```Dart
 @override
  void resetLazySingleton<T extends Object>({
    Object? instance,
    String? instanceName,
    void Function(T)? disposingFunction,
  }) {
    _ServiceFactory instanceFactory;

    if (instance != null) {
      instanceFactory = _findFactoryByInstance(instance);
    } else {
      instanceFactory = _findFactoryByNameAndType<T>(instanceName);
 ```

**Comment by escamoteur** [comment]
couly you show me the line whare you call `resetLazySingelton`?

**Comment by petermusembi69** [comment]
> @saharvx9 That's not correct. That part of the code is absolutely correct.
> 
> @petermusembi69 I just looked at the code. How do you know it didn't reset?

@saharvx9's approach doesn't help much.

@escamoteur  this is how I know it didn't reset. Here are the cubit logs, thrown when the app is running. I have 4 states(initial, loading, loaded, error).

**1st** try with wrong LogIn credentials.
```
[log] onChange(LogInCubit, Change { currentState: LogInState.initial(), nextState: LogInState.loading() })
[log] onChange(LogInCubit, Change { currentState: LogInState.loading(), nextState: LogInState.error(message: Login Failed!) })
```
**2nd** try with the correct credentials starts off with the error state. This should not be the case if the lazySignleton was reset. It should start with the initial state instead.
```
[log] onChange(LogInCubit, Change { currentState: LogInState.error(message: Login Failed!), nextState: LogInState.loading() })
[log] onChange(LogInCubit, Change { currentState: LogInState.loading(), nextState: LogInState.error(message: Login Failed!) })
```
**3rd** try with the correct credentials
```
[log] onChange(LogInCubit, Change { currentState: LogInState.error(message: Login Failed!), nextState: LogInState.loading() })
[log] onChange(LogInCubit, Change { currentState: LogInState.loading(), nextState: LogInState.error(message: Login Failed!) })
```

**Comment by petermusembi69** [comment]
> couly you show me the line whare you call `resetLazySingelton`?

`locator.resetLazySingleton<LogInCubit>();`

**Comment by escamoteur** [comment]
@petermusembi69 can it be that you have somewhere else a reference to this Cubit so that the garbage collector can't do its job? I'm not familiar with Cubit but AFAIK it used streams, so you will have to call some dispose method on the cubid or not?

**Comment by escamoteur** [comment]
> @escamoteur you metioned something about "pass the type as with all other methods as generic parameter". I think that is what I have done here. If not, kindly explain further.
No, you do it exactly as it should be

**Comment by escamoteur** [comment]
could you solve your problem?

**Comment by petermusembi69** [comment]
@escamoteur Not yet, I will have a look at it, in the course of the week and share any useful findings.

**Comment by petermusembi69** [comment]
> @petermusembi69 can it be that you have somewhere else a reference to this Cubit so that the garbage collector can't do its job? I'm not familiar with Cubit but AFAIK it used streams, so you will have to call some dispose method on the cubid or not?

Cubit is a high-level library and it extends dart streams in the background. Using BlocProvider will automatically dispose the cubit.

**Comment by kmartins** [comment]
@escamoteur I have the same problem here. In the version, `6.0.0` is working normally.

**Comment by kmartins** [comment]
try this small test - Version: 7.0.0

```dart

class Value {
  int number = 0;
}

GetIt.I.registerLazySingleton<Value>(() => Value());
      final value = GetIt.I.get<Value>();
      value.number = 10;
      print(value.number); // 10 - OK
      GetIt.I.resetLazySingleton<Value>(instance: value);
      final value2 = GetIt.I.get<Value>();
      print(value2.number); // 10 instead of 0
```

**Comment by escamoteur** [comment]
oh, sorry you now have to await the reset

**Comment by escamoteur** [comment]
I recommend checking out the changelog

**Comment by kmartins** [comment]
OK, It's working 👍🏾 
Thanks.

**Comment by kmartins** [comment]
However, if I do not have a disposing function in my `resetLazySingleton`, why I must have to use `await`?

I think changing this in the functions `resetLazySingleton` and` unregister`, works better

In  `resetLazySingleton` 
```dart
if (instanceFactory.instance! = null) {
       if (disposingFunction! = null) {
         await disposingFunction.call (instanceFactory.instance as T);
       } else {
         await instanceFactory.dispose ();
       }
     }
```
to:
```dart
if (instanceFactory.instance != null) {
      if (disposingFunction != null) {
        final dispose = disposingFunction.call(instanceFactory.instance as T);
        if (dispose is Future) {
          await dispose;
        }
      } else {
        final dispose = instanceFactory.dispose();
        if (dispose is Future) {
          await dispose;
        }
      }
}
```

**Comment by escamoteur** [comment]
Hmm, that's an interesting take honestly I hadn't thought about that possibility. Would you like to make a PR and add tests to secure that it works as it should?

**Comment by kmartins** [comment]
OK, I created a pull request - https://github.com/fluttercommunity/get_it/pull/185

**Comment by escamoteur** [comment]
Just pushed V7.1.2

@petermusembi69 could you please check if this version still has the problem for you?

**Comment by petermusembi69** [comment]
@escamoteur Version V7.1.2 solved the problem. I was able to get the desired behaviour from the cubit as shown in the logs below. Thank you.
```
[log] onChange(LogInCubit, Change { currentState: LogInState.initial(), nextState: LogInState.loading() })
[log] onChange(LogInCubit, Change { currentState: LogInState.loading(), nextState: LogInState.error(message: The selected phone number is invalid.) })
[log] onChange(LogInCubit, Change { currentState: LogInState.initial(), nextState: LogInState.loading() })
[log] onChange(LogInCubit, Change { currentState: LogInState.loading(), nextState: LogInState.loaded() })
```

**Comment by ddthanh198** [comment]
I await the reset the reset, but does not work
