### ISSUE TITLE
assert: param1 == null || param1.runtimeType == param1Type

### ISSUE THREAD

**Issue by CLD1994** [fluttercommunity/get_it#173]
![image](https://user-images.githubusercontent.com/10044266/114529051-283e9580-9c7c-11eb-9ef5-6281a7cd7631.png)
![image](https://user-images.githubusercontent.com/10044266/114529135-3be9fc00-9c7c-11eb-8932-c765c25a437a.png)

**Comment by CLD1994** [comment]
get_it 6.1.0
@escamoteur

**Comment by escamoteur** [comment]
OH, shit, that too should be commented out. will fix

**Comment by escamoteur** [comment]
Just pushed V6.1.1
