### ISSUE TITLE
Register concrete implementation as multiple abstractions

### ISSUE THREAD

**Issue by daniellampl** [fluttercommunity/get_it#174]
We already have the possibility to register an implementation as an abstraction by passing the registration type with the `as` parameter.

It would also be nice to register the same concrete class `as` MULTIPLE implementation abstractions. This is especially important if we want to separate concrete implementations into multiple abstractions by implementing multiple `interfaces`.

A simple example: There is a class called `Auth` which implements `Login` and `Register`. In the login section, only the `Login` implementation is needed, and therefore the concrete `Auth` class should get accessed via the `Login`abstraction. Same for the register section.

**Comment by escamoteur** [comment]
What changed your mind?
