### ISSUE TITLE
reloading page in web target causes state to vanish

### ISSUE THREAD

**Issue by formvoltron** [fluttercommunity/get_it#175]
yikes.

how can this be fixed?   I'm using the whole stack here:  get_it, get_it_mixin, flutter_command, functional_listener

tweet thread outlines the problem / potential solutions:
https://twitter.com/ThomasBurkhartB/status/1382301168915914755

Couldn't this persisting / rehydrating be automated in some way?  Or does the lack of a cycle callback mean that the problem lies more with the flutter team to develop a general solution for handling page reloads for the flutter web framework?

**Comment by formvoltron** [comment]
some more details from flutter team:
https://docs.google.com/document/d/1KIiq5CdqnSXxQXbZIDy2Ukc-JHFyLak1JR8e2cm3eO4/edit

https://github.com/flutter/flutter/issues/6827

**Comment by escamoteur** [comment]
This still an issue? I mean that is related to get_it?

**Comment by formvoltron** [comment]
I guess this is more of a feature request?

I know nobody is too excited to add features like this because the web
platform seems like more of a hack from Google than a well planned thing.

**Comment by escamoteur** [comment]
My point is that storing and retrieving state outside of the scope of get get it gives you the means to access your objects.

**Comment by formvoltron** [comment]
Ok.  Yes I see you like to keep packages focused on one task.  Good idea.

**Comment by escamoteur** [comment]
you are welcome to publish a package that does the job ans plugs in nicely with get_it :-)

**Comment by formvoltron** [comment]
Well I think I will wait & see what the approach will be for a more popular framework like provider or bloc.  Also, let's wait to see what the Flutter team devises.  

Until then, I'll check out Navigator 2.0 & the DashCast example that was presented in the Flutter & Web prez here:  https://youtu.be/HAstl_NkXl0?t=603

Alternatively, does it make sense to use get_it inside of AngularDart?

**Comment by escamoteur** [comment]
Sure, you can use it anywhere as its pure dart
