### ISSUE TITLE
isRegistered relies on assertion errors for control flow

### ISSUE THREAD

**Issue by buntagonalprism** [fluttercommunity/get_it#178]
Checking for a type being already registered with getIt using a call to `isRegistered` internally relies on catching an assertion error thrown by attempting to access the registered factory / instance. 

This becomes an issue when debugging with break on all exceptions turned on, as unnecessary extra breakpoints are hit when the assertions are failed. This also seems to go against the general principle of not using exceptions for control flow. 

A refactoring of the logic of `isRegistered` and the internal factory finding methods `_findFactoryByInstance` and `_findFactoryByNameOrType` would allow the same interface to be achieved but without the need to use assertion errors to check for registration. 

I am happy to have a go at making these changes and raising a PR

**Comment by escamoteur** [comment]
are you on the latest version? check the null_safety branch which doesn't use exceptions

**Comment by buntagonalprism** [comment]
Ah fantastic thanks, how silly of me. We've got a large app still migrating to null safety, but it looks like this issue is also fixed in the latest non-null safe version `5.0.6`. Closing this issue
