### ISSUE TITLE
Disposable class onDispose typographical error

### ISSUE THREAD

**Issue by OliverRhyme** [fluttercommunity/get_it#184]
The disposable class has a typographical error of  the method `ondDispose()`. I think it should be `onDispose()`.

**Comment by escamoteur** [comment]
Uhm, where is the difference?

**Comment by OliverRhyme** [comment]
> Uhm, where is the difference?

on'd'Dispose()

**Comment by escamoteur** [comment]
oh yeah, I couldn't see it before. You are right

**Comment by escamoteur** [comment]
Fixed with V7.1.0

**Comment by escamoteur** [comment]
Plus another new feature :-)
