### ISSUE TITLE
Type argument 'T' doesn't conform to the bound 'Object' of the type variable 'T' on 'GetIt.get'

### ISSUE THREAD

**Issue by EdvaldoMartins** [fluttercommunity/get_it#187]
My code breaks when I change: 
```
environment:
  sdk: ">=2.7.0-0 <3.0.0"
```

to 
```
environment:
  sdk: ">=2.12.0-0 <3.0.0"
```

I migrated my project to null safety and now I have this error when trying to run

```
Type argument 'T' doesn't conform to the bound 'Object' of the type variable 'T' on 'GetIt.get'.
     - 'Object' is from 'dart:core'.
     - 'GetIt' is from 'package:get_it/get_it.dart'
```

```
import 'package:get_it/get_it.dart';

final _injector = GetIt.instance;

T inject<T>() => _injector.get<T>(); // This is the line causing the error
```

I'm using the latest version 7.1.2

**Comment by escamoteur** [comment]
GetIt now enforces that T has to be minimal of type Object. So you have to

change your line to:
```Dart
T inject<T extends Object>() => _injector.get<T>();
```

**Comment by EdvaldoMartins** [comment]
> GetIt now enforces that T has to be minimal of type Object. So you have to
> 
> 
> 
> change your line to:
> 
> ```Dart
> 
> T inject<T extends Object>() => _injector.get<T>();
> 
> ```
> 
> 

Thank you very much, this worked for me. 🥳
