### ISSUE TITLE
Object/factory with  type IAuthFacade is not registered inside GetIt

### ISSUE THREAD

**Issue by HussainON** [fluttercommunity/get_it#191]
I'm experimenting a weird behavior resulting in a fatal error.

Installed versions:

Get_it version: 7.1.3
Injectable version: 1.4.0

### The error message is:

<img width="788" alt="Screen Shot 2021-05-15 at 7 21 20 PM" src="https://user-images.githubusercontent.com/50908333/118371024-26396080-b5b3-11eb-991b-c9d0302b45e2.png">

Here are the few files sections related to this error:

### injection file
<img width="546" alt="Screen Shot 2021-05-15 at 7 26 53 PM" src="https://user-images.githubusercontent.com/50908333/118371085-96e07d00-b5b3-11eb-947a-1536a175f883.png">

### main file
<img width="591" alt="Screen Shot 2021-05-15 at 7 27 55 PM" src="https://user-images.githubusercontent.com/50908333/118371113-b9729600-b5b3-11eb-8a99-d9191667d5dc.png">

### Some widgets where get_it and injectable are involved
<img width="739" alt="Screen Shot 2021-05-15 at 7 28 49 PM" src="https://user-images.githubusercontent.com/50908333/118371150-dc9d4580-b5b3-11eb-9567-d00b63e62971.png">

<img width="956" alt="Screen Shot 2021-05-15 at 7 35 07 PM" src="https://user-images.githubusercontent.com/50908333/118371312-ba57f780-b5b4-11eb-9f0b-4f0caa781173.png">

<img width="1035" alt="Screen Shot 2021-05-15 at 7 34 13 PM" src="https://user-images.githubusercontent.com/50908333/118371289-9c8a9280-b5b4-11eb-8f77-d5c2269c338f.png">

<img width="761" alt="Screen Shot 2021-05-15 at 7 32 05 PM" src="https://user-images.githubusercontent.com/50908333/118371235-50d7e900-b5b4-11eb-8a33-55128a1e6e61.png">

I'm trying to fix this for few days.
I don't understand what's going wrong. 
There is not syntax error which makes me puzzled of why I'm getting this error.
Any help would be greatly appreciated ;)

**Comment by escamoteur** [comment]
Unfortunately this seems to be a problem of injectable and not get_it. I'm a bit surprised to see that you use also provider but still use get_it to access your bloc in the UI?
I recommend having a look at get_it_mixin :-)

**Comment by HussainON** [comment]
Thanks for your response.
Do you think because I'm using provider with git_it that what causing the problem?
I tried many different ways to fix it and even searched for similar issues online but it seems no use.

**Comment by HussainON** [comment]
If so what would the this UI code below looks like if I used get_it_mixin instead?

<img width="739" alt="Screen Shot 2021-05-15 at 7 28 49 PM" src="https://user-images.githubusercontent.com/50908333/118372399-13765a00-b5ba-11eb-94e8-cc534c9d713e.png">

**Comment by escamoteur** [comment]
the problem probably doesn't come from the mixture of get_it and provider. Just something that seemed a bit strange to me.
With the get_it_mixin you don't need this part of the code anymore. you could directly use the `watchStream` function I think, but I'm not so familiar with the BloC library. 
check the readme of get_it_mixin.

**Comment by HussainON** [comment]
Ok Thank you, I will check it out!

**Comment by jrberronesc** [comment]
Hello, I also have this problem
How did you solve it?

**Comment by escamoteur** [comment]
@jrberronesc please open a new issue and describe in detail your problem with the code that you use
