### ISSUE TITLE
Upgrade async dependency

### ISSUE THREAD

**Issue by cedvdb** [fluttercommunity/get_it#193]
async dependency is outdated 2.5.0 while 2.6.1 is available

**Comment by escamoteur** [comment]
That shouldn't prevent you from doing a 
flutter package upgrade or not?

**Comment by cedvdb** [comment]
It does. After a package upgrade it shows up as outdated transitive dependency. I think upgrade only upgrades the patch version

**Comment by escamoteur** [comment]
done in V7.14
