### ISSUE TITLE
Feature Request: injection depending on target platform

### ISSUE THREAD

**Issue by mars3142** [fluttercommunity/get_it#194]
Problem:
I do have an abstract class **PlatformClass** and two implementations **PlatformClassAndroid** and **PlatformClassIOS**. Because they use different implementations, I would like to use dependency injection depending on the target platform.

For **DEV** and **PROD** I can switch, but not for target. That's why I wish, there would also be an annotation for TargetPlatform or something like that.

**Comment by escamoteur** [comment]
When you say you use annotations, does that mean you use injectable?

**Comment by mars3142** [comment]
Ah, you're right. I need to create a feature request for injectable ;)
