### ISSUE TITLE
Unable to get or isRegistered without passing type.

### ISSUE THREAD

**Issue by CobeGreene** [fluttercommunity/get_it#197]
![image](https://user-images.githubusercontent.com/32606730/120746509-35297980-c4b4-11eb-80ad-54df9900bd9f.png)

Hello, 

I'm getting an error (on 7.1.3) when I attempt to call get or isRegistered without the template type pass in, I would really like this functionality so I only have to pass the instance name and can make calls to get without knowing the type at compile type, it work in a previous build 4.0.4. Anyways, I've reverted back to 4.0.4 for now, but it's a really good package and I would really like to stay up to date. 

![image](https://user-images.githubusercontent.com/32606730/120746609-6e61e980-c4b4-11eb-84d5-43296194dd46.png)

I've narrow it down to this assert statement. 

![image](https://user-images.githubusercontent.com/32606730/120747313-acabd880-c4b5-11eb-84db-7ecbac050b01.png)

**Comment by escamoteur** [comment]
what is the return type of the function where you do that return?

**Comment by CobeGreene** [comment]
The return type is a service with a dynamic template, the dynamic template is because I've multiple services that implement and extend this base class. I've a router that automatically sets up a Change Notifier Provider for pages (using the provider package), however, the router must route for all pages where the types it needs to fetch change per a page so I was using the instance name to get the right service. 
``` dart
ModelService<dynamic> // The return type
```

**Comment by CobeGreene** [comment]
Thank you for the time you have already spent reading my question, it's much appreciate. I hope you don't mind reading some more, here's some code on what I'm essentially trying to do:
``` dart

import 'package:get_it/get_it.dart';

abstract class ModelService<T> {
  T get(int id); // Common method for models for router to get Models from
}
class ObjectA { final int id; ObjectA(this.id); }
abstract class ObjectAService<ObjectA> extends ModelService {
  // methods for ObjectAService ...
}
class AppObjectAService implements ObjectAService {
  ObjectA get(int id) => ObjectA(id); // implements ModelService 
  // implements ObjectAService ... 
}
class ObjectB { final int id; ObjectB(this.id); }
abstract class ObjectBService<ObjectB> extends ModelService {
  // methods for ObjectAService ...
}
class AppObjectBService implements ObjectBService {
  ObjectB get(int id) => ObjectB(id); // implements ModelService 
  // implements ObjectBService ... 
}

GetIt instance = GetIt.instance;

Type typeOf<T>() => T;
String nameOf<T>() => typeOf<T>().toString();

void main() {
  instance.registerLazySingleton<ObjectAService>(() => AppObjectAService(), instanceName: nameOf<ObjectA>());
  instance.registerLazySingleton<ObjectBService>(() => AppObjectBService(), instanceName: nameOf<ObjectB>());
  // Each page take a set of arguments
  var arguments = [ObjectA, ObjectB];
  var service =  instance.get(instanceName: arguments[0].toString()); // This throws Error 1. 
  var service2 =  instance.get<ModelService<dynamic>>(instanceName: arguments[0].toString()); // This throws Error 2. 
  // With the service, I use their get method to get the desired model for my page. 
  // Very handy because in my actual code,  model service get method returns a Future,
  // for it might need to talk to an API, and I have loading screen that now my pages don't have to implement.
 // as well as the overhead of setting up a multichangeprovider when I'm using the provider class. 
}

```
Here's Error 1:
![image](https://user-images.githubusercontent.com/32606730/120876710-4da69c00-c567-11eb-9c07-f20e766047aa.png)

Here's Error 2:
![image](https://user-images.githubusercontent.com/32606730/120876728-657e2000-c567-11eb-8fd1-9790bae243b3.png)

**Comment by CobeGreene** [comment]
Hi, not sure how much I like this solution. But if I registered it as a ModelService and get as ModelService, I can then cast to the extended class. 
``` dart
instance.registerLazySingleton<ModelService>(() => AppObjectAService(),
      instanceName: nameOf<ObjectA>());
var arguments = [ObjectA, ObjectB];
var service =  instance.get<ModelService>(instanceName: arguments[0].toString()) as ObjectAService;
```

**Comment by escamoteur** [comment]
Why would you use the type as an instanceName? I tried to uderstand what you are doing there and I failed.
Could you explain in simple words what you try to achieve? I have the feeling you are doing it way to compllicated

**Comment by CobeGreene** [comment]
Hi, yes some of the code is complicated, but the rest of the UI benefits. I'm using the model type as instanceName because each route has a list of arguments and I'm not able to write the following:
``` dart
instance.get<arguments[index]>(); 
``` 

A route looks like the following:
``` dart
static AppRoute route() => AppRoute(
      path: '/member/:id/group/:groupId',
      arguments: [Member, Group],
      build: () => MemberGroupPage());
```

and the MemberGroupPage gets the benefit that the member and group will both have their change notified setup for any changes, so I can write code like this without having to setup a multi-provider, plus there's some handling of loading that may occur if the model service has to fetch from the API. 
``` dart
this.context.watch<Group>().groupName;
```

**Comment by escamoteur** [comment]
But every page normally knows which objects it's needs, so why pass that in from the outside. Also I recommend using the get_it_mixin instead of provider when you already have objects inside get_it. you won't need any of that then.

**Comment by escamoteur** [comment]
@fullflash you mean you want to check with a variable of type `Type` if that type is registered?

**Comment by fullflash** [comment]
> @fullflash you mean you want to check with a variable of type `Type` if that type is registered?

yes exactly.  to avoid non_type_as_type_argument compiler error.
in dart it is impossible to use Type as argument. 
such functions would be helpful

```
isRegisteredWithName
unregisterWithName
```
