### ISSUE TITLE
 Object of type SharedPreferences is not registered inside GetIt

### ISSUE THREAD

**Issue by Devlonoah** [fluttercommunity/get_it#198]
This is what goes into my injection_container.dart file 

```

final sl = GetIt.instance;
Future init() async {

//Bloc
  sl.registerFactory(
    () => NumberTriviaBloc(
      inputConverter: sl(),
      concrete: sl(),
      random: sl(),
    ),
  );

//Data - source
  sl.registerLazySingleton<NumberTriviaLocalDataSource>(
      () => NumberTriviaLocalDataSourceImpl(sl()));


//External
  sl.registerLazySingleton(() async => await SharedPreferences.getInstance());
  sl.registerLazySingleton(() => client.Client());
  sl.registerLazySingleton<DataConnectionChecker>(
      () => DataConnectionChecker());
}

```

And this is how I use it in **main.dart**

void main() async{
  WidgetsFlutterBinding.ensureInitialized();
 await di.init();

  runApp(MyApp());
}

This is the error i get in my console
**_Exception: Object of type SharedPreferences is not registered inside GetIt_**

**Comment by Devlonoah** [comment]
I later got it solved by 

> Making the init function a asynchronous one using **async**

> creating a variable to get an instance of Sharedpreference,

final spref =await SharedPreference.getInstance();

> then ` sl.registerSingleton<SharedPreference>(() async => spref);`

**Comment by escamoteur** [comment]
you should use registerAsyncSingleton for this
