### ISSUE TITLE
Registering as dynamic

### ISSUE THREAD

**Issue by marcguilera** [fluttercommunity/get_it#2]
Hi thanks for the work, this is exactly what I was looking for.

I am tinkering with this and ran some unit tests. Basically calling ```getIt.registerFactory<Hello>(() => new Hello());``` registered Hello as ```dynamic``` so it fails when doing ```getIt.get<Hello>()``` plus it throws if I add something else because ```dynamic``` has already been registered. 

What am I missing?

**Comment by marcguilera** [comment]
Sure I'm sorry. I have an injector builder that looks like this:

```
import 'package:quiver/check.dart';
import 'iinjector.dart';
import 'injector_impl.dart';

typedef Type Factory<Type>(IInjector injector);

class InjectorBuilder {
  final InjectorImpl _injector = new InjectorImpl();

  InjectorBuilder registerSingleton<Type>(Factory<Type> factory) {
    checkNotNull(factory, message: () => "factory is null");

    _injector.registerLazySingleton(() => factory(_injector));
    return this;
  }

  InjectorBuilder registerFactory<Type>(Factory<Type> factory) {
    checkNotNull(factory, message: () => "factory is null");

    _injector.registerFactory(() => factory(_injector));
    return this;
  }

  InjectorBuilder registerAlias<Type, Alias extends Type>() {
    _injector.get<Type>(); // Will throw if type is not declared

    _injector.registerFactory<Alias>(() => _injector.get<Type>());
    return this;
  }

  IInjector build() {
    return _injector;
  }

}
```

InjectorImpl is just extending the GetIt class.

When I run tests on it this is what I find:
![pic](https://image.ibb.co/fgeA0y/Screen_Shot_2018_05_30_at_10_53_49_PM.png)

**Comment by escamoteur** [comment]
May I ask why you do this? Seems you destroy the slick use of GetIt that way.

Still not sure what your problem is. Could you make a simple repro where you register and then show me the problem?
