### ISSUE TITLE
Can't dispose the instantiated objects of the model class when it is registered

### ISSUE THREAD

**Issue by rajashah33** [fluttercommunity/get_it#20]
I have used registerLazySingleton to register the model of a scopped model. But on Navigator.pop() the variables are not clearing up.

**Comment by escamoteur** [comment]
What do you mean with dispose? Could you show me some code?
What should get cleaned up on pop()

**Comment by rajashah33** [comment]
`GetIt locator = GetIt();

void setupLocator() {

  // Register services
  locator.registerLazySingleton<StorageService>(() => StorageService());

  // Register models
  locator.registerLazySingleton<HomeModel>(() => HomeModel());
  locator.registerLazySingleton<LoginModel>(() => LoginModel());
  locator.registerLazySingleton<RegisterModel>(() => RegisterModel());
}
`

In flutter when dispose() is called the state objects are considered as unmounted and are disposed off.
When the back button is called the dispose() should be called.

Now Since I have registered the model with the registerLazySingleton. The objects  are not disposing. That is when I come back to the screen the textFields() associated with the objects of the model are filled up with previous values. 
Please correct me if I am doing/saying anything wrong, I am new to get_it.

**Comment by escamoteur** [comment]
LazySingleton is designed to do exactly this, it will give you always the same instance back.
Typically models live longer than Widgets. 
If you always need a new instance when this widget is build why not create it directly in initState? 
If you want to use GetIt for it you could use registerFactory

**Comment by escamoteur** [comment]
Yeah, you can call unregister, but I think it would be better to give your registered class a clear or reset method.

**Comment by rajashah33** [comment]
I can't use locator.unregister(). 
It says "The method 'unregister' isn't defined for the class 'GetIt'."

**Comment by escamoteur** [comment]
Are you on the latest version?

**Comment by rajashah33** [comment]
Oh! I am not on the latest version. Let me update it. 
Sorry.

**Comment by escamoteur** [comment]
Also I think you are using completely wrong if you need to use this. Normally you should only store long lived objects in GetIt

**Comment by rajashah33** [comment]
I would be thankful if you give some more information about it. What is the better way?

**Comment by escamoteur** [comment]
I would have to take a look at you Apps code. You say you use provider? If so you normally don't need GetIt with the exception if you have non UI classes that should access other non UI classes.

**Comment by rajashah33** [comment]
I have non UI class for accessing a non UI class. The model class is accessing the data from a class that accesses database.

**Comment by escamoteur** [comment]
Yep and that classes should be in GetIt. I don't understand why you create always a new instance of your model classes. Am 10.09.2019 18:42 schrieb Raja Shah <notifications@github.com>:I have non UI class for accessing a non UI class. The model class is accessing the data from a class that accesses database.

**Comment by rajashah33** [comment]
I think that because I have used BaseView 
I attached .dart file as .txt

[base_view.txt](https://github.com/fluttercommunity/get_it/files/3596967/base_view.txt)

**Comment by rajashah33** [comment]
Thanks for help. I understood and resolved the problem. It was not a problem btw. 👍
