### ISSUE TITLE
dispose function in registerXXX than it's arg is not the register type

### ISSUE THREAD

**Issue by Silentdoer** [fluttercommunity/get_it#200]
instance.registerSingleton(Foo(), instanceName: 's1', dispose: (foo) {
});

the foo is not analyzed Foo type, we must use (Foo foo) {}

**Comment by escamoteur** [comment]
can you elaborate?

**Comment by Silentdoer** [comment]
> elaborate

```dart
class Foo {
  String? prop;
}

instance.registerSingleton(Foo(), instanceName: 's1', dispose: (foo) {
});
```

if i just declare like above, foo is infer a Object? type, not Foo, so use foo.prop is error in callback

**Comment by escamoteur** [comment]
Yeah, that's a limit of Dart's analyzer. therefore I always recomment doing it

```dart
instance.registerSingleton<Foo>(Foo(), instanceName: 's1', dispose: (foo) {
});
```
then is works
