### ISSUE TITLE
can not get with Base type, such as I.get<Base>(instanceName: 'sss')

### ISSUE THREAD

**Issue by Silentdoer** [fluttercommunity/get_it#201]
when i register a Child instance with Base type, i can't get it with Base Type:
```dart
I.registerSingleton<Base>(Child(), instanceName: 'sss');
I.get<Base>(instanceName: 'sss');  // it is error, why?
```

**Comment by escamoteur** [comment]
Actually this should work. And it's the way I always use GetIt.
What doesn't work is `I.get<Child>(instanceName: 'sss')` because you always have to use the type to access that you used when registering.

**Comment by Silentdoer** [comment]
> Actually this should work. And it's the way I always use GetIt.
> What doesn't work is `I.get<Child>(instanceName: 'sss')` because you always have to use the type to access that you used when registering.

your mean is that this is a bug currently?

**Comment by escamoteur** [comment]
what exactly do you mean by 'this'? 
The fact that you have to use the exact type isn't a bug but they way GetIt works.

**Comment by Silentdoer** [comment]
my mean is the fellowingcode should be run ok?
```dart
.registerSingleton<Base>(Child(), instanceName: 'sss');
I.get<Base>(instanceName: 'sss');
```
because when i not support the instanceName, i can use
`I.get<Base>()` ok

**Comment by escamoteur** [comment]
if you have registered with an instance name you also have to use an instance name when accessing it. 
So

```Dart
I.get<Base>()
```

should not work if you haven't done a separate registration with an empty instance name

**Comment by escamoteur** [comment]
what error do you get? this is exactly who it should be used

**Comment by Silentdoer** [comment]
oh, it's my bad, i test again, it is works, sorry for used your time.
