### ISSUE TITLE
Registrering class with generics gives error

### ISSUE THREAD

**Issue by lgLindstrom** [fluttercommunity/get_it#207]
I have different model classes that I would like to save to a database. For this 
For example, one class is called Data Model. 

`class DataModel {}`

I have defined a database interface class.

```
class DbInterface<T> {
...... 
}
```

Then I have my database class. 

```
class Database<T> implements DbInterface<T> {
... 
} 
```

For a specific datamodel i register this within Getit

`getit.instance.registerSingelton<DbInterface<DataModel>>(Database<DataModel>)`

When trying to get a instance
`Getit.instance.get<DbInterface<DataModel>>()`

I get a error saying the DbInterface<DataModel> is not known within GetIt.

So, what Im I doing wrong?

**Comment by escamoteur** [comment]
On a first glance, this should work. I have to try to reproduce this

**Comment by escamoteur** [comment]
It maybe that this is a limitation in Dart see https://twitter.com/ThomasBurkhartB/status/1414977783906947081?s=20

**Comment by escamoteur** [comment]
I now tried to replicate exactly what you are doing:

```Dart
    GetIt.I.registerSingleton<TestBaseClassGeneric<TestBaseClass>>(
        TestClassGeneric<TestBaseClass>());

    final instance1 = GetIt.I.get<TestBaseClassGeneric<TestBaseClass>>();

    expect(instance1 is TestClassGeneric<TestBaseClass>, true);
````

which works without problems.

My class definitions look like:

```dart
class TestBaseClassGeneric<T> {
}

class TestClassGeneric<T> implements TestBaseClassGeneric<T> {
}
```

**Comment by escamoteur** [comment]
I close this for now. if you have more information, please comment.
