### ISSUE TITLE
graph factoryAsync does not accept Future with nullable object

### ISSUE THREAD

**Issue by boshrahi** [fluttercommunity/get_it#209]
Hi,
i use get_it: 7.1.3 in my flutter project.
recently we upgrade flutter and dart version so null safety should be handled.
we manually set up config.dart file, in this file I have this line 
```
final gh = GetItHelper(get, environment, environmentFilter);
gh.factoryAsync<Account>(() => accountModule.accountProvider(get<Authenticator>()));
```

the accountProvider method is like this:
```
@module
abstract class AccountModule {

  @factoryMethod
  Future<Account?> accountProvider(Authenticator authenticator) => AccountUtils.getAccount(authenticator);

}
```
```
static Future<Account?> getAccount(Authenticator authenticator, {String? accountName}) async {
    var accounts = await authenticator.getAccountsByType(ACCOUNT_TYPE);
    if(accountName != null) {
      for(var account in accounts) {
        if(account.name == accountName){
          return account;
        }
      }
      return null;
    } else {
      return accounts.isNotEmpty ? accounts[0] : null;
    }
  }
```
actually i need something like this:
`gh.factoryAsync<Account?> ` but I get error.: The return type 'Future<Account?>' isn't a 'Future<Account>', as required by the closure's context.
why is that? is there any way to add something null?

Thanks in advance

**Comment by escamoteur** [comment]
Hi, it looks like you are using injectable. Please ask at their repo, thanks
