### ISSUE TITLE
Race condition when waiting for isReady() after signalReady() was already called

### ISSUE THREAD

**Issue by Lootwig** [fluttercommunity/get_it#210]
The code below throws an exception (including a typo): "Unhandled Exception: Bad state: There are still other objects waiting for this instance **so** signal ready"

Since it's unpractical to guarantee the order in which calls to isReady / signalReady are executed when instances are distributed over the entire project, maybe the `objectsWaiting.add(...)` calls should be ignored after an instance already signaled to be ready once?

```dart
class X {}

void main() async {
  var x = X();
  GetIt.I.registerSingleton(x, signalsReady: true);
  GetIt.I.signalReady(x);
  await GetIt.I.isReady<X>();
  GetIt.I.unregister<X>();
}
```

**Comment by escamoteur** [comment]
Hi, interesting observation. will look into this next week.

**Comment by escamoteur** [comment]
Hi, I used your change in the next version but I also found some other cases where I needed to add a fix. you made your PR on master and not on the null-safety branch, that's why I don't merge it.

**Comment by Lootwig** [comment]
Ok
Looks like you kept the typo in, though.

**Comment by escamoteur** [comment]
yeah, sorry, but I don't think that's worth a new version :-)
thanks again for finding the problem
