### ISSUE TITLE
i have private or local package use it in my project how to use getIt with?

### ISSUE THREAD

**Issue by A7mdFathi** [fluttercommunity/get_it#211]

**Comment by MohammadEzoo** [comment]
I have the same question , I'm using a private package in my app, and I need to access the same dio instance from my app in my package so that I can change the config of the instance from the package.

**Comment by MohammadEzoo** [comment]
I think get it is singleton itself , so any call to Getit.instance will give the same instance that used in your app .
 then you can get any class from it in your package.

**Comment by escamoteur** [comment]
Exactly, I made is specifically that way. Unless you access get_it inside another isolate you will get the same instance in all packages.
