### ISSUE TITLE
Solving cyclic dependency

### ISSUE THREAD

**Issue by prijupaul** [fluttercommunity/get_it#218]
Hi @escamoteur,

First of all, Thank you for the library. 

Can you please provide examples of how get_it can solve's cyclic dependencies? 

for eg:
```
GetIt g = GetIt.instance;
g.registerLazySingleton<ServiceA>(() => ServiceA(g.get<ServiceB>()));
g.registerLazySingleton<ServiceA>(() => ServiceB(g.get<ServiceA>()));
```
If `ServiceA` is dependent on `ServiceB` and vice-versa, how do we solve it?

Thanks

**Comment by iandis** [comment]
I guess you can create a new class instead that both `ServiceA` and `ServiceB` can depend on.

**Comment by prijupaul** [comment]
> I guess you can create a new class instead that both `ServiceA` and `ServiceB` can depend on.

Can you elaborate @iandis. Any code samples pls..?

**Comment by iandis** [comment]
@prijupaul I think this [stackoverflow discussion](https://stackoverflow.com/questions/37414104/how-to-solve-cyclic-dependency) may help you.
