### ISSUE TITLE
GetIt not being able to correctly find registered Type

### ISSUE THREAD

**Issue by AlvBarros** [fluttercommunity/get_it#222]
Hey all!

Sorry if this issue is in the wrong format, I didn't find anything mentionind any guidelines on how to write one.

My app has this issue where I can't get my instance after registering.
Through some deep debugging, I've found this method "_findFirstFactoryByNameAndTypeOrNull" inside get_it_impl.dart that compares the given T to a scope's factoriesByName, and this comparison by Map index wasn't working properly.

In other words; when I run the line:
```
final AuthenticationService authService = GetIt.I.get<AuthenticationService>(instanceName: "authentication");
```

After a while, the package goes through its factories in its scope.
```    
while (instanceFactory == null && scopeLevel >= 0) {
      final factoryByTypes = _scopes[scopeLevel].factoriesByName[instanceName];
      if (type == null) {
        instanceFactory = factoryByTypes != null
            ? factoryByTypes[T] as _ServiceFactory<T, dynamic, dynamic>?
            : null;
      } else {
        /// in most cases we can rely on the generic type T because it is passed
        /// in by callers. In case of dependent types this does not work as these types
        /// are dynamic
        instanceFactory = factoryByTypes != null
            ? factoryByTypes[type] as _ServiceFactory<T, dynamic, dynamic>?
            : null;
      }
      scopeLevel--;
    }
```

But when I compare on debug:
<img width="626" alt="Captura de Tela 2021-08-17 às 14 03 53" src="https://user-images.githubusercontent.com/33898913/129769704-986e8936-f737-4430-a0cc-e2e2ff4b238b.png">

Am I doing something wrong?

**Comment by AlvBarros** [comment]
Here is my `flutter doctor`:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (2 available)
```

Here is my `flutter --version`: 

```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (7 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

I'm using `get_it` version `7.2.0`, running on macOS Big Sur.

**Comment by escamoteur** [comment]
Hi, sorry for not looking into this earlier, but I had some mental health problems the last half year.

this seems indeed strange. Does anyone of you have a short repro project?

**Comment by royd** [comment]
@escamoteur  I can repro [here](https://github.com/royd/flutter-architecture/tree/flow). 
Repro steps:
1. Run app
2. Click "Collect Sequence"
3. Enter a number and click "Accept"
3. Assertion

**Comment by royd** [comment]
The issue for me was with the improper capitalization of the import [here](https://github.com/royd/flutter-architecture/blob/2d667efa5d03248550470a4f67df0be1292abe74/lib/flow/import_seed/screen2/screen2_screen.dart#L1).

It compiles, but the hash code in the [factoryByTypes](https://github.com/fluttercommunity/get_it/blob/f372b951d1e8ee7aa445a85ec13bc2255d84c6eb/lib/get_it_impl.dart#L346) map was different from the requested type `T`.

**Comment by escamoteur** [comment]
How do mean mean the problem was the imports?
Am 4. Feb. 2022, 02:40 +0100 schrieb Roy ***@***.***>:

**Comment by escamoteur** [comment]
Also, does this happen on all Platforms?

**Comment by escamoteur** [comment]
For all others in this thread, can you check if you too might have different capitalization in your imports?

**Comment by escamoteur** [comment]
@leafpetersen to me this looks like a compiler bug if types get different Hashcodes depending on how the import is capitalised

**Comment by royd** [comment]
I see the same behavior on ios, macos, and web.

**Comment by escamoteur** [comment]
did you try to make a really simple project without get_it and compare the Hashcodes of the types if the imports differ? 
That would be really helpful and if yes you could directly report it to the dart team

**Comment by royd** [comment]
Here is a basic repro:
```
import 'one.dart' as lower;
import 'one.dart' as lower2;
import 'One.dart' as upper;

void main() {
  final a = lower.One;
  final b = lower2.One;
  final c = upper.One;

  print("a: ${a.hashCode}");
  print("b: ${b.hashCode}");
  print("c: ${c.hashCode}");
}
```

where the file `one.dart` contains
```
class One {}
```

which yields:
```
% dart run main.dart                   
a: 830824423
b: 830824423
c: 886268188
```

Interestingly, now VS Code is giving me a red line under `'One.dart'`, though it wasn't before, and though it still compiles.

**Comment by leafpetersen** [comment]
I believe you're running into a known sharp edge around non-canonical URIs.  Basically, if you import a file twice with a different URI, Dart treats the two imports as entirely unrelated things, as if you'd made two copies of the file and imported them separately.  So in your example above, `lower.One` and `upper.One` are treated as two entirely unrelated types from unrelated libraries that just happen to have the same name.  You can see this by trying to assign one to the other: if you add the line `lower.One one = upper.One();` to your test, you'll get a static error.  There is an request [here](https://github.com/dart-lang/sdk/issues/42829) for a hint to warn about this when possible.

cc @natebosch @lrhn in case I'm missing something else going on.

**Comment by escamoteur** [comment]
I recall that we had the same situation some time ago when you mixed package and relative imports that were solved so that these imported types were treated equally.

Why does Dart treat import filepaths caps-sensitive when it doesn't make any sense on non Unix like platforms?

**Comment by lrhn** [comment]
Dart identifies libraries by their import URL. Different capitalization makes it different URLs, even if they happen to resolve to the same local file. Library identification is case sensitive, because URLs are, independently of the underlying file system. (If there is a file system at all, originally you could import using `http:` URIs too).
What you remember is that `package:` URI imports are considered different from `file:` URI imports, even if both resolve to the same local file, a problem which has even more impact if such a double-imported library has relative imports of its own. We had a fix for *one* case of this: When a file in the `lib/` directory was passed as entry point on the command line, we treat it as the corresponding `package:` URI.

The problem with case is that it's not generally true that `foo.dart` and `Foo.dart` is the same file (only on Windows, but that means that it's also not generally true that they are different files.)
I think the best we can do is to warn if something looks like it's probably a mistake.

**Comment by escamoteur** [comment]
Hmm, OK, because Linux treats the paths differently you can't even just make the import lowercase because you could access the real file no longer.
But a warning is definitely necessary. Windows developers are not used to think about capitalisation in paths
Am 5. Feb. 2022, 19:08 +0100 schrieb Lasse R.H. Nielsen ***@***.***>:
