### ISSUE TITLE
Test widget problem after upgrade Dart 2.12

### ISSUE THREAD

**Issue by mdmota** [fluttercommunity/get_it#224]
I'm having problems testing the widget to registerFactory using mockito and getIt.
This code worked before the flutter/dart migration.

My Code Test:
` var mockAnalytics = MockFBAnalytics();

    GetIt.instance.registerFactory<AnalyticsService>(() => mockAnalytics);

    when(mockAnalytics.getAnalytics()).thenReturn(FirebaseAnalytics());`

Error when running:
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _TypeError was thrown running a test:
type 'Null' is not a subtype of type 'FirebaseAnalytics'

Ref: https://flutterprojects.blog/2021/05/17/widget-testing-with-mockito/

**Comment by escamoteur** [comment]
Hi, sorry for not looking into this earlier, but I had some mental health problems the last half year.

I think this is a mockito problem with the null safety
