### ISSUE TITLE
Get by superclass/subclass?

### ISSUE THREAD

**Issue by fzyzcjy** [fluttercommunity/get_it#231]
Hi thanks for the lib! Consider this simplified example:

```
class SuperClass {}
class SubClass extends SuperClass {}

GetIt.I.registerSingleton<SubClass>(SubClass());
GetIt.I.get<SubClass>(); // ok
GetIt.I.get<SuperClass>(); // error!
```

Can we allow the last line to return the SubClass? Currently I workaround by registering twice, but I hope I can register once and make it work.

**Comment by escamoteur** [comment]
Hi, sorry for not looking into this earlier, but I had some mental health problems the last half year.

Why don't you register it with the SuperClass? Can you elaborate on the usecase?

**Comment by fzyzcjy** [comment]
> but I had some mental health problems the last half year.

Sorry to hear that :( Hope you get better now!

> Why don't you register it with the SuperClass? Can you elaborate on the usecase?

Indeed I have forgotten why I needed it (months have passed). Currently I think (normally) I can register with the superclass; if I find out why I made this issue I will reopen it. Thanks!
