### ISSUE TITLE
unregister scope issue

### ISSUE THREAD

**Issue by ccadieux** [fluttercommunity/get_it#239]
The following code produces this error. `Null check operator used on a null value`
```
    GetIt.I.registerLazySingleton<A>(() => A());
    GetIt.I.pushNewScope(scopeName: 'scope');
    if (GetIt.I.isRegistered<A>()) {
      GetIt.I.unregister<A>();
    }
```

isRegistered checks all scopes but but unregister only uses the current scope. I don't see a way to check if something is registered in the current scope to prevent this issue.

Seems related to https://github.com/fluttercommunity/get_it/issues/189

**Comment by escamoteur** [comment]
fixed in next version
