### ISSUE TITLE
Allow for UnitOfWork Scoping

### ISSUE THREAD

**Issue by kmanpro** [fluttercommunity/get_it#25]
I really like the simplicity of get_it and it's speed.
Thank you so much for creating and maintaining this product!

I am wondering if we can get the ability to do UnitOfWork scoping where even factories will be the same instance if used in the same UnitOfWork.

See the code below for the example:

**Registration**

```
GetIt.I.registerFactory<SharedService>(() => new SharedService());
GetIt.I.registerFactory<Service3>(() => new Service3(GetIt.I.get<SharedService>()));
GetIt.I.registerFactory<Service2>(() => new Service2(GetIt.I.get<SharedService>()));
GetIt.I.registerFactory<MainService>(() => new MainService(GetIt.I.get<Service2>(), GetIt.I.get<Service3>()));
```
**Classes**
```
class MainService(Service2 service2, Service3 service3)
class Service2(SharedService sharedService)
class Service3(SharedService sharedService)
```
**Test**
```
var service1 = GetIt.I.get<MainService>();
        expect(service1.service2.service4, same(service1.service3.service4));
```

**Can SharedService be the same instance in this unitOfWork without making it a singleton?**

**Comment by escamoteur** [comment]
Sure, just use `registerSingleton` instead of `registerFactory` or why would this be a problem?

**Comment by kmanpro** [comment]
Thanks for your response, and time on this issue!

I was looking for a scoped lifetime on services, if possible. More than just Singleton/Factory.
I don't need SharedService to be a singleton globally, but I do need it to be a scoped singleton for a certain process.

**Example** (click button and start a new unit of work processing in the background. In the scope of that unit of work the SharedService is a singleton. Once that process is done the object should be disposed and the next time the process is ran it should new up a new SharedService.)

Hope that makes sense. I am coming from a C# web background and am used to scoping my Dependency Injection to the current request using StructureMap.  So perhaps it is just me applying web concepts to my mobile app incorrectly ;).

I of course could handle this by making SharedService always a global singleton and reset the state of it every time one of these ends but like the clean ability to scope my services without passing them around to each other.

I'll close it for now since it probably doesn't make much sense in this context.

Thanks!

**Comment by escamoteur** [comment]
Hmmm, perhaps it might interest you that the next version will have a reset for Lazy Singleton so this might be a solution.
I'm still pondering on when a scoped injection would be needed because I didn't have the requirement yet.
