### ISSUE TITLE
Using Same Object Multiple Times (To Use Multiple APIs using Get It & Dio Package)

### ISSUE THREAD

**Issue by milan-7span** [fluttercommunity/get_it#250]
I am using Get It for State management for my Flutter App

I want to use multiple APIs with [Dio](https://pub.dev/packages/dio) Package. 

What i have done:
I have added two Dio Clients for two different APIs
I have add these two lines for registering Dio Clients in Get It.

// First API (Dio Client)
  _getIt.registerSingleton<Dio>(DioClient().getDio());

// Second API (Dio Client)
  _getIt.registerSingleton<Dio>(DioAnotherClient().getDio());

I am Facing this error after doing this:
E/flutter (13845): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Object/factory with  type Dio is already registered inside GetIt. 

I am seeking a solution to Use Multiple APIs using GetIt & Dio Package.

Can anyone provide a solution to this issue?

**Comment by escamoteur** [comment]
Hi,
it's actually very easy to fix for that case you have to provide different `instanceNames` when registerinf and use that too when you access the instances

**Comment by milan-7span** [comment]
> Hi, it's actually very easy to fix for that case you have to provide different `instanceNames` when registerinf and use that too when you access the instances

Okay, Thanks for the help!
