### ISSUE TITLE
Questions: Best practice of getting app buildContext?

### ISSUE THREAD

**Issue by itaishalom** [fluttercommunity/get_it#256]
The documentation states that:
"The fact that you need a BuildContext to access your objects made it inaccessible from the Business layer."

But it is unclear what is the best practice? 
If I wish to access the app context from service (not from a widget), what is the best practice to achieve it?

**Comment by escamoteur** [comment]
You want to access the Build context from your Business logic?
In General you should avoid that.
You can check the code of my interaction_manager where I do that do displays dialogs from non UI code
Am 15. Feb. 2022, 13:30 +0100 schrieb Itai Shalom ***@***.***>:

**Comment by itaishalom** [comment]
The truth is that i do want to show dialog from non ui code. Where can I see that example?
