### ISSUE TITLE
How to check if object created inside of getIt?

### ISSUE THREAD

**Issue by mgazisalik** [fluttercommunity/get_it#257]
GetIt.I.registerLazySingleton(() => CrosswordManager());

I tried to check if an object was created by LazySingleton at least one time but I didn't find it. Because I want to reset the object somewhere.

**Comment by escamoteur** [comment]
Why do you have to check if its created?
Am 15. Feb. 2022, 18:20 +0100 schrieb Muhammet Gazi Salık ***@***.***>:

**Comment by mgazisalik** [comment]
@escamoteur because otherwise I get this error: 

> StateError (Bad state: This instance of the type CrosswordManager is not available in GetIt If you have registered it as LazySingleton, are you sure you have used it at least once?)

**Comment by mgazisalik** [comment]
@escamoteur I need to reset those data in somewhere inside of object.

**Comment by escamoteur** [comment]
Do you use resetLazySingleton? Because with that this should not be possible
Am 15. Feb. 2022, 18:28 +0100 schrieb Muhammet Gazi Salık ***@***.***>:

**Comment by mgazisalik** [comment]
> 

Yes, I used resetLazySingleton. So why this should not be possible?

**Comment by mgazisalik** [comment]
@escamoteur let me explain the scenario. I registered my object as a lazySingleton. I called this object the first time on the third screen in my app but I am calling this object with a parameter. When the user returns to back the second screen and then selects the third screen, I need to reset my singleton object and create it with a different parameter.

**Comment by escamoteur** [comment]
Wouldn't it the not make more sense to use a factory instead of a Singleton?
Am 15. Feb. 2022, 18:45 +0100 schrieb Muhammet Gazi Salık ***@***.***>:

**Comment by mgazisalik** [comment]
@escamoteur yes it would make more sense. But I tried to use registerFactoryAsync but I got some errors and didn't understand usage. Can you add more examples to this package?

**Comment by escamoteur** [comment]
Do you need an async factory function?
Am 15. Feb. 2022, 23:00 +0100 schrieb mgazisalik ***@***.***>:

**Comment by mgazisalik** [comment]
@escamoteur I solved some of issues myself. But I am still getting some error. For example I used registerFactory and registerFactoryAsync to create new object, but when I create new one getIt give me error like this: 

> ArgumentError (Invalid argument(s): Object/factory with  type CrosswordManager is already registered inside GetIt.

What should I do? Maybe I misunderstand something. It would be good if there is a discord channel for this package. Or maybe more example. At least there should be some examples under the functions of descriptions.

**Comment by mgazisalik** [comment]
> registers a type so that a new instance will be created on each call of [get] on that type [T] type to register [factoryFunc] factory function for this type [instanceName] if you provide a value here your factory gets registered with that name instead of a type. This should only be necessary if you need to register more than one instance of one type. Its highly not recommended

I was misunderstand something. I don't need to create more than one instance of one type. I just need one instance of one type and should be able to reset existing data. I would actually do this manually but I wanted to do this in a more good way because maybe I would forget to reset some data and some bugs can appear in my app. So then I need to know if an instance was created or not.

**Comment by fullflash** [comment]
it would be nice to make publicly available method **_findFactoryByNameAndType**
we need to check if singleton object is created n order to use it without creating.
Anyway such method already exists but private.

**Comment by escamoteur** [comment]
@mgazisalik you could use a scope for that. Maby my talk https://www.youtube.com/watch?v=YJ52kSfSMyM&list=PL-BFoWYMGZ2TvwY0uf1fBJB1358utBlAz&index=10 will also help you

**Comment by escamoteur** [comment]
@fullflash what's wrong with

```Dart
  /// Tests if an [instance] of an object or aType [T] or a name [instanceName]
  /// is registered inside GetIt
  bool isRegistered<T extends Object>({Object? instance, String? instanceName});
```

**Comment by fullflash** [comment]
isRegistered is checking if class is registered but we were asking for ability to check if instance is created .

isRegistered will be true after called registerLazySingleton but how to know if singleton instance is called before.

**Comment by escamoteur** [comment]
Why would you need to know that? The Lazy Singleton guarantees that the instance is available when you first access it
Am 25. Feb. 2022, 19:45 +0100 schrieb fullflash ***@***.***>:

**Comment by mgazisalik** [comment]
Can you please provide this api? I still need this. For instance, I have an object and it should be created with lazy. And I need to reset when this object should not be used. Please, I need this api. If you will not provide this api, I will use my own singleton objects and will remove get_it package.

**Comment by escamoteur** [comment]
As noone has brought a conclusve argument why you need this, I close this issue now. If you have to check if your lazy Singleton is already created that feels like a code smell of a bad design to me.

**Comment by escamoteur** [comment]
You are aware that there is a resetLazySingleton function for exactly this use case?
Am 16. März 2022, 15:44 +0100 schrieb mgazisalik ***@***.***>:

**Comment by fullflash** [comment]
we need to check if lazysingleton is registered if registered to call a method of this class if not ignore.
use case product list bloc that fetching products and caches
and there is a different view (that can be accessed independently of product list page) has a function to scan prouct by barcode and edit the title image etc. so if product list fetched it will update the title inside the cached product list if not nothing to edit.

but if a class is not registered especially a lazy singleton why isRegistered returns true ?

**Comment by escamoteur** [comment]
@fullflash to you last comment. You claim that without any registration `isRegistered` returns true? Please provide a code example how you use it there.

have you checked the relatively new function `checkLazySingletonInstanceExists`
and maybe you would be better off not using a lazy singleton but use `registerSingletonIfAbsent`

**Comment by fullflash** [comment]
@escamoteur thanks! those new methods looks like what we need.
