### ISSUE TITLE
Reset lazy singleton

### ISSUE THREAD

**Issue by mariomka** [fluttercommunity/get_it#26]
Get it is awesome! Congrats!

I have to reset (only reset, not unregister) some lazy singletons when the user logout and force to instance a new object. Is there any way to do this?

Thank you!

**Comment by ewertonrp** [comment]
For now, you need to unregister and register again.

**Comment by escamoteur** [comment]
Thanks a lot for the PR

**Comment by mariomka** [comment]
Amazing! When it will be available?

**Comment by shrimantNikate** [comment]
can anyone give me the example how this should be used ?

**Comment by escamoteur** [comment]
Whats isn't clear?
