### ISSUE TITLE
Flutter using getit and mobx

### ISSUE THREAD

**Issue by Saim213** [fluttercommunity/get_it#264]
Invalid argument(s): Object/factory with  type LoginStore is already registered inside GetIt. 
![0111Capture](https://user-images.githubusercontent.com/58992568/157655056-cbcb23ba-4020-43bd-b101-4526aca23a15.PNG)

**Comment by Rohithgilla12** [comment]
@Saim213 Can you. please show a snippet on how you are registering it?
Maybe I can help, I have developed one recently with MobX + Get_it

**Comment by Saim213** [comment]
ok

**Comment by Saim213** [comment]
ok

**Comment by Saim213** [comment]
![image](https://user-images.githubusercontent.com/58992568/157659742-bdbeb2fd-4a8f-42fe-ac4f-ec79e7b1e3c2.png)

**Comment by Saim213** [comment]
![image](https://user-images.githubusercontent.com/58992568/157659885-cd9abc87-16c7-4732-82ea-138fb326d017.png)

**Comment by escamoteur** [comment]
I recommend doing your registration before you create your app object. Because if your homepage is destroyed and recreated you registration is called twice.
Am 10. März 2022, 13:16 +0100 schrieb Saim213 ***@***.***>:

**Comment by Saim213** [comment]
ok

**Comment by Saim213** [comment]
Thanks for the tip!

**Comment by escamoteur** [comment]
Seems you are trying to register the same type twice
Am 10. März 2022, 12:43 +0100 schrieb Saim213 ***@***.***>:
