### ISSUE TITLE
it say does not registered but it registered successfully

### ISSUE THREAD

**Issue by mostafasaadamin** [fluttercommunity/get_it#274]
Object/factory with  type TokenLocalRepository is not registered inside GetIt. 
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
'package:get_it/get_it_impl.dart':
Failed assertion: line 372 pos 7: 'instanceFactory != null'

`Future<void> init() async {
  getIt.registerLazySingleton(() => CompanyUrls(
    storeKeeperUrl: "",
    personnelUrl: "",
    tokenEndPoint: "",
    miscUrl: "",
    domain: "",
    apiUrl: ""));
  getIt.registerLazySingleton(() => AppLanguage());
  getIt.registerLazySingleton(() => Daily());
  getIt.registerLazySingleton(() => PointOfSale());
  getIt.registerLazySingleton(() => User());
  getIt.registerLazySingleton(() => ConnectionServices());
  getIt.registerLazySingleton(() => AlerterMessage());
  getIt.registerLazySingleton<IPrinter>(() => PrinterLocalRepository());
  getIt.registerLazySingleton<IToken>(() => TokenLocalRepository());
  getIt.registerLazySingleton<IUrls>(() => UrlsLocalRepository());
  getIt.registerLazySingleton<IUsers>(() => UserLocalRepository());
  getIt.registerLazySingleton<IRemoteToken>(() => TokenRepository(language: getIt(), companyUrls: getIt()));
  getIt.registerLazySingleton<ICompanyUrls>(() => CompanyUrlsData(client: getIt()));
  getIt.registerLazySingleton<IRemoteUser>(() => UserRepository(client: getIt()));
  getIt.registerLazySingleton(() => TokenService(tokenLocalRepository: getIt(),tokenRepository: getIt()));
  getIt.registerLazySingleton(() => RequestProvider(
      companyUrls: getIt(), language: getIt(), tokenService: getIt()));
  getIt.registerFactory(() => SplashViewModel(
      language: getIt(),
      companyUrls: getIt(),
      userLocalRepository: getIt(),
      user: getIt(),
      urlsLocalRepository: getIt(),
      tokenLocalRepository: getIt(),
      printerLocalRepository: getIt()));
  getIt.registerFactory(() => CodeViewModel(
      connectionService:getIt(),
      companyUrls: getIt(),
      urlsRepository:getIt(),

      messageService:getIt(),
      urlsLocalRepository: getIt(),));
}`

**Comment by omerrciftcii** [comment]
Also I have same issue and looking the answers almost 2 days.

**Comment by escamoteur** [comment]
Sorry for the late response, I had to take a longer break due to health issues. If you still have a problem, please open a new issue
