### ISSUE TITLE
instanceName "highly not recommended"

### ISSUE THREAD

**Issue by davidsowerby** [fluttercommunity/get_it#282]
Hi

Firstly, thanks for this package - I find it incredibly helpful.

I am a bit confused, though, about the use of the `instanceName` option.  It is "highly not recommended" as in the extract below, and yet it was put forward as a possible solution in #272.

There is presumably a risk attached to using this option, but the docs do not give any indication (that I can find) what that risk might be.  Could you explain the concerns?

```
  /// [instanceName] if you provide a value here your instance gets registered with that
  /// name instead of a type. This should only be necessary if you need to register more
  /// than one instance of one type. It's highly not recommended.
```

**Comment by escamoteur** [comment]
Sorry for the late response, I had to take a longer break due to health issues. After I used the instance name now in my own project, I have to agree, there are cases where it's the perfect solution. I removed the warning from the docs
