### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value 

### ISSUE THREAD

**Issue by Hardik3143** [fluttercommunity/get_it#283]
E/flutter (20701): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
E/flutter (20701): #0      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:380)
E/flutter (20701): #1      _GetItImplementation.get (package:get_it/get_it_impl.dart:393)
E/flutter (20701): #2      _GetItImplementation.call (package:get_it/get_it_impl.dart:430)
E/flutter (20701): #3      init (package:nowopen/di/injection_container.dart:33)
E/flutter (20701): <asynchronous suspension>
E/flutter (20701): #4      main (package:com.opn/main.dart:21)
E/flutter (20701): <asynchronous suspension>
E/flutter (20701): 

Facing above issue while launch app  but can't run it.

**Comment by escamoteur** [comment]
That is a pretty weird exception. It happens in ui_dart_state.cc according to that stack trace.
Can you try debug to the last mentioned line in get_it_implementation and check which variables are null that shouldn't be null?

I'm currently down with Covid so I can't really look into it
Am 27. Juni 2022, 11:16 +0200 schrieb Hardik Prajapati ***@***.***>:

**Comment by safwanyp** [comment]
try using a null-aware operator? just a shot in the dark..

**Comment by xVemu** [comment]
@Hardik3143 Did you manage to fix this?
