### ISSUE TITLE
[Question]Config generation differences for the same set of dependencies

### ISSUE THREAD

**Issue by DartAndrik** [fluttercommunity/get_it#285]
When using approach of holding generated code in developer branch, you may setup some code validation pipelines for your CI/CD that check your generated code in PR on Git DIFF. And they won't work with this package correct. The code from pipeline-generated config is valid but has differences. For example:
```
import 'package:my_package/src/data/repository/signatures_repository_impl.dart'
    as _i110;
import 'package:my_package/src/data/repository/stops_repository_impl.dart'
    as _i243;
    as _i246;
import 'package:my_package/src/data/repository/sync_repository_impl.dart'
    as _i301;
import 'package:my_package/src/data/repository/sync_settings_repository_impl.dart'
    as _i186;
    as _i176;
```
Yes i agree it's up to you. But it would be great if the code will be the same every time for unchanged dependencies set. Is it possible to add such improvements?

**Comment by AndrewsMlab** [comment]
Sorry,  can you please close this issue. Looks like i used wrong package for it.
