### ISSUE TITLE
Cant register with get_it on latest versions

### ISSUE THREAD

**Issue by ajinkya446** [fluttercommunity/get_it#288]
**User cases and repositories cant be registered and getting this issue while running**

The following assertion was thrown:
Object/factory with  type HomePageBloc is not registered inside
GetIt.
(Did you accidentally do GetIt sl=GetIt.instance(); instead of
GetIt sl=GetIt.instance;
Did you forget to register it?)
'package:get_it/get_it_impl.dart':
Failed assertion: line 372 pos 7: 'instanceFactory != null'

When the exception was thrown, this was the stack:
#2      _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:372:7)
#3      _GetItImplementation.get (package:get_it/get_it_impl.dart:393:29)
#4      _GetItImplementation.call (package:get_it/get_it_impl.dart:430:12)
#5      _HomePageState.blockBody.<anonymous closure> (package:task/main.dart:80:38)
#6      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:736:36)
#7      _InheritedProviderScopeElement.value (package:provider/src/inherited_provider.dart:590:33)
#8      Provider.of (package:provider/src/provider.dart:303:37)
#9      ReadContext.read (package:provider/src/provider.dart:649:21)

**Comment by mateusdevelopes** [comment]
I pass for the same problem here, i suggest downgrade package version!

**Comment by escamoteur** [comment]
Hi, with this little information I fear I can't help you. Are you sure you have registered HomepageBlock correctly? 
Otherwise I will need a demo project that I can debug

**Comment by escamoteur** [comment]
Sorry for the late response, I had to take a longer break due to health issues. If you still have a problem, please open a new issue
