### ISSUE TITLE
Feature: Support for Annotation

### ISSUE THREAD

**Issue by dinbtechit** [fluttercommunity/get_it#290]
This is a great package but would be nice if there were annotations. This will make the code cleaner. I would like to implement this. But I am looking for some guidance. Or some reference to get_it architecture.

```dart
@Injectable(type= "singleton" | "lazySingleton" | "factory" (default), primary=true | false (default), order = 1 )
class InjectableClass {

}
```

Usage: 

```dart
@Injectable 
class A {
  
}

@Injectable 
class B {
  B(A a) {}    // <<--<<  A gets injected here.
}

```

**Comment by mjablecnik** [comment]
@dinbtechit You can use [injectable](https://pub.dev/packages/injectable) package with get_it.

**Comment by dinbtechit** [comment]
the injectable package has a ton of issues. I thought it would be nice to have some first-class support for injectables. But I would totally agree if you think that's outside the scope of this package. Cheers.

**Comment by iandis** [comment]
I've been using injectable package with get_it for production apps and have never faced any issue at all. Definitely worth to try👍

**Comment by dinbtechit** [comment]
closing this as there is a package, injectable for this.
