### ISSUE TITLE
Where to register singletons, main.dart or elsewhere?

### ISSUE THREAD

**Issue by tobinharris** [fluttercommunity/get_it#291]
What's the safest place to register singletons with GetIt, `main.dart` or elsewhere?

On the app I'm working on now we're doing it in the splash screen that is our `initialRoute`.  

On splash screen `init()` we then re-register everything.

```
void init() async {
  GetIt.instance.allowReassignment = true;
  GetIt.instance.registerSingleton<Db>(db);
  //register more stuff here...
}
```

This has been working fine for a while, but I wondered if it's bad practice for any reason? Most of the examples show singleton registration in `main.dart`.

**Comment by escamoteur** [comment]
I'm not sure if you can get problems doing this in an async init function. I normally do it directly before my call to `runApp`.

**Comment by tobinharris** [comment]
> I'm not sure if you can get problems doing this in an async init function. I normally do it directly before my call to `runApp`.

Thanks, I'll see if it's possible to move it. I'm still learning about Dart, what do you think _could_ cause the issue in `async init`?
