### ISSUE TITLE
popScopeUntil should allow baseScope with inclusive: false

### ISSUE THREAD

**Issue by ccadieux** [fluttercommunity/get_it#299]
Thank you for adding the inclusive flag on popScopeUntil. I feel the assert needs to be updated with the new flag though. 
https://github.com/fluttercommunity/get_it/blob/master/lib/get_it_impl.dart#L795

This should be valid but fails due to the current assert. Since it's are popping everything except the baseScope.
```
  await GetIt.I.popScopesTill('baseScope', inclusive: false);
```

Current:
```
assert(scopeName != _baseScopeName, "You can't pop the base scope");
```

Suggested
```
assert(inclusive && scopeName != _baseScopeName, "You can't pop the base scope");
```

**Comment by escamoteur** [comment]
Sorry for the late response, I had to take a longer break due to health issues. Thanks for this catch, will be fixed in the next release

**Comment by ccadieux** [comment]
Thank you. Good to see you back!
