### ISSUE TITLE
Futures and Hot Reload

### ISSUE THREAD

**Issue by Magenda** [fluttercommunity/get_it#31]
Is there any way to make future instances work with hot reload? 

For an explanation on the issue please read here: https://stackoverflow.com/questions/58326960/flutter-get-it-and-futurebuilder-not-working-with-hot-reload

Thanks!

**Comment by escamoteur** [comment]
What are you thinking about this as new API 

`Future<void> allReady();` 

and 

`Future<void> isReady<T>({Object instance, String instanceName}); `

instead of exposing the Future or Stream directly? With this way we get more control and I can easily correct the problem above

**Comment by escamoteur** [comment]
Hi, I'm just doing an overhaul of the initialization helper of GetIt.
It would be great if you could have a look at my current API proposal and give me Feedback 
https://gist.github.com/c4c717518729a4c24a4ce95c10111473

**Comment by escamoteur** [comment]
Should be handled better with version V4.0.0 please check https://github.com/fluttercommunity/get_it/issues/46
