### ISSUE TITLE
[Request] Add custom scope open/closing

### ISSUE THREAD

**Issue by Anfet** [fluttercommunity/get_it#313]
Hi everyone.

With this feature we can tie scopes to stateful widget lifecycle initState/dispose methods.

With current model it's not possible, since widget A can be disposed after Widget B initState is called. Therefor breaking scope destruction.

**Comment by subzero911** [comment]
Same here, I just got a scope race condition, when I pop scope on widget dispose and register a new singleton on a new screen open.
But the new singleton gets into the old scope which would got disposed in a next frame.
I couldn't figure out why my new singleton disappears!

**Comment by escamoteur** [comment]
Any idea how this should lool like? If you only want to tie a scope to a widgets life cycle, the get_it_mixin would be the more elegant solution.

**Comment by Anfet** [comment]
Just add a scope name to close function.

**Comment by escamoteur** [comment]
Can you elaborate on how you mean that?

**Comment by Anfet** [comment]
Just add a scopeName to popScope function. 
```
getIt.pushNewScope(scopeName: someScreen);
getIt.popScope(scopeName: someScreen);
```
This way we can close any open scope.

**Comment by escamoteur** [comment]
but that wouldn't be popping but removing a scope anywhere in the stack, or not?

There is actually a PR waiting for that https://github.com/fluttercommunity/get_it/pull/292

I'm not sure if that would help with the race condition that you observed?

**Comment by Anfet** [comment]
Yep. Thats exactly what is needed.
Thank you.

**Comment by escamoteur** [comment]
https://github.com/fluttercommunity/get_it/issues/316#issuecomment-1535797647
