### ISSUE TITLE
Error Register SharedPreferences in Widget Testing

### ISSUE THREAD

**Issue by rrifafauzikomara** [fluttercommunity/get_it#314]
Hi, I get this error when register `SharedPreferences` class.
```dart
dart:async                                                        _Completer.completeError
package:shared_preferences/shared_preferences.dart 38:19          SharedPreferences.getInstance
===== asynchronous gap ===========================
dart:async                                                        _CustomZone.registerBinaryCallback
package:shared_preferences/shared_preferences.dart 33:13          SharedPreferences.getInstance
test/presentation/ui/profile/main_profile_screen_test.dart 20:51  main.<fn>.<fn>

PlatformException(channel-error, Unable to establish connection on channel., null, null)
```

This is my widget testing.
```dart
final sl = GetIt.instance;
void main() {
  group('MainProfileScreen test', () {
    late AppTestMaterialApp app;

    setUpAll(() async {
      TestWidgetsFlutterBinding.ensureInitialized();
      final preferences = await SharedPreferences.getInstance();
      sl.registerLazySingleton(() => preferences);

      ...

      app = AppTestMaterialApp(
        providers: [
          BlocProvider(
            create: (context) => ProfileBloc(
              profileUseCase: sl(),
              authUseCase: sl(),
              localization: sl(),
            ),
          ),
        ],
        home: const MainProfileScreen(),
      );
    });

    testWidgets('can render MainProfileScreen', (WidgetTester tester) async {
      await tester.pumpWidget(app.widget);
      await tester.pumpAndSettle();

      expect(find.byType(MainProfileScreen), findsOneWidget);
    });
  });

  tearDownAll(() {
    /// clear di after finish test
    sl.reset(dispose: true);
  });
}
```

**Comment by emintolgahanpolat** [comment]
https://github.com/flutter/packages/blob/main/packages/shared_preferences/shared_preferences/test/shared_preferences_test.dart

You must create a mock platform for shared preference testing. Your question is not about get_it.

**Comment by vousmeevoyez** [comment]
You need to create mock for shared preference.

```
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'storage_test.mocks.dart'; // change depending on your test_file_name and generate it from bulid_runner

final sl = GetIt.instance;


@GenerateMocks([SharedPreferences])
void main() {
  group('MainProfileScreen test', () {
    late MockSharedPreferences mockSharedPreferences;
    late AppTestMaterialApp app;

    setUpAll(() async {
      TestWidgetsFlutterBinding.ensureInitialized();
      
       mockSharedPreferences = MockSharedPreferences();
      sl.registerLazySingleton(() => mockSharedPreferences);

      ...

      app = AppTestMaterialApp(
        providers: [
          BlocProvider(
            create: (context) => ProfileBloc(
              profileUseCase: sl(),
              authUseCase: sl(),
              localization: sl(),
            ),
          ),
        ],
        home: const MainProfileScreen(),
      );
    });

    testWidgets('can render MainProfileScreen', (WidgetTester tester) async {
       when(mockSharedPreferences.getString(any)).thenAnswer((_) => "hello");

      await tester.pumpWidget(app.widget);
      await tester.pumpAndSettle();

      expect(find.byType(MainProfileScreen), findsOneWidget);
    });
  });

  tearDownAll(() {
    /// clear di after finish test
    sl.reset(dispose: true);
  });
}

**Comment by vousmeevoyez** [comment]
> You need to create mock for shared preference.
> 
> ```
> import 'package:mockito/annotations.dart';
> import 'package:mockito/mockito.dart';
> import 'package:shared_preferences/shared_preferences.dart';
> 
> import 'storage_test.mocks.dart'; // change depending on your test_file_name and generate it from bulid_runner
> 
> final sl = GetIt.instance;
> 
> 
> @GenerateMocks([SharedPreferences])
> void main() {
>   group('MainProfileScreen test', () {
>     late MockSharedPreferences mockSharedPreferences;
>     late AppTestMaterialApp app;
> 
>     setUpAll(() async {
>       TestWidgetsFlutterBinding.ensureInitialized();
>       
>        mockSharedPreferences = MockSharedPreferences();
>       sl.registerLazySingleton(() => mockSharedPreferences);
> 
>       ...
> 
>       app = AppTestMaterialApp(
>         providers: [
>           BlocProvider(
>             create: (context) => ProfileBloc(
>               profileUseCase: sl(),
>               authUseCase: sl(),
>               localization: sl(),
>             ),
>           ),
>         ],
>         home: const MainProfileScreen(),
>       );
>     });
> 
>     testWidgets('can render MainProfileScreen', (WidgetTester tester) async {
>        when(mockSharedPreferences.getString(any)).thenAnswer((_) => "hello");
> 
>       await tester.pumpWidget(app.widget);
>       await tester.pumpAndSettle();
> 
>       expect(find.byType(MainProfileScreen), findsOneWidget);
>     });
>   });
> 
>   tearDownAll(() {
>     /// clear di after finish test
>     sl.reset(dispose: true);
>   });
> }
> ```

@rrifafauzikomara
