### ISSUE TITLE
Failed assertion: line 372 pos 7: Object/factory with type NavigationService is not registered inside GetIt

### ISSUE THREAD

**Issue by alaindeseine** [fluttercommunity/get_it#315]
I currently upgrade a very old flutter application developped by another developper.

After upgading dependencies, correct null safety problems and correct gradle problems, i first build application.

But the application hang at startup with this error: 

> E/flutter ( 8836): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)]
> Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed
> assertion: line 372 pos 7: 'instanceFactory != null': Object/factory
> with  type NavigationService is not registered inside GetIt. 
> E/flutter ( 8836): (Did you accidentally do GetIt sl=GetIt.instance();
> instead of GetIt sl=GetIt.instance; E/flutter ( 8836): Did you forget
> to register it?) E/flutter ( 8836): #0     
> _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61) E/flutter ( 8836): #1      _AssertionError._throwNew
> (dart:core-patch/errors_patch.dart:40:5) E/flutter ( 8836): #2     
> _GetItImplementation._findFactoryByNameAndType (package:get_it/get_it_impl.dart:372:7) E/flutter ( 8836): #3     
> _GetItImplementation.get (package:get_it/get_it_impl.dart:393:29) E/flutter ( 8836): #4      _GetItImplementation.call
> (package:get_it/get_it_impl.dart:430:12) E/flutter ( 8836): #5     
> new MyOrganizationViewModel
> (package:politeia_france/ui/views/my_organizations/my_organizations_viewmodel.dart:14:55)
> E/flutter ( 8836): #6      GetItInjectableX.init
> (package:politeia_france/app/locator.config.dart:63:51) E/flutter (
> 8836): #7      setupLocator
> (package:politeia_france/app/locator.dart:16:17) E/flutter ( 8836): #8
> main (package:politeia_france/main.dart:29:9) E/flutter ( 8836): #9   
> _runMain.<anonymous closure> (dart:ui/hooks.dart:131:23) E/flutter ( 8836): #10     _delayEntrypointInvocation.<anonymous closure>
> (dart:isolate-patch/isolate_patch.dart:297:19) E/flutter ( 8836): #11 
> _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)

Problem is with getIt initialisation. GetIt is initalized with a generated dart file which is generated with `injectable_generator`. 

pubspec.yaml configuration: 

    dependencies:
      flutter:
        sdk: flutter
    ...

      get_it: ^7.2.0
      injectable: ^2.1.0
    ...

    dev_dependencies:
      flutter_test:
        sdk: flutter
    
      flutter_launcher_icons: ^0.12.0
      build_runner: ^2.3.3
      json_serializable: ^6.6.1
      auto_route_generator: ^5.0.3
      injectable_generator: ^2.1.2
      hive_generator: ^2.0.0
      ferry_generator: ^0.8.0+1

locator.dart: 

    import 'package:get_it/get_it.dart';
    import 'package:injectable/injectable.dart';
    import 'package:politeia_france/app/locator.config.dart';
    
    GetIt locator = GetIt.instance;
    
    @InjectableInit(preferRelativeImports: false)
    Future<void> setupLocator() async {
    
      await locator.init(
        environment: '',
        environmentFilter: null,
      );
    
    }

main.dart:

    void main() async {
      if (kReleaseMode) {
        debugPrint = (String? message, {int? wrapWidth}) {};
      }
    
      WidgetsFlutterBinding.ensureInitialized();
    
      SystemChrome.setSystemUIOverlayStyle(SystemUiOverlayStyle(
          statusBarColor: Colors.blue,
          statusBarBrightness: Brightness.dark,
          systemNavigationBarColor: Colors.blue));
    
      await setupLocator();
    
      debugPrint('>>>>>>>>>> Locator setup done');
    
      final AppService _appService = locator<AppService>();
    
      SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
          .then((_) async {
        debugPrint('>>>>>>>>>> Orientation fixed');
        await SentryFlutter.init(
          (options) {
            options.dsn =
                'https://456ac564d@o8974564.ingest.sentry.io/56987445';
          },
          appRunner: () {
            debugPrint('>>>>>>>>>> Sentry initialized');
            _appService.initApp();
            debugPrint('>>>>>>>>>> appService init done, run App');
            return runApp(MyApp());
          },
        );
      });
    }

Generated locator.config.dart: 

    // GENERATED CODE - DO NOT MODIFY BY HAND
    
    // **************************************************************************
    // InjectableConfigGenerator
    // **************************************************************************
    
    // ignore_for_file: no_leading_underscores_for_library_prefixes
    import 'package:get_it/get_it.dart' as _i1;
    import 'package:injectable/injectable.dart' as _i2;
    import 'package:politeia_france/services/api.dart' as _i3;
    import 'package:politeia_france/services/app.dart' as _i4;
    import 'package:politeia_france/services/my_organizations.dart' as _i7;
    import 'package:politeia_france/services/my_participations.dart' as _i9;
    import 'package:politeia_france/services/notifications_badges.dart' as _i10;
    import 'package:politeia_france/services/settings.dart' as _i20;
    import 'package:politeia_france/services/surveys.dart' as _i22;
    import 'package:politeia_france/services/text_to_speech.dart' as _i23;
    import 'package:politeia_france/services/third_party_services_modules.dart'
        as _i25;
    import 'package:politeia_france/ui/views/my_organizations/my_organizations_search_viewmodel.dart'
        as _i8;
    import 'package:politeia_france/ui/views/my_organizations/my_organizations_viewmodel.dart'
        as _i6;
    import 'package:politeia_france/ui/views/onboarding/onboarding_viewmodel.dart'
        as _i11;
    import 'package:politeia_france/ui/views/organisation/organization_alerts_viewmodel.dart'
        as _i12;
    import 'package:politeia_france/ui/views/participations/participations_viewmodel.dart'
        as _i14;
    import 'package:politeia_france/ui/views/posts/posts_viewmodel.dart' as _i13;
    import 'package:politeia_france/ui/views/questions/question_viewmodel.dart'
        as _i15;
    import 'package:politeia_france/ui/views/questions/questions_list_viewmodel.dart'
        as _i16;
    import 'package:politeia_france/ui/views/reports/report_create_viewmodel.dart'
        as _i17;
    import 'package:politeia_france/ui/views/reports/report_viewmodel.dart' as _i18;
    import 'package:politeia_france/ui/views/reports/reports_viewmodel.dart'
        as _i19;
    import 'package:politeia_france/ui/views/surveys/surveys_list_viewmodel.dart'
        as _i21;
    import 'package:politeia_france/ui/views/user/user_viewmodel.dart' as _i24;
    import 'package:stacked_services/stacked_services.dart'
        as _i5; // ignore_for_file: unnecessary_lambdas
    
    // ignore_for_file: lines_longer_than_80_chars
    extension GetItInjectableX on _i1.GetIt {
      // initializes the registration of main-scope dependencies inside of GetIt
      _i1.GetIt init({
        String? environment,
        _i2.EnvironmentFilter? environmentFilter,
      }) {
        final gh = _i2.GetItHelper(
          this,
          environment,
          environmentFilter,
        );
        final thirdPartyServicesModule = _$ThirdPartyServicesModule();
        gh.lazySingleton<_i3.Api>(() => _i3.Api());
        gh.lazySingleton<_i4.AppService>(() => _i4.AppService());
        gh.lazySingleton<_i5.DialogService>(
            () => thirdPartyServicesModule.dialogService);
        gh.singleton<_i6.MyOrganizationViewModel>(_i6.MyOrganizationViewModel());
        gh.lazySingleton<_i7.MyOrganizations>(() => _i7.MyOrganizations());
        gh.singleton<_i8.MyOrganizationsSearchViewModel>(
            _i8.MyOrganizationsSearchViewModel());
        gh.lazySingleton<_i9.MyParticipations>(() => _i9.MyParticipations());
        gh.lazySingleton<_i5.NavigationService>(
            () => thirdPartyServicesModule.navigationService);
        gh.lazySingleton<_i10.NotificationsBadges>(
            () => _i10.NotificationsBadges());
        gh.singleton<_i11.OnboardingViewModel>(_i11.OnboardingViewModel());
        gh.singleton<_i12.OrganizationAlertsViewModel>(
            _i12.OrganizationAlertsViewModel());
        gh.singleton<_i13.OrganizationWithPostsViewModel>(
            _i13.OrganizationWithPostsViewModel());
        gh.singleton<_i14.ParticipationsViewModel>(_i14.ParticipationsViewModel());
        gh.singleton<_i15.QuestionViewModel>(_i15.QuestionViewModel());
        gh.singleton<_i16.QuestionsListViewModel>(_i16.QuestionsListViewModel());
        gh.singleton<_i17.ReportCreateViewModel>(_i17.ReportCreateViewModel());
        gh.singleton<_i18.ReportViewModel>(_i18.ReportViewModel());
        gh.singleton<_i19.ReportsViewModel>(_i19.ReportsViewModel());
        gh.lazySingleton<_i20.Settings>(() => _i20.Settings());
        gh.lazySingleton<_i5.SnackbarService>(
            () => thirdPartyServicesModule.snackbarService);
        gh.singleton<_i21.SurveysListViewModel>(_i21.SurveysListViewModel());
        gh.lazySingleton<_i22.SurveysService>(() => _i22.SurveysService());
        gh.lazySingleton<_i23.TextToSpeech>(() => _i23.TextToSpeech());
        gh.singleton<_i24.UserViewModel>(_i24.UserViewModel());
        return this;
      }
    }
    
    class _$ThirdPartyServicesModule extends _i25.ThirdPartyServicesModule {
      @override
      _i5.NavigationService get navigationService => _i5.NavigationService();
      @override
      _i5.DialogService get dialogService => _i5.DialogService();
      @override
      _i5.SnackbarService get snackbarService => _i5.SnackbarService();
    }

I have found that if i deplace this line up:

    gh.lazySingleton<_i5.NavigationService>(
                () => thirdPartyServicesModule.navigationService);

the problem disappear but is replace with another error:

> Failed assertion: line 372 pos 7: 'instanceFactory != null':
> Object/factory with  type MyOrganizations is not registered inside
> GetIt

my_organizations_viewmodel.dart:

    @singleton
    class MyOrganizationViewModel extends StreamViewModel<List<Organization>> {
      final NavigationService _navigationService = locator<NavigationService>();
      final _organizationsService = locator<MyOrganizations>();
    ...

my_organizations.dart:

    @lazySingleton
    class MyOrganizations with ListenableServiceMixin {
      final _settingsService = locator<Settings>();
      final _apiService = locator<Api>();
    ...

I've been stuck on this problem for 2 days and I've looked at a considerable number of posts, without finding any solutions.

Any idea is welcome.

**Comment by hussenIbrahim** [comment]
Check your imports
Dart Analyzer  is not sensitive for imported files name cases
in my case I imported "./Categories"  instead  of "./categories"

**Comment by lamgiahung112** [comment]
**PROBLEM SOLVED**

I changed my dependency_injection.dart file name in to di.dart and it just works. 
I still don't know why it works tho. It would be great if anyone could give some information about it!

**Comment by escamoteur** [comment]
@alaindeseine did you solve your problem?

**Comment by alaindeseine** [comment]
Yes, i just throw away GET_it from this project.

**Comment by escamoteur** [comment]
What a pity :-) it's a very helpful package but I'm not a fan of injectable
