### ISSUE TITLE
get.to does not work after returning from a page with a dialog inside

### ISSUE THREAD

**Issue by almog228** [fluttercommunity/get_it#317]
Hello, when I route from the default dialog home screen, which is my selection screen to which page I want to navigate. When I perform get.to.... I can back from the screen and access it back from the defualt dialog but when on the target screen I open a new dialog and I perform get.back it does not let me open any get.to from the dialog I returned to on the main screen. Hope it was understood.
Does anyone know the problem?

** With Navigator.push(
    context,
    MaterialPageRoute...... is Work

**Comment by escamoteur** [comment]
you are probably in the wrong repository. this isn't getx, this is get_it
