### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by rrifafauzikomara** [fluttercommunity/get_it#321]
When I create a unit test for a class that needs a context and is also injected by get_it, I got this error.

```
test/main_test.dart 13:71               main.<fn>.<fn>
package:get_it/get_it_impl.dart 178:41  _ServiceFactory.getObject
package:get_it/get_it_impl.dart 434:34  _GetItImplementation.get
package:get_it/get_it_impl.dart 455:12  _GetItImplementation.call
test/main_test.dart 14:23               main.<fn>

Null check operator used on a null value
```

Here's the example project for the above error: https://github.com/rrifafauzikomara/flutter_sdk_example/blob/main/test/main_test.dart

**Comment by escamoteur** [comment]
Will have a closer look tomorrow. I checked the place of the exception and it's almost impossible, but I have to clone your project and see it myself

**Comment by escamoteur** [comment]
Actually the exception doesn't come from get_it.

![image](https://user-images.githubusercontent.com/16635729/236687089-ec57e72a-8e0a-4414-bab1-6223fad45f19.png)

your `currentContext` is null in your factory function. 
if you enable break in all exceptions you would have found it
