### ISSUE TITLE
Dart 3: InitDependency should not extend Type

### ISSUE THREAD

**Issue by sunderee** [fluttercommunity/get_it#324]
Going through the source code of `get_it`, I saw the following:

```dart
class InitDependency extends Type {}
```

If you were to bump the Dart SDK version constraint to the latest stable version of Dart, which is 3.0, the linter should warn you of the following: `The class 'Type' can't be extended outside of its library because it's an interface class.`, which is true because `Type` is defined as an `abstract interface class`.

Of course, you can just ignore the [`invalid_use_of_type_outside_library ` rule itself](https://dart.dev/diagnostics/invalid_use_of_type_outside_library), but I think it might be a good idea to migrate sometime in the future. I'm really not sure if this would work, but what about implementing `Type` instead? I don't have a deep insider knowledge of the library itself, so I could be completely wrong about that.

**Comment by escamoteur** [comment]
are you using any linter package? just bumping the SDK version didn't show me this lint.

**Comment by escamoteur** [comment]
fixed it it now implements Type
