### ISSUE TITLE
readyFuture does not complete if signalReady() is called first

### ISSUE THREAD

**Issue by Lootwig** [fluttercommunity/get_it#33]
Just wanted to check if this is a known issue, if not, I'll happily try to recreate the problem in a small example (I'm only observing the issue with a slightly more complex initialization routine just now).

**Comment by escamoteur** [comment]
I think I know why. I have to change some things

**Comment by escamoteur** [comment]
Hi, I'm just doing an overhaul of the initialization helper of GetIt.
It would be great if you could have a look at my current API proposal and give me Feedback 
https://gist.github.com/c4c717518729a4c24a4ce95c10111473

**Comment by escamoteur** [comment]
Should be fixed with https://github.com/fluttercommunity/get_it/issues/46
