### ISSUE TITLE
The license page is wrong with certain fonts.

### ISSUE THREAD

**Issue by nobushiueshi** [fluttercommunity/get_it#336]
When I set up the NotoSansJp font and look at the "get_it" license page, I see mysterious characters.

The reason is that the newline code in the LICENSE file is CRLF.

> I changed the line feed code to LF and it cured it.

[Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto+Sans+JP)

<img src="https://github.com/fluttercommunity/get_it/assets/26820149/a47ca791-bf2d-4c5e-92db-348430dd7e38" width="50%">

**Comment by escamoteur** [comment]
sorry, but that is hardly a problem with the package if you use a font that has problems with this.

**Comment by nobushiueshi** [comment]
@escamoteur 
The problem is that the newline code in the license file is "CRLF". Please change the newline code to "LF".

**Comment by escamoteur** [comment]
If it's so important, make PR and fix it please.
It's really not my responsibility that your font has problems with it
Am 25. Aug. 2023, 20:29 +0200 schrieb nobushiueshi ***@***.***>:
