### ISSUE TITLE
Make a lazy `registerSingletonWithDependencies`

### ISSUE THREAD

**Issue by feinstein** [fluttercommunity/get_it#338]
If we have a Singleton that depends on another Singleton that has an `async` initialization, then we can't use lazy singletons, which leads to memory leaks.

**Comment by escamoteur** [comment]
Can you explain to me how a lazy singleton would help you in this aspect?
I'm pretty sure there are better ways to achieve the same?
Did you have a closer look at get_it scopes?

**Comment by feinstein** [comment]
If we declare Singletons they will be create as soon as they are declared and will live in memory. Scopes allow us to reduce their foot print, but then we have to be controlling scopes all over the app. I don't want to use scopes for several reasons:

1 - I have a `Storage` class that's used in many screens and flows in my app, but not in all of them. The ones who use it, I want them to have the same Singleton with the same internal cache. It's ok if it's created once by one screen and it lives there in memory, but I don't want to be micromanaging scopes the app.

2 - The less coupling my app has on third party libraries, the better. No offense, get_it is very useful, but I rather "contain" how much it influences my app in case I need to replace it one day. I declare the dependencies when the app starts and I make all the singletons and factories call each other. then I create the objects I want on a given page. This way I only have get_it in 2 places: App Initialization and Pages initialization.

**Comment by feinstein** [comment]
>unless they cache images or other huge Data blocks.

So you agree with me that that are cases where Singletons can bloat your app's memory, so why not make the lib ready to provide to us the tools to control the memory in any way we want?

**Comment by escamoteur** [comment]
See our other discussion
