### ISSUE TITLE
Avoid dispose singleton

### ISSUE THREAD

**Issue by antonino-tocco** [fluttercommunity/get_it#34]
Hi, I need help with an issue.
I observed that when the app go to background the Singleton are disposed.
It is possibile to avoid dispose singleton on app background?

Thanks in advance

**Comment by escamoteur** [comment]
I guess you talk about sending the app in to the background by using the backbutton on Android?
I just spoke to one of the flutter team and he said there is no guarantee that the activity is not destroyed in that case, so you have to expect that no data is preserved.
So you have to save any state that you need later.

**Comment by antonino-tocco** [comment]
No, I'm talking about sending app in the background with home button in android not back button.
With the back button the activity is destroyed

**Comment by escamoteur** [comment]
hmm, I test again

**Comment by escamoteur** [comment]
just tried it with the sample app of GetIt and it does not get disposed, but I know that Android can kill theactivity there too if memory gets low

**Comment by escamoteur** [comment]
Try it yourself, I just pushed the latest version to github.

In general you app has to expect that it get's killed by Android
