### ISSUE TITLE
`registerLazySingletonAsync` not working with `dependsOn`

### ISSUE THREAD

**Issue by feinstein** [fluttercommunity/get_it#341]
I have been trying for countless hours understand why my objects weren't being created, it turns out I had marked a class on `dependsOn` that was being created by a `registerLazySingletonAsync`. Removing the `dependsOn` or changing the `registerLazySingletonAsync` to a `registerSingletonAsync` fixed it. So I believe `registerLazySingletonAsync` aren't working with the `dependsOn` dependency resolution, as this factory is never triggered.

**Comment by escamoteur** [comment]
yep, that is indeed the behavior as intended. asyncLazySingletngs are not included in the dependson feature

**Comment by feinstein** [comment]
This should at least be documented. How could I know that some ways of registering a dependency will be a part of the dependency tree check, while others will be ignored?

**Comment by escamoteur** [comment]
I am not 100% sure that it's nothing stated. I think of you call already() you should get a warning but I can strengthen that point 8n the docs.
Am 20. Aug. 2023, 14:06 +0200 schrieb Michel Feinstein ***@***.***>:
