### ISSUE TITLE
unlisted from pub.dev? 

### ISSUE THREAD

**Issue by xmany** [fluttercommunity/get_it#344]
`UNKNOWN PLATFORMS` from [pub.dev](https://pub.dev/packages/get_it)

Can't find the package unless you specifically search for `get_it`

<img width="420" alt="image" src="https://github.com/fluttercommunity/get_it/assets/57887009/66683e14-2156-43f2-8d8a-d057ccba3eee">

**Comment by escamoteur** [comment]
Hey, thanks for telling, I though I had only unlisted the faulty version.
Look into it when I m back
Am 4. Sept. 2023, 12:37 +0200 schrieb Jimmy Yang ***@***.***>:

**Comment by xmany** [comment]
sorry, it turned out that the reason for not being able to resolve the package, is because an issue with vscode...

**Comment by escamoteur** [comment]
But there is also something wrong, it's not listed if you don't search for it
Am 4. Sept. 2023, 12:43 +0200 schrieb Jimmy Yang ***@***.***>:

**Comment by escamoteur** [comment]
I pushed a new version, now its listed fine again
