### ISSUE TITLE
Bad state: GetIt: Object/factory with type AdviceRepoImpl is not registered inside GetIt.

### ISSUE THREAD

**Issue by guns28** [fluttercommunity/get_it#347]
i'm having this issue and no idea from where it's coming : 

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building KeyedSubtree-[GlobalKey#aafbc]:
Bad state: GetIt: Object/factory with type AdviceRepoImpl is not registered inside GetIt.
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)

```dart
`final sl = GetIt.I;

/// sl is service Locator

Future<void> init() async {
  /// Application layer
  /// Factory = every time a new instance of that class
  sl.registerFactory(() => AdviceCubit(adviceUseCase: sl()));

  /// sl() will look for the registered param

  ///domain layer
  sl.registerFactory(() => AdviceUseCase(adviceRepo: sl()));

  /// data layer
  sl.registerFactory<AdviceRepo>(
      () => AdviceRepoImpl(adviceRemoteDataSource: sl()));

  sl.registerFactory<AdviceRemoteDataSource>(
      () => AdviceRemoteDataSourceImpl(client: sl()));

  /// extern
  sl.registerFactory(() => Client());
}
```
`
flutter doctor : 

[✓] Flutter (Channel master, 3.13.0-16.0.pre.7, on macOS 14.0 23A344 darwin-x64, locale fr)
    • Flutter version 3.13.0-16.0.pre.7 on channel master at /Users/macbook/Downloads/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision de5b9670dd (3 months ago), 2023-08-01 09:18:27 -0400
    • Engine revision f1c80ce984
    • Dart version 3.2.0 (build 3.2.0-19.0.dev)
    • DevTools version 2.25.0

any help

**Comment by escamoteur** [comment]
if the error is `missing AdviceRepoImpl ` that means you tried to access it via sl<AdviceRepoImpl> which can't work as you have registered `AdviceRepoImpl ` with it's base type `AdviceRepo` so you have to use that when accessing the factory
