### ISSUE TITLE
Check implementation of `WillSignalReady` on subclasses

### ISSUE THREAD

**Issue by tpucci** [fluttercommunity/get_it#348]
Hi there !

It seems that if `WillSignalReady` is implemented by a subclass, `get_it` do not expect it to signals its readiness.

**Example**
```dart
abstract class A {}

class B implements A, WillSignalReady {}

void main() async {
	di.registerSingleton<A>(B())
	await di.allReady() // does not wait for B to be ready
}
```

**Comment by escamoteur** [comment]
Sorry for the late response. `SignalReady` has to be on the type that you register, not only on the one implementing it.
