### ISSUE TITLE
Collections Multibinding

### ISSUE THREAD

**Issue by vscmaster** [fluttercommunity/get_it#349]
Hi get_it team,

I have a proposition to extend injection with the same type into collection.

I many years been using such approach with  [Dager multibinding](https://dagger.dev/dev-guide/multibindings) and it very convenient way to support dynamic typed behaviours and abstract factories. Like parsers, creators, decorator, etc.

Thank you.

**Comment by escamoteur** [comment]
Hi,

can you elaborate on how this should work?
Am 16. Nov. 2023, 20:57 +0100 schrieb vscmaster ***@***.***>:

**Comment by vscmaster** [comment]
> Hi, can you elaborate on how this should work? Am 16. Nov. 2023, 20:57 +0100 schrieb vscmaster ***@***.***>:
> […](#)
> Hi get_it team, I have a proposition to extend injection with the same type into collection. I many years been using such approach with Dager multibinding and it very convenient way to support dynamic typed behaviours and abstract factories. Like parsers, creators, decorator, etc. Thank you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Sure, lets think about some interface, I'll call it `DeepLink` and several impls, HomeDeepLink, CatalogDeepLink, DetailsDeepLink, etc.

and with the GetIt we will register them(even with the scope also).  `GetIt.registerInToSet<DeepLink>(HomeDeepLink())`

then we'll call it like this `GetIt.getSet<DeepLink>()`, this will return the `Set<DeepLink>`.

**Comment by escamoteur** [comment]
I guess that is the same as this issue here? https://github.com/fluttercommunity/get_it/issues/75

**Comment by escamoteur** [comment]
@vscmaster haven't heard from you?
