### ISSUE TITLE
Questions about the registerFactory

### ISSUE THREAD

**Issue by NicosNicolaou16** [fluttercommunity/get_it#351]
Hello,

I have two questions about the registerFactory. According to documentation the registerFactory creates every time a new instance when it calls.

1) Does registerFactory is singleton as well?

2) Does the previous registerFactory instance destroy when create a new one or keep the previous and the new instance as well?

**Comment by escamoteur** [comment]
The Factory isn't  Singleton, as it will create a new instance of the type it is registered with.
What happens afterwards with the new instance is not further controlled by get_it
Am 12. Dez. 2023, 19:39 +0100 schrieb Nicos Nicolaou ***@***.***>:

**Comment by NicosNicolaou16** [comment]
Thank you for your answer! 🙏😀
