### ISSUE TITLE
Object of type X is not registered inside GetIt

### ISSUE THREAD

**Issue by MatheusHoudin** [fluttercommunity/get_it#36]
Trying to create objects with get_it, although all the necessary objects are being registered as factories or lazy singletons, the library keeps saying that those objects are not registered.

final sl = GetIt.instance;

Future<void> init() async {

  sl.registerFactory(() => MoviesBloc(getMoviesWithPageUsecase: sl()));

  sl.registerSingleton(() => GetMoviesWithPageUsecase(sl()));

  sl.registerLazySingleton<MoviesRepository>(
    () => MoviesRepositoryImpl(
      moviesLocalDataSource: sl(),
      moviesRemoteDataSource: sl(),
      networkInfo: sl()
    )
  );

  sl.registerLazySingleton<MoviesRemoteDataSource>(
    () => MoviesRemoteDataSourceImpl(client: sl())
  );
  sl.registerLazySingleton<MoviesLocalDataSource>(
    () => MoviesLocalDataSourceImpl(moviesBox: sl('moviesBox'))
  );

  sl.registerLazySingleton<NetworkInfo>(
    () => NetworkInfoImpl(sl())
  );

  final appDocumentDirectory = await path_provider.getApplicationDocumentsDirectory();
  Hive.init(appDocumentDirectory.path);
  final moviesBox = await Hive.openBox('movies');
  sl.registerLazySingleton(() => http.Client());
  sl.registerLazySingleton(() => DataConnectionChecker());
  sl.registerLazySingleton(() => moviesBox,instanceName: 'moviesBox');
}

I call this method inside the main method and when I try to retrieve some object i always get the same error, example:
Invalid argument (Object of type GetMoviesWithPageUsecase is not registered inside GetIt):

**Comment by LeonanFragaLeonardo** [comment]
I have the same problem
Can you provide more information on how you solved your problem?

**Comment by mghase** [comment]
i have the same issue any solution if any

**Comment by derrickxiang** [comment]
same issue here, any solution?

**Comment by david-legend** [comment]
My project came to a standstill sake of this issue. what I did was I changed the version from get_it: ^4.0.2 to get_it: ^3.1.0 and it worked like a charm. I totally do not get why this was happening

**Comment by david-legend** [comment]
it turns out the version change didn't work

**Comment by escamoteur** [comment]
Can all that have the same problem raise a new issue with source code where you register and where you access your type?
Also check if you are on the latest version. 
Even better would be a small example project where this happens because I can't reproduce it

**Comment by bvdwalt** [comment]
Hi @escamoteur, I'll open up another issue and link my github repo with my Flutter code, which is getting this error. You can then try and run the app in my repo and see if you can manage to reproduce it.

**Comment by yanivshaked** [comment]
I have the same issue. Using get_it from the operational flow works, but all initialization done from the test environment are lost when you invoke the application. @escamoteur Please let me know if you still need a small example project, I can prepare it ASAP.

**Comment by hmanenga** [comment]
I have the same issue

**Comment by escamoteur** [comment]
all that have problems Please open a new issue with the code where you register and where you use your Objects as well as the error code.
If possible put a little repro project on Github
