### ISSUE TITLE
trying to upgarde the package to 7.6.9

### ISSUE THREAD

**Issue by Moatasem159** [fluttercommunity/get_it#362]
I'm trying to upgrade to 7.6.9 version and i get this error

**Because notes depends on get_it ^7.6.9 which doesn't match any versions, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on get_it: flutter pub add get_it:^7.6.8** 

my flutter doctor

**[√] Flutter (Channel stable, 3.19.5, on Microsoft Windows [Version 10.0.19045.4291], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.2)
[√] Android Studio (version 2023.2)                                           
[√] VS Code (version 1.87.2)
[√] Connected device (3 available)
[√] Network resources**

**Comment by escamoteur** [comment]
From the message it seems that the notes package is the problem because it is fixed on an earlier get_it version.
Am 13. Apr. 2024, 12:44 +0200 schrieb Moatasem Mohamed ***@***.***>:

**Comment by Moatasem159** [comment]
i tried to delete pubspec.lock , flutter clean and pub get same error happened. and when i tried to add it with command 
 **$ flutter pub add get_it** it get 7.6.8 version , it happen also when upgrade image_picker and path_provider.

**Comment by escamoteur** [comment]
Can you please post the full error message you get?
Am 13. Apr. 2024, 13:47 +0200 schrieb Moatasem Mohamed ***@***.***>:

**Comment by Moatasem159** [comment]
Because notes depends on get_it ^7.6.9 which doesn't match any versions, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on get_it: flutter pub add get_it:^7.6.8

**Comment by escamoteur** [comment]
Is 'notes' the name of your app? This error doesn't really make any sense because the version on pub is 7.6.9, so I don't really know why you get this error.
Am 13. Apr. 2024, 13:52 +0200 schrieb Moatasem Mohamed ***@***.***>:

**Comment by Moatasem159** [comment]
yes 'notes' is the name of the app , i tried to add it to new project does not have it and same error happened

**Comment by escamoteur** [comment]
Please file an issue on the Flutter repository on this telling that despite a package version exists on pub the Flutter tools say the version does not exist.
The changes of the last version are not significant for most people so you can just stick with the last version without a problem.
Am 13. Apr. 2024, 14:02 +0200 schrieb Moatasem Mohamed ***@***.***>:

**Comment by Moatasem159** [comment]
I add issue to flutter repository thank you for helping

**Comment by escamoteur** [comment]
Closing as this seems not to be rooted in get_it
