### ISSUE TITLE
[feature request] `registerCachedInstance`?

### ISSUE THREAD

**Issue by y-nk** [fluttercommunity/get_it#367]
I would like to have the lazy singleton instance to be retained as long as its used, but destroyed when it's no longer in use. I know it sounds like a factory, **but hear me out**.

The project I work on currently is implementing the Clean Architecture, where repositories are registered as factories and requested the use-case classes. We write something such as:

```dart
class Repo {
  String getFoo() => "foo";
}

GetIt.instance.registerFactory(() => Repo());

class UseCase1 {
  String call() => GetIt.instance.get<Repo>().getFoo();
}

class UseCase2 {
  String call() => GetIt.instance.get<Repo>().getFoo();
}

class UseCase3 {
  String call() => GetIt.instance.get<Repo>().getFoo();
}

GetIt.instance.registerFactory(() => UseCase1());
GetIt.instance.registerFactory(() => UseCase2());
GetIt.instance.registerFactory(() => UseCase3());

class MyBloc {
  UseCase1 usecase1 = GetIt.instance()
  UseCase2 usecase2 = GetIt.instance()
  UseCase3 usecase3 = GetIt.instance()
}
```

When doing ↑, repositories get instantiated quite too often (everytime `UsecaseX.call` get called) so it's not ideal.

```dart
class Repo {
  String getFoo() => "foo";
}

GetIt.instance.registerFactory(() => Repo());

class UseCase1 {
  Repo repo = GetIt.instance()
  String call() => this.repo.getFoo();
}

class UseCase2 {
  Repo repo = GetIt.instance()
  String call() => this.repo.getFoo();
}

class UseCase3 {
  Repo repo = GetIt.instance()
  String call() => this.repo.getFoo();
}

GetIt.instance.registerFactory(() => UseCase1());
GetIt.instance.registerFactory(() => UseCase2());
GetIt.instance.registerFactory(() => UseCase3());

class MyBloc {
  UseCase1 usecase1 = GetIt.instance()
  UseCase2 usecase2 = GetIt.instance()
  UseCase3 usecase3 = GetIt.instance()
}
```

We can try to make it better. When doing ↑, repositories get created less often but still there's one instance per Usecase instances, so still not ideal.

```dart
class Repo {
  String getFoo() => "foo";
}

GetIt.instance.registerLazySingleton(() => Repo());

class UseCase1 {
  String call() => GetIt.instance.get<Repo>().getFoo();
}

class UseCase2 {
  String call() => GetIt.instance.get<Repo>().getFoo();
}

class UseCase3 {
  String call() => GetIt.instance.get<Repo>().getFoo();
}

GetIt.instance.registerFactory(() => UseCase1());
GetIt.instance.registerFactory(() => UseCase2());
GetIt.instance.registerFactory(() => UseCase3());

class MyBloc {
  UseCase1 usecase1 = GetIt.instance()
  UseCase2 usecase2 = GetIt.instance()
  UseCase3 usecase3 = GetIt.instance()
}
```

When doing ↑, repo instance remains in memory forever, so it's currently the best **but** it clutters the memory _forever_, so it's even better... but still not there _100%_.

What I would like to have is a **Cached Instance** which could be very similar to `registerLazySingleton` but the reference to the instance would be retained in a WeakReference in GetIt, so that it is a singleton as long as it is used somewhere, but as soon as every user-land reference is gone, it would turn to `null` and be garbage collected.

---

We currently are experimenting wrapping our `UseCase` class with a Finalizer, so that we can call manually `resetLazySingleton()` which would have the same effect. What i'm proposing/requesting is that it became a feature of the library 🙏

Thank you for your time reading this

**Comment by y-nk** [comment]
Another possibility, as I just thought of it would be for factory instances to be able to implement the same `Disposable` interface like singletons and scopes.

**Comment by escamoteur** [comment]
Why the hell are you even try to do that?
Clean architecture is not really a good pattern especially for apps but why use instatiate objects for every call again? There are way better ways to achieve what you want.
Am 18. Juli 2024, 06:59 +0100 schrieb Julien Barbay ***@***.***>:

**Comment by y-nk** [comment]
@escamoteur haha thanks for the frank answer :)

to give some context, i've landed into a codebase which is already too far into the clean architecture to remove it... _and also_ uses get-it _sometimes_. i've been around coding a few decades now, and i've seen some level of spaghettiness but to this level... so overall i agree that clean architecture is not really a good pattern, especially for apps ; but i just can't `rm -fr` it all and restart from scratch (even if somehow, i'd love to).

now for "why the hell are you even trying to do that" → because i dont have the luxury to rewrite it all. it is the way it is and it is sad to say that the business won't allow this level of rewrite. i have to find some level of compromise. i had been thinking a lot how to do this without implying modifying get-it, and most attempts are not that elegant tbh. then i realized that maybe, since there are lazy singletons, there could be a space where cached instances would be useful too.

**Comment by escamoteur** [comment]
Hi Julien,

ok, I can understand that but I probably would try to refactor it at least partwise.
I mean keeping the layers. But the constant recreation of factories seems totally stupid.
I will today have another look at what you need
Am 30. Juli 2024, 11:18 +0100 schrieb Julien Barbay ***@***.***>:

**Comment by escamoteur** [comment]
I think I have now understood what you need, I think this might be actually a nice addition. using a weak reference should be possible because I can check if it is still valid

**Comment by escamoteur** [comment]
wondering if it makes more sense to really add a registerCachedFactory or giving the lazySingelton  `weakReference` optional parameter. Probably better to add it to the `lazySingleton` because a factory is defined in that it should really create new instances on every call

**Comment by escamoteur** [comment]
The latest prerelease on pub offers now an optional Flag for `registerLazySingleton` but see

https://github.com/dart-lang/sdk/issues/56432

Maybe you can give it a try to see if that behaves differently if multiple objects are used this way

**Comment by y-nk** [comment]
@escamoteur this is amazing! thank you

**Comment by escamoteur** [comment]
I m on solving the problem. Will finish this afternoon
Am 12. Aug. 2024, 10:54 +0100 schrieb Julien Barbay ***@***.***>:

**Comment by escamoteur** [comment]
please test 8.0.0-pre-7 it has an optional parameter for LazySingleton as well as a unch of new `registerCachedFactory` functions that still need tests, so in case you want to help adding these that would be helpful

**Comment by escamoteur** [comment]
one more question, why don't you just register all factories inside get_it?

**Comment by y-nk** [comment]
@escamoteur we thought about it, which is best for memory. but we end up with a bunch of duplicated instances at runtime for a given page.

I've edited my original post, so you could see better on the issues this would be.

1st case, if everything is registered as a factory we end up creating a new Repository for every usecase call. we have one instance in memory at a single time but memory works a lot (spawn/kill) everytime a usecase is called.

2nd case, there's an attempt at holding the repository instances in the usecases, but they are duplicated (there's one instance per usecase, so the memory is bloated by 
"instances - 1").

**Comment by y-nk** [comment]
i will test today.

**Comment by escamoteur** [comment]
does it do what you need?

**Comment by escamoteur** [comment]
have you tested it?

**Comment by y-nk** [comment]
@escamoteur it is working as intended indeed. easy to use and after adding a bunch of print at key points, we can see that it's behaving as expected (at least on simulators) 🙏
