### ISSUE TITLE
registerCachedFactoryParam asserts no params are passed

### ISSUE THREAD

**Issue by franco-conroo** [fluttercommunity/get_it#382]
The registerCachedFactoryParam function implies that params can be passed. Equivalent to registerFactoryParam. This case is not checked in the implementation of getObject in the get_it_impl file.

```dart
assert(
      !(factoryType != _ServiceFactoryType.alwaysNew &&
          (param1 != null || param2 != null)),
      'You can only pass parameters to factories!',
    );
```

I think the assertion should be done on a case by case bases depending on the _ServiceFactoryType.

**Comment by escamoteur** [comment]
agreed, this check needs the addition of `cachedFactory` in the assert. Could you make a PR including a test?
