### ISSUE TITLE
popScopesTill broken in version 8

### ISSUE THREAD

**Issue by kuhnroyal** [fluttercommunity/get_it#384]
Hello @escamoteur

The changes in commit 7d2d4bb7d403b39af631f04e2e0dbb8419646f39 lead to `popScopeTill(inclusive: true)` always popping all scopes until the base scope. The while loop exit condition does not trigger when `inclusive == true`.

**Comment by kuhnroyal** [comment]
I added tests in https://github.com/fluttercommunity/get_it/pull/385 for now

**Comment by escamoteur** [comment]
Could you determine where the problem is?
Am 23. Okt. 2024, 16:09 +0100 schrieb Peter Leibiger ***@***.***>:

**Comment by kuhnroyal** [comment]
Yea, I think I fixed it.

```dart
while (hasScope(scopeName) && inclusive
        ? (poppedScopeName != scopeName)
        : (nextScopeToPop.name != scopeName))
```
This lead to the else branch running even if `hasScope` returned false.

Additionally I found a secondary problem if the passed scopeName is the top scope and `inclusive == false` which would always have popped the first scope because of the used `do() while` loop.

Changes are on the same PR.

**Comment by kuhnroyal** [comment]
Fixed by #385

**Comment by kuhnroyal** [comment]
@escamoteur Can you please cut a release when you get a chance, thanks!

**Comment by escamoteur** [comment]
done
Nachricht von ***@***.*** am Oct 28, 2024, 1:30 PM +0100:

**Comment by kuhnroyal** [comment]
Thanks a lot!
