### ISSUE TITLE
Hidden bug on allReady

### ISSUE THREAD

**Issue by JCKodel** [fluttercommunity/get_it#389]
Dart is so freaking useless when come to generics, geez >.<

Once, I've created a `FutureBuilder<void>` to wait for `get_it` to be ready.

Since `allReady` is a `Future<void>`, I passed the result of `allReady` to `FutureBuilder<boid>`, as this:

```dart
late final Future<void> _allReady;

@override
void initState() {
  ...
  _allReady = GetIt.I.allReady();
  ...
}

@override
Widget build(BuildContext context) {
  return FutureBuilder<void>(
    future: _allReady,
    ...
}
```

Why? Because `FutureBuilder` should be fed completed (or to be completed) futures, so it won't execute the future again for each build.

But, as Dart crappy typing system allows, `Future<void>` is not really `void`. It can be anything (and it really doesn't even care if it is even `Future`, no complaints, no warnings, no exceptions thrown.

Since `get_it` returns a `FutureGroup` (not a `FutureGroup<void>`), which, for Dart, is valid

![image](https://github.com/user-attachments/assets/2bb5fd23-7aa0-4227-ad28-abb0696546d4)

my `Future<void> _allReady` becomes a `FutureGroup _allReady`.

And guess what, `wait FutureGroup()` returns? Not what you intended. =(

The bug in this case is: this code will wait ONLY for the first async singleton registered in `get_it`, not all of them.

Tip: use these rules on `analysis_options.yml` to mark this kind of generics weaknesses as warnings (and, of course, don't ignore warnings):

```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

1) Since the intention of `allReady` is to wait for ALL async registrations to be ready, the correct would be to await the futures and then return void.

Lines 1909 and 1912 should be `await futures.future`. Yes. Dart will say that this is bad code (https://dart.dev/tools/linter-rules/unnecessary_await_in_return), but IT IS NOT. Without awaiting local scope futures you a) hit the Dart's weak generic mess and b) you no longer throw exceptions within this scope (exceptions will be thrown outside of it, by the caller. And the caller can be sync. Guess what happens then?).

**Comment by escamoteur** [comment]
Wow, really? I'm not sure if I introduced this a while back when doing some cleanup there.
I really thought the allReady would be working.
Thanks for figuring out the problem
Am 5. Nov. 2024, 04:22 +0100 schrieb J.C.Ködel ***@***.***>:

**Comment by escamoteur** [comment]
hmmm, I just extended one of the test for allReady like this (also pushed to github) and it doesn't show anything like this

```dart
  test('ready automatic signalling for async Singletons', () async {
    try {
      final getIt = GetIt.instance;
      await getIt.reset();

      getIt.registerSingletonAsync<TestClass>(
        () async => TestClass(internalCompletion: false).init(),
      );
      getIt.registerSingletonAsync<TestClass2>(
        () async {
          final instance =
              TestClass2(internalCompletion: false, initMsDelay: 50);
          await instance.init();
          return instance;
        },
      );
      getIt.registerSingletonAsync<TestClass>(
        () async => TestClass2(internalCompletion: false).init(),
        instanceName: 'Second Instance',
      );

      expect(getIt.isReadySync<TestClass>(), false);
      expect(getIt.isReadySync<TestClass2>(), false);
      expect(
          getIt.isReadySync<TestClass>(instanceName: 'Second Instance'), false);

      await getIt.allReady();

      expect(getIt.isReadySync<TestClass>(), true);
      expect(getIt.isReadySync<TestClass2>(), true);
      expect(
          getIt.isReadySync<TestClass>(instanceName: 'Second Instance'), true);
    } on Exception catch (e) {
      print(e);
    }
  });
```

**Comment by JCKodel** [comment]
I'm not able to reproduce the issue in a brand-new code, and the code that had the problem was thrown away some time ago. Guess I made something wrong and did not realize that =\
