### ISSUE TITLE
registerLazySingleton unexpected behavior

### ISSUE THREAD

**Issue by computervirus91** [fluttercommunity/get_it#39]
This does NOT WORK,
GetIt.I.registerLazySingleton<Injector>(() => SingletonInjector.configuration(RepoType.PROD));

ERROR,
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown building Builder(dirty):
Invalid argument (Object of type Injector is not registered inside GetIt.
Did you forget to pass an instance name?
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;)): Instance
of '_Type'

But this WORKS,
Injector inj = SingletonInjector.configuration(RepoType.PROD);
GetIt.I.registerLazySingleton<Injector>(() => inj);

**Comment by escamoteur** [comment]
Which version are you using?

**Comment by computervirus91** [comment]
> Which version are you using?

get_it: 3.1.0

**Comment by escamoteur** [comment]
This is definitively strange. I have a closer look

**Comment by escamoteur** [comment]
It works for me see my Test Code:

```Dart
  test('register LazySingleton with lambda and factory function', () {
    GetIt.I.registerLazySingleton(() => SingletonInjector.configuration());

    final instance = GetIt.I<Injector>();

    expect(instance, TypeMatcher<Injector>());
  });
}

class SingletonInjector {
  static Injector configuration() {
    return Injector();
  }
}

class Injector {}
``` 
I would have to see the code for your injector and SinglettonInjector.

Overall I want to add, you should always provide a type or a name when registering something, you didn't either. it only worked because of type inference.
My guess would be that `configuration`does not have a return type declared.

**Comment by escamoteur** [comment]
Please also test the latest beta https://github.com/fluttercommunity/get_it/issues/46

**Comment by computervirus91** [comment]
########################################################################
// injector_interface.dart
----------------------------

enum RepoType {
  MOCK,
  PROD,
}

abstract class Injector{
  //getter and setter
  LocationTracker get locationTracker;
  Repository get repo;

  //method
  void configureInjector(RepoType repoType);

  void dispose();
}
#######################################################################
//singleton_injector.dart
---------------------------


class SingletonInjector implements Injector {
  //class property
  static final SingletonInjector _singleton = SingletonInjector._internal();
  static RepoType _repoType;

  //getter and setter

  //class constructor
  factory SingletonInjector.configuration(RepoType repoType) {
    _configure(repoType);
    return _singleton;
  }

  SingletonInjector._internal();

  //class methods
  static void _initRepo() {
    //repository
    switch (_repoType) {
      case RepoType.MOCK:
        GetIt.I.registerLazySingleton<Repository>(() => RepoPROD());
        break;
      default:
        GetIt.I.registerLazySingleton<Repository>(() => RepoPROD());
    }

    //location tracker
  }

  //configure injector methods
  @override
  void configureInjector(RepoType repoType) {
    _configure(repoType);
  }

  //config wrapper
  static void _configure(RepoType repoType) {
    print("_configure from injector");
    GetIt.I.reset();
    _repoType = repoType;
    _initRepo();
    kIsWeb ? _configureForWeb() : _configureForMobile();
  }

  @override
  void dispose() {
    repo.cloudDB.dispose();
    GetIt.I.reset();
  }
}

**Comment by computervirus91** [comment]
> It works for me see my Test Code:
> 
> ```dart
>   test('register LazySingleton with lambda and factory function', () {
>     GetIt.I.registerLazySingleton(() => SingletonInjector.configuration());
> 
>     final instance = GetIt.I<Injector>();
> 
>     expect(instance, TypeMatcher<Injector>());
>   });
> }
> 
> class SingletonInjector {
>   static Injector configuration() {
>     return Injector();
>   }
> }
> 
> class Injector {}
> ```
> 
> I would have to see the code for your injector and SinglettonInjector.
> 
> Overall I want to add, you should always provide a type or a name when registering something, you didn't either. it only worked because of type inference.
> My guess would be that `configuration`does not have a return type declared.

this is the code for injector and its singleton implementation

**Comment by escamoteur** [comment]
Yeah, I guess Dart has a problem infferring the type for factory constructors please do

`` Dart
GetIt.I.registerLazySingleton<Injector>(() => SingletonInjector.configuration(RepoType.PROD));
```

which is the correct way if you don't use a named instance

**Comment by computervirus91** [comment]
> Yeah, I guess Dart has a problem infferring the type for factory constructors please do
> 
> `` Dart
> GetIt.I.registerLazySingleton(() => SingletonInjector.configuration(RepoType.PROD));
> 
> ```
> 
> which is the correct way if you don't use a named instance
> ```

thank you for your reply
