### ISSUE TITLE
can't access to getIt when the app in background state 

### ISSUE THREAD

**Issue by dali010** [fluttercommunity/get_it#390]
I am using Firebase Cloud Messaging with a background message handler, annotated with @pragma('vm:entry-point'), in my Flutter app. Inside the background handler, I call getIt as my service locator to obtain an AudioPlayer instance. However, I encounter the following error:

An error occurred in your background messaging handler:
Bad state: GetIt: Object/factory with type AudioPlayer is not registered inside GetIt. 
(Did you accidentally do GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;
Did you forget to register it?)
I have registered AudioPlayer with GetIt and injectable, and it works fine in the foreground state handler for Firebase setup. My dependency injection is set up as follows:

Injection file:

```
final getIt = GetIt.instance;

@InjectableInit()
Future<void> configureDependencies() => getIt.init();
```
Dependency Module:

```
@module
abstract class CoreModule {
  @lazySingleton
  AudioPlayer get audioPlayer => AudioPlayer();
  // Other dependencies...
}
```
Firebase Messaging Setup:

`FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);`

Background Handler:

```
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage notificationResponse) async {
  final audioPlayer = getIt<AudioPlayer>();
  // Additional code...
}
```

**Comment by escamoteur** [comment]
I m pretty sure that when your app gets called via that entry point it's a different isolate so you have to register your objects again
Am 13. Nov. 2024, 09:56 +0100 schrieb dali010 ***@***.***>:

**Comment by dali010** [comment]
I read about that in firebase documentation [background handler](https://firebase.flutter.dev/docs/messaging/usage/#background-messages)
but I want to access to AudioPlayer instance injected to play audio

**Comment by escamoteur** [comment]
Are you using injectable?
Am 13. Nov. 2024, 10:06 +0100 schrieb dali010 ***@***.***>:

**Comment by escamoteur** [comment]
Then just register the objects you need manually via the get_it register methods at the start of your entry point
Am 13. Nov. 2024, 10:08 +0100 schrieb dali010 ***@***.***>:

**Comment by escamoteur** [comment]
Or call the init function that injectable generates (I'm not familiar with injectable)
Am 13. Nov. 2024, 10:09 +0100 schrieb ***@***.***:

**Comment by dali010** [comment]
I think  when I register it manually the previous registered instance will be ecrased

**Comment by dali010** [comment]
ahh Okay, thank you <3

**Comment by escamoteur** [comment]
btw we have a new forum https://forum.itsallwidgets.com

**Comment by dali010** [comment]
nice, I can make a question on that forum or I mark the current issue as closed and find another solution ?

**Comment by escamoteur** [comment]
Both close this one and ask new questions in the forum
Am 13. Nov. 2024, 13:32 +0100 schrieb dali010 ***@***.***>:
