### ISSUE TITLE
dependsOn confusion

### ISSUE THREAD

**Issue by Reprevise** [fluttercommunity/get_it#40]
I'm a bit confused on the `dependsOn` syntax. Before I was using `readyFuture` and that worked fine but I decided to try the new beta version. Here's how I register my singletons.

```dart
  getIt.registerSingletonAsync<AndroidDetails>(
    (_) => AndroidDetailsImplementation()..init(),
  );
  getIt.registerSingletonAsync<ThemeService>(
    (_) => Future<ThemeService>.value(ThemeService()),
    dependsOn: <Type>[AndroidDetails],
  );
```

I keep getting `The method <method name> was called on null` since I'm using `_details.<method name>()`.

Here's my `ThemeService` constructor:

```dart
  ThemeService() {
    _details = getIt.get<AndroidDetails>();
    settings = Hive.box<dynamic>(DatabaseHelper.SETTINGS_BOX);
  }
```

Am I doing something wrong? Should I be using `getAsync`? 

EDIT: Here's my `AndroidDetailsImplementation` init() function:

```dart
  Future<void> init() async {
    try {
      final AndroidDeviceInfo _deviceInfo = await DeviceInfoPlugin().androidInfo;
      _deviceData = getDeviceData(_deviceInfo);
    } on PlatformException {
      _deviceData = <String, dynamic>{
        'Error:': 'Failed to get platform version.',
      };
    }
  }
```

**Comment by Reprevise** [comment]
I think I fixed the issue by using the `Completer` manually and awaiting it in my `main()` function.

**Comment by escamoteur** [comment]
@Reprevise This will change mostly back to the way before with a lot of improvements

**Comment by Reprevise** [comment]
Sounds good @escamoteur, what kind of improvements will there be?

**Comment by escamoteur** [comment]
async factories with dependencies but easier to use
also a new registerSingletonWithDependencies

**Comment by Reprevise** [comment]
Sounds cool! What version will these changes be released on? The next one?

**Comment by escamoteur** [comment]
Yep, I guess next week
