### ISSUE TITLE
Question: Is GetIt capable of changing singleton in runtime?

### ISSUE THREAD

**Issue by lazarvgd** [fluttercommunity/get_it#42]
Is it possible to dynamically change object in runtime using GetIt. For example:
Let's say that there is abstract class DataSource, with two concrete implementation, LocalDataSoruce and NetworkDataSource. Is it possible to make GetIt return one or the other service depending on configuration that user can set in runtime?

Thanks

**Comment by escamoteur** [comment]
sure you can do this. Either use two different registrations at startup or reregister the type again but therefore you have to set 

```Dart
  /// By default it's not allowed to register a type a second time.
  /// If you really need to you can disable the asserts by setting[allowReassignment]= true
  bool allowReassignment = false;
```

to true

**Comment by ezzabuzaid** [comment]
it would be very helpful if there `allowReassignment` on service level registration
```dart
  _locator.registerSingleton<T>(instance, allowReassignment: true);
```

**Comment by escamoteur** [comment]
Why on registration level? what's wrong with globally enable it if you really need it?
In many cases unregister and then register anew is the cleaner options. Possible using a scope.

**Comment by PhilipPurwoko** [comment]
```dart  
  /// By default it's not allowed to register a type a second time.
  /// If you really need to you can disable the asserts by setting[allowReassignment]= true
  bool allowReassignment = false;
```

By changing to true this mean I need to change the code in a package, or just copy and paste the whole `_GetItImplementation` into my app code just to config it. Should have the better way. I agree with @ezzabuzaid
