### ISSUE TITLE
Quick question: does storing BuildContext in get_it causes a memory leak?

### ISSUE THREAD

**Issue by karmazinkd** [fluttercommunity/get_it#43]
I'm registering a singleton with FirebaseMessagingHelper class in get_it so I can have access to its instance throughout the code, which is really useful.

But there are some callbacks where I want to open new pages in my Flutter app. For this, I need a **context**.

Is it ok to pass and store a BuildContext there and keep it as a singleton in get_it? Would it cause a memory leak (like in plain Android for example)?

What I want to do is to initialize my FirebaseMessagingHelper and pass there a BuildContext from the MyApp stateful widget, then I register it as a Singleton.

```
GetIt.instance
      .registerSingleton<FirebaseNotificationsHelper>(FirebaseNotificationsHelper(context)) 
```

**Comment by escamoteur** [comment]
You can do that but you should use a root context close to the first page of your app, so that it doesn't get removed
