### ISSUE TITLE
Need an example of defining an instance which will be rebuild when listening to a Stream of another instance

### ISSUE THREAD

**Issue by dungnv2602** [fluttercommunity/get_it#44]
I have a service which exposes a Stream, what I want is defining an instance which has a subscription listening to that Stream and rebuilds itself when that Stream emits a new value. This case pretty much the same as using ProxyProvider in Provider package. How do I do it in get_it? An example of code will be much appreciated.

**Comment by escamoteur** [comment]
What about using a StreamBuilder?

**Comment by dungnv2602** [comment]
> What about using a StreamBuilder?
I want to provide it everywhere in the app. If wrapping the entire MaterialApp in StreamBuilder that means it will rebuild the whole app when new value emits.

**Comment by escamoteur** [comment]
Get_It does not update anything in the UI! You have to register an Object that either publishes an ChangeNotifier or a Stream as a property to signal the UI that it should update.

Then you you can use this object as data source at any place of your UI and use their either an StreamBuilder or an AnimatedBuilde (if you choose ChangenNotifiers)

I'm not really clear where your problem is.

**Comment by dungnv2602** [comment]
What I want is to register an instance that can update its value based on another registered instance's value (a Stream or ChangeNotifier). Then when I use locator<>(), the value of that instance already be updated. As I said, it's like a ProxyProvider.

**Comment by dungnv2602** [comment]
I hope the code will describe my problem properly
```
        StreamProvider<ImagesConfiguration>(
          create: (context) =>
              Provider.of<TmdbRemoteDataSource>(context, listen: false)
                  .onConfigurationChange,
        ),
        ProxyProvider2<ImagesConfiguration, AssetQualitySettings,
            AssetResolver>(
          update: (_, configuration, qualitySettings, assetRevolver) =>
              AssetResolver(
            configuration,
            qualitySettings,
          ),
        ),
```
From the code above, you can see that `AssetResolver's configuration` is updated every time `ImagesConfiguration` update. I want that in get_it either. I'm having trouble migrating from Provider to get_it

**Comment by escamoteur** [comment]
Updates like that are not supported directly from GetIt. Provider has there anotehr philosopie in that it includes some state management whereas get_it is a pure locator. I always recomens to use get_it togeteher with Streams .
