### ISSUE TITLE
GetIt V4 release candidate is out

### ISSUE THREAD

**Issue by escamoteur** [fluttercommunity/get_it#46]
Hi,

I uploaded the release candidate for V4 on pub: https://pub.dev/packages/get_it/versions/4.0.0-release-candidate

Please give it a try. It contains:

* Breaking changes in API!!! and also to the  beta before!!
* Release candidate
* New Async functions
* Factories with parameters
* Improved startup synchronisation
* https://github.com/fluttercommunity/get_it/issues/41
* https://github.com/fluttercommunity/get_it/issues/33
* https://github.com/fluttercommunity/get_it/issues/29

Please also read the documentation and tell me here if something isn't clear or even better make an PR on the readme file ;-)

**Comment by lanmonster** [comment]
Is there a migration guide for the breaking changes?

**Comment by escamoteur** [comment]
The changes are minimal so shouldn't be a problem this time. If you need help just ask here.

**Comment by ThinkDigitalSoftware** [comment]
Yes, been waiting for #41. Thank you!

**Comment by Kavantix** [comment]
Really like what you ended up with for the async factory/singletons!

**Comment by escamoteur** [comment]
Thanks!

**Comment by thor-jc** [comment]
I was just hitting the fact that my async singletons were not loading 'in-time' yesterday and found this new version published.  Great additions!

Regards,
John
ps quick note ->
Can you implement a logger with levels that we can control via config?  (or remove print statements?)
get_it_impl.dart -> line 533

`void _register<T, P1, P2>({
    @required _ServiceFactoryType type,
    FactoryFunc<T> factoryFunc,
    FactoryFuncParam<T, P1, P2> factoryFuncParam,
    FactoryFuncAsync<T> factoryFuncAsync,
    FactoryFuncParamAsync<T, P1, P2> factoryFuncParamAsync,
    T instance,
    @required String instanceName,
    @required bool isAsync,
    Iterable<Type> dependsOn,
    @required bool shouldSignalReady,
  }) {
    print(T.toString());
`. ....

**Comment by HeikoMueller** [comment]
The isRegistered method seems not to work for me on Android : 

Using Version 4.0.1, registering async Singletons conditionally. Then I use 
 if(locator.isRegistered<TypeName>()) {...}
for checking if the particular "TypeName" has been registered or not. This works on iOS, but on Android, it runs into an error :

'instanceFactory != null': No type TypeName is registered inside GetIt.
