### ISSUE TITLE
Is relative vs package imports still an issue?

### ISSUE THREAD

**Issue by jibbers42** [fluttercommunity/get_it#49]
The docs warn
> Extremely important if you use GetIt: ALWAYS use the same style to import your project files either as relative paths OR as package which I recommend. DON'T mix them because currently Dart treats types imported in different ways as two different types although both reference the same file.

However I'm wondering if this issue has been solved (and released in possibly Dart 2.1) via
https://github.com/dart-lang/sdk/issues/33076

My tools tend to suggest relative imports at times and I'm curious if I actually need to be diligent about this.

Is it no longer an issue?

**Comment by escamoteur** [comment]
Interesting catch! From what I read this shouldn't now longer be a problem. Could you give it a try and test if it works if you register a type via package but get it in another file with relative import?

**Comment by escamoteur** [comment]
It seems it's no longer a problem
