### ISSUE TITLE
Async Registering, compact model fails

### ISSUE THREAD

**Issue by dekadevelop** [fluttercommunity/get_it#51]
Hi,
if I use:
`getIt.registerSingletonAsync<ConfigService>(() async => ConfigService()..init());`
the service's registration is not awaited, and it's not working

meanwhile if I use the following, everything is working fine:
```
getIt.registerSingletonAsync<ConfigService>(() async {
    final configService = ConfigService();
    await configService.init();
    return configService;
  });
```

**Comment by escamoteur** [comment]
interesting. can you try to add an await in the first version?

**Comment by dekadevelop** [comment]
- If I put an await like in the following:
`getIt.registerSingletonAsync<ConfigService>(() async => await ConfigService()..init());`
I get a warning which says that the await is not awaiting any Future. That's because it is awaiting on the ConfigService() instance.

- if I remove the double dots, to await correctly on the init() method:
`getIt.registerSingletonAsync<ConfigService>(() async => await ConfigService().init());
`
The init is awaited, but then the service will be registered with the instance returned from the init() method, and not the ConfigService(), so when you use it you get an Exception

**Comment by escamoteur** [comment]
Ok, then this is my fault that my tests didn't check if that case does really wait and not just complete. I will upddate the docs

**Comment by escamoteur** [comment]
If you write the init function like this it will work with one dot:
```Dart
  class RestService {
    Future<RestService> init() async {
      Future.delayed(Duration(seconds: 1));
      return this;
    }
  }
```
