### ISSUE TITLE
Question about garbage collector

### ISSUE THREAD

**Issue by TheVinhLuong** [fluttercommunity/get_it#56]
Are instances returned by a factory eligible for garbage collection? And how about singleton?

**Comment by escamoteur** [comment]
GetIt doeesn't keep any referenes to Objects created by Factories.

It has to keep references to Singletons to be able to access them though. Howver you can dispose them manually. By calling `unregister` you can free a Singleton and even pass a disposing function.

**Comment by kmartins** [comment]
@escamoteur The `resetLazySingleton` works the same that `unregister` discarding the `Singleton`?

**Comment by escamoteur** [comment]
yep, reset also frees the existing instance

**Comment by kmartins** [comment]
Ok, so in the question of performance, I can use `registerLazySingleton` with `resetLazySingleton` without problems?  Or it would be better always use `unregister`?

**Comment by escamoteur** [comment]
with LazySingletons you can always just use reset unless you want to remove the registrataion which would lead to an exception on the next access if you don't reregister it. Performance difference is not the point.
