### ISSUE TITLE
Where to initialize serviceLocator in clean architecture?

### ISSUE THREAD

**Issue by manjrekarom** [fluttercommunity/get_it#64]
I am following clean architecture tutorial from Resocoder [https://resocoder.com/flutter-clean-architecture-tdd/](url) and well that is how I got introduced to Get_it.

I have three questions to ask:
1. How many service locators should I have in an application?
2. Should I initialize the ServiceLocator in main?
3. How do I manage dependencies properly?

In the tutorial it is mentioned that I should have a separate **injection_container.dart** for each feature. The problem is that some of these features share dependencies due to which if I initialize them in the wrong order, Get_it throws an error. Also I am initializing all this together in main, is there a better way to do this?

If you could point me to a resource where I can read about this further that will be great.

**Comment by escamoteur** [comment]
Hi,
unless you have a good reason, you only should use one service locator

2. I typically do it in main.
3. Have you seen the new startup synchronization feature of GetIt? Check out: https://www.burkharts.net/apps/blog/lets-get-this-party-started-startup-orchestration-with-getit/
