### ISSUE TITLE
Wrong error message for non-async dependency

### ISSUE THREAD

**Issue by rhalff** [fluttercommunity/get_it#69]
It seems the error message is wrong when a non-async dependency is added to the `dependsOn` list when using `registerSingletonAsync`.

e.g:
```dart
..registerSingletonAsync<MyAsyncService>(
  () => MyAsyncService()..init(),
   dependsOn: [
      MySyncService,
   ],
)
```

Would give:

`Invalid argument(s): Dependent Type MySyncService is an async Singleton`

In this case `MySyncService` is a non-async singleton.

It should probably read: "is ***not*** an async Singleton"

**Comment by escamoteur** [comment]
Thanks for spotting. Fixed in next version
