### ISSUE TITLE
Integration tests - get_it  factories map is lost

### ISSUE THREAD

**Issue by yanivshaked** [fluttercommunity/get_it#76]
Hi,
In short: Problem is that registering several factories and singletones on get_it from the integration tests environment (e.g. app.dart file) has no effect and when the application starts running, the internal factories are lost.

In details: Using initServices() on the operational program, I am binding several abstract classes as follows:

`
    GetIt.I.registerLazySingleton<INetworkService>(() => NetworkService());
    GetIt.I.registerLazySingleton<ILocalization>(() => LocalizationService());
`

however, when using the integration tests environment, I would like to bind other implementations, so I'm calling initiServicesTestEnv() before running the app:

`  GetIt.I.registerLazySingleton<INetworkService>(() => NetworkServiceSimulator());
  GetIt.I.registerLazySingleton<ILocalization>(() => LocalizationMock());
`

but when the test starts running, the following statement fails:

`GetIt.I<INetworkService>();`

due to the following:

No type INetworkService is registered inside GetIt.
 Did you forget to pass an instance name? 
(Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;did you forget to register it?)
'package:tw_app/get_it/get_it_impl.dart':
Failed assertion: line 251 pos 14: 'instanceFactory != null'

**Comment by escamoteur** [comment]
Can you show me the test file where you call `GetIt.I<INetworkService>();`

**Comment by escamoteur** [comment]
Hi,
could you check that the import statements for `INetworkService` is not relative but a package reference at all places you use it?

**Comment by yanivshaked** [comment]
I'm not calling the `GetIt.I<INetworkService>();` from the test file. Only from the application itself.
The test consist of two files, 1st one is responsible for starting the application under test and the 2nd contains the test itself. The 1st file is:
```

import 'package:get_it/get_it.dart';
import 'package:flutter/material.dart';
import 'package:flutter_driver/driver_extension.dart';
import 'package:tw_app/main.dart' as app;

import '../lib/Services/Network/NetworkServiceSimulator.dart';
import '../lib/Services/Logger/ConsoleLoggerService.dart';
import '../lib/Services/Localization/LocalizationService.dart';

void main() {
  print('Test environment wakeup');
  // This line enables the extension.
  enableFlutterDriverExtension();

  // TODO: Pending answer on https://github.com/fluttercommunity/get_it/issues/76
  initServicesTestEnv();
  runApp(app.MyApp());
}

void initServicesTestEnv() async {
  GetIt.I.registerLazySingleton<INetworkService>(() => NetworkServiceSimulator());
  GetIt.I.registerLazySingleton<ILogger>(() => ConsoleLoggerService());
  GetIt.I.registerLazySingleton<ILocalization>(() => LocalizationService());
}

```

and as soon as the application starts running (from within runApp), the first call to `GetIt.I<INetworkService>();` fails.

**Comment by yanivshaked** [comment]
> Hi,
> could you check that the import statements for `INetworkService` is not relative but a package reference at all places you use it?

After converting all import statements for all abstract classes to package references, the problem is solved.
Can you please elaborate on the reason for this? Does it mean I have to use package reference from now on, or will there be a fix for this?

**Comment by escamoteur** [comment]
Please have a look at the explanation here https://github.com/dart-lang/sdk/issues/41868

**Comment by yanivshaked** [comment]
Thank you!
