### ISSUE TITLE
Suppor for using the same instanceName multiple times for different types

### ISSUE THREAD

**Issue by Pawelo93** [fluttercommunity/get_it#78]
Hello @escamoteur, I was wondering if it is possible to allow using same instance name for different class types. For example i have two kinds of repositories (different type) and and want to register two of them with name 'local', and all the others repositories with name 'remote'.

Thank you :)

**Comment by escamoteur** [comment]
I think allowing this would make GetIt more complex. You are the first one asking for this. If others want it too I will consider it.

**Comment by SAGARSURI** [comment]
I agree this is important. In Dagger we have the @Named annotation to get two different instances of the same type. Repository class may depends different type of local sources e.g moor or sqflite.

**Comment by joanofdart** [comment]
I still fail to see how you need multiple instances of the same repository for the same user o.O

**Comment by Pawelo93** [comment]
> I still fail to see how you need multiple instances of the same repository for the same user o.O

I guess you are not using much of abstraction in your codebase. Most complex example is in domain, with multiple use cases on same contract managing this with strings names or class types. But there is no other way so far.

Remember that im using injectable, library for generating get_it code, couse in bigger projects it is hard to manually maintain all dependencies.

**Comment by escamoteur** [comment]
When I would add this you would be required to pass always the type together the name when accessing your objects

**Comment by agubha** [comment]
@Pawelo93 is there any update on this issue?
if you solved it, how did you do it?

**Comment by escamoteur** [comment]
Hi, this is now supported in get_it V5.0.0
