### ISSUE TITLE
Setting values inside GetIt singletons directly

### ISSUE THREAD

**Issue by d-apps** [fluttercommunity/get_it#79]
Is it ok to set values inside variables of an instantiated class (singleton)? 

I have an app that will create Stores from MobX as singletons but I will need to change the obsevable variables inside this classes in runtime.

```
abstract class Test extends with Store {

     @observable
     String name;

}
```

If so it's ok to do this:

`Get.I<Store()>().name = "Test"`

**Comment by escamoteur** [comment]
Sure absolutely
