### ISSUE TITLE
using get_it in separated classes

### ISSUE THREAD

**Issue by MahdiPishguy** [fluttercommunity/get_it#8]
you suppose your sample code witch all of classes in one class as main, separated in some other class into another files, for example:

```
main
MyApp 
MyHomePage 
_MyHomePageState 
```

in this structure how can i get_it witch that defined in `main()` ? how can i registered classes in all of other classes?

**Comment by escamoteur** [comment]
You have to define a global variable that holds your GetIt instance

**Comment by basnetjiten** [comment]
@escamoteur  can you please help me with the code as well.
I have a situation where I need to change the value of global string called siteBaseUrl.
Now Based on user selection this siteBaseUrl will have to change. I have a get_it using SharedPreferenceServiceLocator. In main metod I have to change the base url value with the one stored in the sharedpreference;

**Comment by MahdiPishguy** [comment]
@escamoteur i hope to help you this links

https://stackoverflow.com/a/29182641/1830228
https://medium.com/@lawrey/flutter-global-variable-scopedmodel-568aab9f7901
