### ISSUE TITLE
Creating scoped instance

### ISSUE THREAD

**Issue by SAGARSURI** [fluttercommunity/get_it#83]
Is it possible to create scoped instances?
For example I have a login screen which depends on a loginBloc. LoginBloc's instance should be tied to the login screen lifecycle. The moment login screen widget is created, loginBloc instance should be created and injected. When the login screen is destroyed or disposed, loginBloc instance should be destroyed.

**Comment by escamoteur** [comment]
Not directly at the moment. You can create new instances manually  
https://github.com/fluttercommunity/get_it#more-than-one-instance-of-getit
