### ISSUE TITLE
Impossible to register inside GetIt

### ISSUE THREAD

**Issue by vince83110** [fluttercommunity/get_it#84]
I am using last version of the plugin, and here is my main.dart file : 

```
final di = GetIt.instance;

Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  _registerAppLevelObjects();
  _resetInProgressFlag();

  await DotEnv().load('.env');

  runApp(MyApp());
}

Future<void> _registerAppLevelObjects() async {
  di.registerSingleton(AppDatabase.getInstance());
  di.registerSingleton(DeviceInfoPlugin());
  di.registerSingleton(DeviceInfoRepository(di.get()));
  di.registerSingleton(Api(di.get()));
  di.registerSingleton(DossierRepository(di.get(), di.get()));
  di.registerSingleton(CenterRepository(di.get()));
  di.registerSingleton(SharedPreferences.getInstance());
}

Future<void> _resetInProgressFlag() async {
  final repo = di.get<DossierRepository>();
  repo.resetInProgressFlag();
}
```

And I have the error : 

> E/flutter ( 3834): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 251 pos 14: 'instanceFactory != null': No type Api is registered inside GetIt.
> E/flutter ( 3834):  Did you forget to pass an instance name?
> E/flutter ( 3834): (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;did you forget to register it?)

Only DossierRepository relies on Api, so I guess the order is good. How can I debug it ?

**Comment by escamoteur** [comment]
I think you really should use types im as generic parameters. Im not sure that the compiler will guess all types correctly

**Comment by escamoteur** [comment]
Also, are you sure that your `_registerAppLevelObjects` has completed when you call `_resetInProgressFlag`?
Check out the startup synchronization functions of GetIt https://www.burkharts.net/apps/blog/lets-get-this-party-started-startup-orchestration-with-getit/

**Comment by escamoteur** [comment]
closing this because of no response
