### ISSUE TITLE
Benefits over singleton

### ISSUE THREAD

**Issue by ncuillery** [fluttercommunity/get_it#87]
I'm wondering what are the benefits of this package over plain simple Dart singletons.

With singletons, you can make an instance of a class available everywhere in your code base, by leveraging the Dart import mechanism (no global variable).

So I'm wondering _why_ would I use get_it. So far, I see that get_it offers a better testability.

It also seems that the laziness would require a bit of boilerplate in singleton, that I wouldn't have to write with get_it

 Is there anything else?

**Comment by creativecreatorormaybenot** [comment]
Seems like I had the same question just now 😄 (#88)

My question is a bit more concrete than yours → possible answer to your question: `get_it` supports a lot more than plain singletons, like named singletons, `async` stuff, non-lazy, etc.

**Comment by escamoteur** [comment]
Main difference to a singleton is that you can easily switch out implementations.

Furthermore:
* Singletons normally can't be reasigned or resetted
* GetIt offers besides Singletons Factories
* It suports async Singletons
* It has support for async startup synchronisation

**Comment by ncuillery** [comment]
Thanks for the explanation!
