### ISSUE TITLE
If I only use registerLazySingleton, is there an advantage over a static instance?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [fluttercommunity/get_it#88]
Taking a look at the Flutter framework, you will notice the following pattern for singletons:

https://github.com/flutter/flutter/blob/4d7525f05c05a6df0b29396bc9eb78c3bf1e9f89/packages/flutter/lib/src/services/raw_keyboard.dart#L493

```dart
  /// The shared instance of [RawKeyboard].
  static final RawKeyboard instance = RawKeyboard._();
```

I think that this is functionally equivalent to `get_it`'s `registerLazySingleton` as `final` variables that are ["top-level or class variable[s are] initialized the first time [they are] used"](https://dart.dev/guides/language/language-tour#final-and-const).

Am I correct with this assumption?

In that case, which is at least the most common use-case for me, I would not _need_ `get_it`. Then, only the additional features are appealing (might be worth a note in the README then) 🙃

**Comment by escamoteur** [comment]
Please see https://github.com/fluttercommunity/get_it/issues/87

What you are describing isn't lazy but will be instantiated immediately on App startup as its an static variable.
also the idea of the singleton pattern is that is should ensure that there really is only one instance in your app.

I would especially not the async support of GetIt and that you easily switch implementations

**Comment by creativecreatorormaybenot** [comment]
@escamoteur Are you sure about the instantiation part? I am pretty sure that this is not the case (see [article](https://dart.dev/guides/language/language-tour#final-and-const)).

**Comment by escamoteur** [comment]
Interesting, I'm not sure if this was implemented as discussed, but I will try to find out.

**Comment by escamoteur** [comment]
I just verified, you are correct. although I couldn't  find anything in the linked article, but maybe I oversaw something.
Anyway, all global variables and therefore static ones too are initialized lazy.
Thanks to point me to this.

**Comment by creativecreatorormaybenot** [comment]
@escamoteur Btw, the same applies to top-level `final` variables because they are also lazily initialized.

So, the following is true:

```dart
final topLevelSingleton = Singleton();
// The above is a shorthand for:

void main() {
  GetIt.instance.registerLazySingleton(() => Singleton());
}
```

As I said before, there are obviously advantages that `GetIt` can have - just in this basic usage it performs worse afaic.

**Comment by escamoteur** [comment]
Yeah only that you have then many global variables and you can not switch implementations.

**Comment by creativecreatorormaybenot** [comment]
@escamoteur Exactly.
