### ISSUE TITLE
Automatic registration via annotations? 

### ISSUE THREAD

**Issue by fzyzcjy** [fluttercommunity/get_it#90]
Thanks for the library! Shall we have some automatic registration via, for instance:

```
@Bean
class Apple { ... }
```

which will automatically generate some code like

```
GetIt.I.registerSingleton<Apple>(Apple());
```

using the [very famous code generator](https://pub.dev/packages/source_gen) used by a lot of packages.

Thanks!

**Comment by escamoteur** [comment]
There is a package `injectable` that does this for GetIt

**Comment by fzyzcjy** [comment]
Sounds wonderful!
