### ISSUE TITLE
Issue with reseting lazy Singletone

### ISSUE THREAD

**Issue by Sirrr** [fluttercommunity/get_it#92]
Below code will never call disposingFunction as it is first set to null then check if not null then function call.

    void resetLazySingleton<T>({...}) {
     ...
 
    instanceFactory.instance = null;
     ...

    if (instanceFactory.instance != null) {
      disposingFunction?.call(instanceFactory.instance as T);
     }
    }

**Comment by dannymanjon** [comment]
Yes, I noted the same, it need to check first the if test, and then set to null

**Comment by escamoteur** [comment]
fixed in V4.0.4
