### ISSUE TITLE
Locating instance variables

### ISSUE THREAD

**Issue by Bryanx** [fluttercommunity/get_it#95]
I have a some nested stores and would like to locate them all individually. What would be the best way to do this? At the moment I'm doing it like this:

```dart
// store structure:
class MainStore {
  var reminderStore = ReminderStore();
}

class ReminderStore {
  var taskStore = TaskStore();
}

// registering the instances:
var mainStore = new MainStore();
GetIt.instance.registerSingleton<MainStore>(mainStore);
GetIt.instance.registerSingleton<ReminderStore>(mainStore.reminderStore);
GetIt.instance.registerSingleton<TaskStore>(mainStore.reminderStore.taskStore);
```

**Comment by escamoteur** [comment]
I think it's perfectly fine to do it that way- But if you have them registered directly this way, Why do you nest them at all?

**Comment by Bryanx** [comment]
You were right, it was possible to remove nesting entirely. Thanks :)
