### ISSUE TITLE
registered FlutterLocalNotificationsPlugin give me error

### ISSUE THREAD

**Issue by akoua** [fluttercommunity/get_it#96]
When  I register  FlutterLocalNotificationsPlugin like this `slL.registerLazySingleton<FlutterLocalNotificationsPlugin>(
      () => FlutterLocalNotificationsPlugin());`, and want to call his `show()` method it's give me error like this: 

`I/flutter ( 7792): 'package:get_it/get_it_impl.dart': Failed assertion: line 251 pos 14: 'instanceFactory != null': No type FlutterLocalNotificationsPlugin is registered inside GetIt.
I/flutter ( 7792):  Did you forget to pass an instance name?
I/flutter ( 7792): (Did you accidentally do  GetIt sl=GetIt.instance(); instead of GetIt sl=GetIt.instance;did you forget to register it?)`

But when I create an instance of FlutterLocalNotificationsPlugin and register an instance of FlutterLocalNotificationsPlugin with GetIt, there are the same hashcode

**Comment by escamoteur** [comment]
Can you show me the code where you register and where you call the show method?

**Comment by akoua** [comment]
I can't give anymore informations. But I register that `slL.registerLazySingleton<FlutterLocalNotificationsPlugin>( () => FlutterLocalNotificationsPlugin());` and call it `slL<FlutterLocalNotificationsPlugin>()`

**Comment by escamoteur** [comment]
That is pretty strange because it's basically what GetIt is designed to do.
could you create a small repro project and put it on GitHub please?
